### ISSUE TITLE
[question]: Angular Routing Testing support

### ISSUE THREAD

**Issue by morenoisidro** [ngneat/spectator#110]
Hi, is it planned to support angular routing testing in the near future? Thx!

**Comment by NetanelBasal** [comment]
Sure

**Comment by LayZeeDK** [comment]
Any ideas for what could be useful, @morenoisidro?

Any ideas from you, @NetanelBasal?

**Comment by NetanelBasal** [comment]
We have to check out the "painful" points here.

**Comment by LayZeeDK** [comment]
Exactly

**Comment by LayZeeDK** [comment]
I remembered one thing from testing Router-related things.

If we have a component that subscribes to route parameters, it would be nice to have a utility function to create fake route parameters for testing purposes.

**Comment by LayZeeDK** [comment]
# Testing a routing component
_[Examle from Angular.io](https://angular.io/guide/testing#routing-component)_

```
// dashboard.component.ts
// (...)
export class DashboardComponent {
  constructor(
    private router: Router,
    private heroService: HeroService) {
  }

  gotoDetail(hero: Hero) {
    let url = `/heroes/${hero.id}`;
    this.router.navigateByUrl(url);
  }
}
```

```
// dashboard.component.spec.ts

const routerSpy = jasmine.createSpyObj('Router', ['navigateByUrl']);
const heroServiceSpy = jasmine.createSpyObj('HeroService', ['getHeroes']);

TestBed.configureTestingModule({
  providers: [
    { provide: HeroService, useValue: heroServiceSpy },
    { provide: Router,      useValue: routerSpy }
  ]
});

it('should tell ROUTER to navigate when hero clicked', () => {
  heroClick(); // trigger click on first inner <div class="hero">

  // args passed to router.navigateByUrl() spy
  const spy = router.navigateByUrl as jasmine.Spy;
  const navArgs = spy.calls.first().args[0];

  // expecting to navigate to id of the component's first hero
  const id = comp.heroes[0].id;
  expect(navArgs).toBe('/heroes/' + id,
    'should nav to HeroDetail for first hero');
});
```

Here, we simply want to verify that the side effect of triggering navigation happens when the button is clicked.

It would be nice to be able to add a `Router` spy object spying on methods such as `navigateByUrl` and `navigate`.

**Comment by LayZeeDK** [comment]
# Nested component tests
_[Examples from Angular.io](https://angular.io/guide/testing#nested-component-tests)_

## Stubbing `RouterOutlet`
```typescript
@Component({selector: 'router-outlet', template: ''})
class RouterOutletStubComponent {}

TestBed.configureTestingModule({
  declarations: [
    AppComponent,
    RouterOutletStubComponent,
  ]
})
```

**Comment by LayZeeDK** [comment]
# Router setup
_[Example from CodeCraft](https://codecraft.tv/courses/angular/unit-testing/routing/#_router_setup)_

A lot of setup is involved to use `RouterTestingModule` for tests.

We could create a test harness class similar to `Spectator` and `SpectatorWithHost` to have access to the `Router` and `Location` services and call `Router#initialNavigation`.

```typescript
describe('Router: App', () => {

  let location: Location;
  let router: Router;
  let fixture;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [RouterTestingModule.withRoutes(routes)], (1)
      declarations: [
        HomeComponent,
        SearchComponent,
        AppComponent
      ]
    });

    router = TestBed.get(Router); (2)
    location = TestBed.get(Location); (3)

    fixture = TestBed.createComponent(AppComponent); (4)
    router.initialNavigation(); (5)
  });
});
```

>1. We import our RouterTestingModule with our routes.
>2. We grab a reference to the injected Router.
>3. We grab a reference to the injected Location.
>4. We ask the test bed to create an instance of our root AppComponent. We don’t need this reference in our test specs but we do need to create the root component with the router-outlet so the router has somewhere to insert components.
>5. This sets up the location change listener and performs the initial navigation.

**Comment by NetanelBasal** [comment]
Sounds good. I'm too busy and can't work on it. If someone wants to contribute, it will be helpful.

**Comment by LayZeeDK** [comment]
What do you think, @morenoisidro?

**Comment by dirkluijk** [comment]
I'll see what I can do.

Add a previous project I used this stub implementation for `ActivatedRoute` which was really helpfull.

```typescript
import { ActivatedRoute, ActivatedRouteSnapshot, convertToParamMap, Data, ParamMap, Params } from '@angular/router';
import { BehaviorSubject, Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export class ActivatedRouteStub extends ActivatedRoute {
  private _testParams: Params = {};
  private _testData: Data = {};

  private paramsSubject = new BehaviorSubject(this.testParams);
  private dataSubject = new BehaviorSubject(this.testData);

  constructor(options?: {
    params?: Params,
    data?: Data
  }) {
    super();

    if (options) {
      this.testParams = options.params || {};
      this.testData = options.data || {};
    }

    this.params = this.paramsSubject.asObservable();
    this.data = this.dataSubject.asObservable();
  }

  get paramMap(): Observable<ParamMap> {
    return this.paramsSubject.asObservable().pipe(
      map(params => convertToParamMap(params))
    );
  }

  get snapshot(): ActivatedRouteSnapshot {
    const snapshot = new ActivatedRouteSnapshot();

    snapshot.params = this._testParams;
    snapshot.data = this._testData;

    return snapshot;
  }

  set testParams(params: Params) {
    this._testParams = params;
    this.paramsSubject.next(params);
  }

  set testData(data: Data) {
    this._testData = data;
    this.dataSubject.next(data);
  }

  get testParams(): Params {
    return this._testParams;
  }

  get testData(): Data {
    return this._testData;
  }

  get children(): ActivatedRouteStub[] {
    return [this];
  }

  get parent(): ActivatedRouteStub {
    return this;
  }

  detectChanges(): void {
    this.dataSubject.next(this._testData);
    this.paramsSubject.next(this._testParams);
  }

  toString(): string {
    return 'activatedRouteStub';
  }
}
```

**Comment by dirkluijk** [comment]
I have a proposal for Spectator v4 with a `createRoutedComponentFactory()` which returns a factory for `SpectatorWithRouting`.

It includes all existing Spectator features, with additionally:
- an integrated `ActivatedRouteStub` with a clean API
- support for changing the route params, queryParams and data
- support for configuring `Routes`
- support for auto-mocking routerLink directives
- automatically loads RouterTestingModule

I will need to write unit tests and test on an existing project, expect more information soon.

**Comment by dirkluijk** [comment]
https://github.com/NetanelBasal/spectator/pull/151

**Comment by dirkluijk** [comment]
Routing support has just been released in `4.0.0`. Please consult the [README](https://github.com/ngneat/spectator/blob/master/README.md#testing-with-routing) for more details about this new feature.

**Comment by LayZeeDK** [comment]
Great addition 💪 I'm not sure it covers all these use cases though.

**Comment by vpArth** [comment]
Just a note: don't forget to provide correct imports to your `createRoutingFactory`:

```js
  const createComponent = createRoutingFactory({
    component: AppComponent,
    imports: [RouterModule.forRoot([])],
  });
```
