### ISSUE TITLE
Migrate from Gitbook to Wiki

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/spectator#137]

**Comment by dirkluijk** [comment]
Why, did you encounter issues with Gitbook? And what wiki do you have in mind?

**Comment by NetanelBasal** [comment]
The same. It's easier to contribute.

**Comment by dirkluijk** [comment]
+1

**Comment by MartinNuc** [comment]
We have issues with gitbook - it uses some weird DNS configuration and basically only first html render works for us. When navigated in SPA the page doesnt show up.

**Comment by PowerKiKi** [comment]
By Wiki did you mean GitHub's wiki ? If so it is not possible to create a PR on the wiki. Unless if you meant to have the docs in the main repository, eg in a `docs` folder ?

**Comment by NetanelBasal** [comment]
@PowerKiKi this issue is not relevant anymore as we refactor the docs and move it to the README file in v4. Thanks anyway.
