### ISSUE TITLE
[Feature Request]: Query element by directive

### ISSUE THREAD

**Issue by twittwer** [ngneat/spectator#150]
At first, awesome lib - helps a lot at testing 👍 

For me it would be nice if it would be possible to query an element by its component class.

Currently `spectator.query(MyComponent)` will return the component instance, but it would be nice to retrieve the native or debug element. I think a good option to provide this would be by the second argument, where it's currently possible to get a component's service.
`spectator.query(MyComponent, { element: true })`

In my opinion it would be also more intuative to switch the defaults. So `spectator.query(MyComponent)` would return an element, like `spectator.query('my-component').
`spectator.query(MyComponent): HTMLElement`
`spectator.query(MyComponent, { instance: true }): MyComponent`
`spectator.query(MyComponent, { read: SomeService }): SomeService`

I'm interested in contributing this myself, if the idea is approved. ([my current entrypoint](https://github.com/NetanelBasal/spectator/blob/7ae901860704ce50f26f7753b6d6101e83761b2b/projects/spectator/src/lib/internals.ts#L345))

Kind regards

**Comment by NetanelBasal** [comment]
We support it:

```ts
const { nativeElement } = spectator.query(ChildComponent, {
  read: ElementRef
});
```

**Comment by dirkluijk** [comment]
Yeah, I don't think it's good to expose DebugElement. After all, that's what makes Spectator great: encapsulate the inferior TestBed/DebugElement API's in a cleaner API.

I think it is nice that you can now choose what fits best:
```typescript
spectator.query('.some-selector'); // to query for a HTML element
spectator.query(SomeComponent); // to query for a component instance

spectator.query('.some-selector', { read: SomeDirective }); // to query for an instance by selector
spectator.query(SomeComponent, { read: ElementRef }); // to query for an element by instance
```

What is your use case / what does your test code now look like?

**Comment by NetanelBasal** [comment]
@dirkluijk we already support it ^^

**Comment by NetanelBasal** [comment]
We expose the `debugElement` through `spectator.debugElement` if you need more control.

**Comment by twittwer** [comment]
> We support it:
> 
> ```ts
> const { nativeElement } = spectator.query(ChildComponent, {
>   read: ElementRef
> });
> ```

Oh, I did not think about that option 🙈 

My use case for the debug element is a cascaded query.
Here is the test code before spectator:
```
const datagridRows = fixture.debugElement.queryAll(By.directive(ClrDatagridRow));
const cellsOfFirstRow = datagridRows[0].queryAll(By.directive(ClrDatagridCell));
```

**Comment by NetanelBasal** [comment]
That's an interesting example.

**Comment by dirkluijk** [comment]
Why not:
```
spectator.queryAll('datagrid-row:nth-of-type(1) datagrid-cell');
// or
spectator.queryAll('datagrid-row:nth-of-type(1) datagrid-cell', { read: ClrDatagridCell })
```
Where `datagrid-row` and `datagrid-cell` are the selectors.
Not tested but should work I think.

**Comment by twittwer** [comment]
I'm not sure, but it seems to me a bit more decoupled to work with the component classes.

**Comment by dirkluijk** [comment]
Closing this issue as the desired functionality is provided by Spectator. 

Feel free to open a new ticket if you have additional ideas or questions!
