### ISSUE TITLE
Renaming suggestions (v4)

### ISSUE THREAD

**Issue by dirkluijk** [ngneat/spectator#158]
Currently we have:

* `createTestComponentFactory` returning a factory for `Spectator`
* `createHostComponentFactory` returning a factory for `SpectatorWithHost`
* `createRoutedComponentFactory` returning a factory for `SpectatorWithRouting`
* `createHostDirectiveFactory` returning a factory for `SpectatorForDirective`
* `createServiceFactory` returning a factory for `SpectatorService`
* `createHttpFactory` returning a factory for `SpectatorHttp`

This feels a bit inconsistent. What about:

* `createComponentFactory` returning a factory for `Spectator`
* `createComponentWithHostFactory` returning a factory for `SpectatorWithHost`
* `createComponentWithRoutingFactory` returning a factory for `SpectatorWithRouting`
* `createDirectiveFactory` returning a factory for `SpectatorDirective`
* `createServiceFactory` returning a factory for `SpectatorService`
* `createHttpFactory` returning a factory for `SpectatorHttp`

This would mean a bit more breaking changes or deprecations, so I am not sure.

**Comment by NetanelBasal** [comment]
I am in. I think it's the right time now as we have more breaking changes. But I think `createComponentWithHostFactory` and `createComponentWithRoutingFactory` are too long. How about `createHostFactory` and `createRoutingFactory`.

- `createComponentFactory` returning a factory for Spectator
- `createHostFactory` returning a factory for SpectatorWithHost
- `createRoutingFactory` returning a factory for SpectatorWithRouting
- `createDirectiveFactory` returning a factory for SpectatorDirective
- `createServiceFactory` returning a factory for SpectatorService
- `createHttpFactory` returning a factory for SpectatorHttp

**Comment by dirkluijk** [comment]
👍 Agreed. 

I will change it asap. Would you keep the original names from v3 and deprecate them, or just remove it?

**Comment by NetanelBasal** [comment]
Let's deprecate them and remove them in v5.
