### ISSUE TITLE
Conflict with Jest matchers

### ISSUE THREAD

**Issue by bekos** [ngneat/spectator#168]
Nice project 👍 

On a Jest spec file, when importing anything, even from just `@ngneat/spectator/jest` the matchers change from Jest to Jasmine. 
For example this leads to `expect` from `jest.Expect` to turns into Jasmine's one, causing typescript complaining and losing all the autocomplete features for Jest, like `expect.objectContaining`.

**Comment by dirkluijk** [comment]
I will look into it, anytime soon. Thanks for reporting!_

**Comment by dirkluijk** [comment]
@bekos I tried reproducing it on a clean project with only Jest and Spectator but I have no issues. What `types` do you have in `tsconfig.spec.json`? 

![image](https://user-images.githubusercontent.com/2102973/64205197-b85d0c00-ce97-11e9-80fa-af7c5a47523d.png)

Can you share a repo or reproduce it [here](https://ng-run.com/edit/VIYdwKFVnEgIc2m6tQYz?test=true)?

**Comment by NetanelBasal** [comment]
@bekos maybe it's an IDE issue?

**Comment by bekos** [comment]
Sorry for the noise guys...probably something from another library interfering with the types! I created a new Nx project, just imported spectator and everything seems to work fine. Keep up the good work 👍

**Comment by dirkluijk** [comment]
No problem. Thanks!
