### ISSUE TITLE
Schematics documentation

### ISSUE THREAD

**Issue by mpetito** [ngneat/spectator#170]
Nice library! I might just be missing it, but it's unclear what schematics exist or how best to integrate this into an angular project.

For ex.,

 - can I change angular.json to use spectator for tests automatically?
 - is there a command to generate a spec file for an existing component?

**Comment by NetanelBasal** [comment]
> can I change angular.json to use spectator for tests automatically?

You don't need to change it. It's a library that works on top of Angular.

> is there a command to generate a spec file for an existing component?

## Schematics
Generate component, service and directive with Spectator spec templates with Angular Cli: (when using it as default)

**Component**
* Default spec: `ng g cs dashrized-name`  
* Spec with a host: `ng g cs dashrized-name --withHost=true`
* Spec with a custom host: `ng g cs dashrized-name --withCustomHost=true`

**Service:**
* Default spec: `ng g ss dashrized-name`
* Spec for testing http data service: `ng g ss dashrized-name --isDataService=true`

**Directive:**

`ng g ds dashrized-name`

## Default Schematics Collection

To use `spectator` as the default collection in your Angular CLI project,
add it to your `angular.json`:

```sh
ng config cli.defaultCollection @netbasal/spectator
```

The `spectator` schematics extend the default `@schematics/angular` collection. If you want to set defaults for schematics such as generating components with scss file, you must change the schematics package name from `@schematics/angular` to `@netbasal/spectator` in `angular.json`:

```json
"schematics": {
  "@ngneat/spectator:component": {
    "styleext": "scss"
  }
}
```

**Comment by mpetito** [comment]
This would be great to add to the readme.  I couldn't find mention of these new Spectator specific schematics other than in #82.

For existing projects, or in cases where a component already exists via `ng g c`, it would be nice if there was a switch to generate a spec file for an existing component.  Something like `ng g cs dashrized-name --spec-only`.  Or perhaps `ng g cs dashrized-name` would see the presence of the component .ts and absence of .spec.ts and infer `--spec-only` automatically.

**Comment by NetanelBasal** [comment]
Addded it to the README file, thanks!
