### ISSUE TITLE
How to test ngOnChanges in angular library that has many input property

### ISSUE THREAD

**Issue by Rajanusa** [ngneat/spectator#171]
Hi,

I would like to test ngOnChanges in angular library that has many input property.
Please find the code below.
isJSONSchema is a input property and based on that, value would converted and assigned to the field variable.

ngOnChanges() {
    if (this.isJSONSchema) {
      this.fields = [this.formlyJsonschema.toFieldConfig(this.jsonSchema)];
    }
    else {
      this.fields = this.jsonSchema;
    }
  }

Please advise.

Thanks
Raj

**Comment by benelliott** [comment]
You should test using a Host. See https://github.com/ngneat/spectator/issues/111

**Comment by Rajanusa** [comment]
I am getting this error when I use the component with host approach as per your documentation.
Error: Template parse errors:
Unexpected closing tag "SynapsePrimengNgxformComponentippy". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("engNgxformComponent [model]="model" [fields]="fields" [formGroup]="formGroup" [isJSONSchema]="true">[ERROR ->]</SynapsePrimengNgxformComponentippy>"): ng:///DynamicTestModule/HostComponent.html@0:112




describe('SynapsePrimengNgxformComponent-Host', () => {
  let spectator: SpectatorHost<SynapsePrimengNgxformComponent>;
  const createHost = createHostFactory(SynapsePrimengNgxformComponent);
  let formGroup: FormGroup = new FormGroup({});
  let model: any = {};
  let fields: FormlyFieldConfig[] = [
    {
      type: 'accordion',
      fieldGroup: [
        // step 1
        {
          key: 'accordion1',
          templateOptions: { label: 'accordion 1' },
          fieldGroup: [
            {
              key: 'firstname',
              type: 'input',
              templateOptions: {
                label: 'First name',
                required: true,
              },
            },
            {
              key: 'age',
              type: 'input',
              templateOptions: {
                type: 'number',
                label: 'Age',
                required: true,
              },
            },
          ]
        },

        // step 2
        {
          key: 'accordion2',
          templateOptions: { label: 'accordion 2' },
          fieldGroup: [
            {
              key: 'firstname',
              type: 'input',
              templateOptions: {
                label: 'First name',
                required: true,
              },
            },
            {
              key: 'age',
              type: 'input',
              templateOptions: {
                type: 'number',
                label: 'Age',
                required: true,
              },
            },
          ]
        },

        // step 3
        {
          key: 'accordion3',
          templateOptions: { label: 'accordion 3' },
          fieldGroup: [
            {
              key: 'firstname',
              type: 'input',
              templateOptions: {
                label: 'First name',
                required: true,
              },
            },
            {
              key: 'age',
              type: 'input',
              templateOptions: {
                type: 'number',
                label: 'Age',
                required: true,
              },
            },
          ]
        },
      ]
    },
  ];

  fit('Check ngOnChanges is called', () => {
    spectator = createHost(`<SynapsePrimengNgxformComponent [model]="model" [fields]="fields" [formGroup]="formGroup" [isJSONSchema]="true"></SynapsePrimengNgxformComponentippy>`, {
      hostProps: {
        model: model,
        fields: fields,
        formGroup: formGroup
      }
    });
    //spectator.detectChanges();
    spectator.component.fields = fields;
    spectator.component.formGroup = formGroup;
    spectator.component.model = model;
    spectator.component.isJSONSchema = true;
    spectator.detectChanges();
    expect(spectator.component.ngOnChanges()).toHaveBeenCalled();

  });

});

**Comment by benelliott** [comment]
`<SynapsePrimengNgxformComponent [model]="model" [fields]="fields" [formGroup]="formGroup" [isJSONSchema]="true"></SynapsePrimengNgxformComponentippy>`

Your closing tag doesn't match here.

**Comment by Rajanusa** [comment]
Hi,

Thanks for the response.
I get the following error though I pass the data.

Error: Template parse errors:
Can't bind to 'model' since it isn't a known property of 'SynapsePrimengNgxformComponent'. ("<SynapsePrimengNgxformComponent [ERROR ->][model]="model" [fields]="fields" [formGroup]="formGroup" [isJSONSchema]="true"></SynapsePrimengNgxfo"): ng:///DynamicTestModule/HostComponent.html@0:32
Can't bind to 'fields' since it isn't a known property of 'SynapsePrimengNgxformComponent'. ("<SynapsePrimengNgxformComponent [model]="model" [ERROR ->][fields]="fields" [formGroup]="formGroup" [isJSONSchema]="true"></SynapsePrimengNgxformComponent>"): ng:///DynamicTestModule/HostComponent.html@0:48
Can't bind to 'isJSONSchema' since it isn't a known property of 'SynapsePrimengNgxformComponent'. ("<SynapsePrimengNgxformComponent [model]="model" [fields]="fields" [formGroup]="formGroup" [ERROR ->][isJSONSchema]="true"></SynapsePrimengNgxformComponent>"): ng:///DynamicTestModule/HostComponent.html@0:90
'SynapsePrimengNgxformComponent' is not a known element:
1. If 'SynapsePrimengNgxformComponent' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHE
MA' to the '@NgModule.schemas' of this component. ("[ERROR ->]<SynapsePrimengNgxformComponent [model]="model" [fields]="fields" [formGroup]="formGroup" [isJSONSche"): ng:///DynamicTestModule/HostComponent.html@0:0



**The following are my uni test case.**


`
describe('SynapsePrimengNgxformComponent-Host', () => {


  @Component({ selector: 'host' })
  class HostComponent {
    myTitle = 'World';
  }

  let spectator: SpectatorHost<SynapsePrimengNgxformComponent, HostComponent>;
  const createHost = createHostComponentFactory({
    declarations: [
      SynapsePrimengNgxformComponent,
      ArrayTypeComponent,
      ObjectTypeComponent,
      FormlyFieldsTab,
      FormlyFieldAccordion
    ],
    component: SynapsePrimengNgxformComponent,
    imports: [
      CommonModule,
      FormsModule,
      PanelModule,
      TabViewModule,
      AccordionModule,
      FormlyPrimeNGModule,
      BrowserModule,
      BrowserAnimationsModule,
      ReactiveFormsModule,
      FormlyModule.forRoot(
        {
          types: formlytypes.types
        }),
    ],
    mocks: [FormlyJsonschema],
    host: HostComponent
  });
  let formGroup: FormGroup = new FormGroup({});
  let model: any = {};
  let fields: FormlyFieldConfig[] = [
    {
      type: 'accordion',
      fieldGroup: [
        // step 1
        {
          key: 'accordion1',
          templateOptions: { label: 'accordion 1' },
          fieldGroup: [
            {
              key: 'firstname',
              type: 'input',
              templateOptions: {
                label: 'First name',
                required: true,
              },
            },
            {
              key: 'age',
              type: 'input',
              templateOptions: {
                type: 'number',
                label: 'Age',
                required: true,
              },
            },
          ]
        },
        // step 2
        {
          key: 'accordion2',
          templateOptions: { label: 'accordion 2' },
          fieldGroup: [
            {
              key: 'firstname',
              type: 'input',
              templateOptions: {
                label: 'First name',
                required: true,
              },
            },
            {
              key: 'age',
              type: 'input',
              templateOptions: {
                type: 'number',
                label: 'Age',
                required: true,
              },
            },
          ]
        },

        // step 3
        {
          key: 'accordion3',
          templateOptions: { label: 'accordion 3' },
          fieldGroup: [
            {
              key: 'firstname',
              type: 'input',
              templateOptions: {
                label: 'First name',
                required: true,
              },
            },
            {
              key: 'age',
              type: 'input',
              templateOptions: {
                type: 'number',
                label: 'Age',
                required: true,
              },
            },
          ]
        },
      ]
    },
  ];


  fit('Check ngOnChanges is called', () => {
    spectator = createHost(`<SynapsePrimengNgxformComponent [model]="model" [fields]="fields" [formGroup]="formGroup" [isJSONSchema]="true"></SynapsePrimengNgxformComponent>`, {
      hostProps: {
        model: model,
        fields: fields,
        formGroup: formGroup
      }
    });
    spectator.detectChanges();
    spectator.component.ngOnInit();
    expect(spectator.component.fields).length>0;

  });

});
`

**Comment by benelliott** [comment]
Can you post `SynapsePrimengNgxformComponent`?
