### ISSUE TITLE
[QUESTION] Mocking properties get() and set()

### ISSUE THREAD

**Issue by irux** [ngneat/spectator#176]
Hello! A little question!

Do spectator support the spyOnProperty from jasmine ? or do we have other alternatives to mock properties ?

Thank you!

**Comment by NetanelBasal** [comment]
We support it. Check out https://github.com/ngneat/spectator/blob/f0e5d7a887114cfe6e1c2f42b2c6e0629d60c7c9/projects/spectator/test/spy-object/spy-object.spec.ts#L15

**Comment by dirkluijk** [comment]
Hi @irux ,

Yes. Spectator should not conflict with basic Jasmine/Jest functionality. As of the `mocks`, `mockProvider` and `createSpyObject` helpers, you can use `spyOnProperty` or just set the value through the setter.

* spyOnProperty(someService, 'yourProperty', 'get').and.returnValue(29); 
* someService.yourProperty = 29;

**Comment by AlixRoyere** [comment]
Hello, 

I've got an additional question. When using `mocks` option in spectator `createXXFactory()`, is it supposed to mock get() and set() properties on a service?
If so, how to check that it has been called in expect ? `expect(??).toHaveBeenCalledWith("toto");`

I'm using jest.
I've found an other way, but it's not using the mocks option.
```
const spectatorFactory = createXXFactory({
    // others params
    providers: [MyService],
  });

const spectator = spectatorFactory();
const myServiceSetUserMock = jest.spyOn(spectator.inject(MyService), "user", "set"); 
myServiceSetUserMock.mockImplementation();

// some action between

expect(myServiceSetUserMock).toHaveBeenCalledWith("toto");
```
