### ISSUE TITLE
Testing mouse events like double click or right click?

### ISSUE THREAD

**Issue by oba93** [ngneat/spectator#177]
Can't find how to test double click and right click in my app. It will be nice to have some documentation about this.

**Comment by NetanelBasal** [comment]
You should use `dispatchEvent`. For example: `dispatchEvent(new CustomEvent('contextmenu'))`.

Maybe we can add it to our API:
```ts
spectator.mouse.rightClick();
spectator.mouse.dblClick();
```

@dirkluijk thoughts?

**Comment by NetanelBasal** [comment]
Added new helpers - https://github.com/ngneat/spectator#mouse-helpers

**Comment by oba93** [comment]
Thanks for help.
