### ISSUE TITLE
Provide documentation for spectator v3

### ISSUE THREAD

**Issue by PhiSpindler** [ngneat/spectator#181]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>
 
I understand that it is easier to maintain documentation directly but it would be nice if documentation for older versions of spectator (v3) would still be available.

Sometimes it is hard to remember spectator functionality and the documentation helped a lot!

**Comment by NetanelBasal** [comment]
https://netbasal.gitbooks.io/spectator/content/
