### ISSUE TITLE
[QUESTION] Overwrite mockProvider values?

### ISSUE THREAD

**Issue by mailok** [ngneat/spectator#182]
Hello everyone. Congratulations for doing a good job with spectator!!

I have a question when I'm going to test a Service, My service uses HttpClient, so I did an HttpClient mock, of the get method which is the one I use:

```
const createService = createServiceFactory({
    service: ConfigService,
    providers: [
      mockProvider(HttpClient, {
        get: (url: string) => of(configSuccess)
      })
    ]
  });
```

but i want test a function in ConfigService, called **loadConfiguration**:

```
beforeEach(() => (spectator = createService()));

  test('should config to be success', () => {
    const configService = spectator.get(ConfigService);
    configService.loadConfiguration().then(() => {
      expect(configService.config).toEqual(configSuccess);
    });
  });

```

**configSuccess**  it's something like this: 

```
const configSuccess: Config = { baseUrl: 'www.localhost:8080', keycloakUrl: 'www.localhost:8081' };
```

the **loadConfiguration** function calls the HttpClient **get** inside it, but in my createServiceFactory, the function **get** will always return configSuccess.

And then I want to do a test where the get returns another value, for example:

```
const configError: Config = { baseUrl: 'failed', keycloakUrl: 'failed' };
```

and the test:

```
 test('should config to be error', () => {
    const configService = spectator.get(ConfigService);
    configService.loadConfiguration().then(() => {
      expect(configService.config).toEqual(configError);
    });
  });
```

How in this second test case do I overwrite the HttpClient get to return the other value?

**Comment by NetanelBasal** [comment]
You can return a different value in each `it` block.

```ts
const createService = createServiceFactory({
  service: ConfigService,
  providers: [mockProvider(HttpClient)]
});

it('should return success', () => {
  const http = spectator.get(HttpClient);
  http.and.returnValue(successConfig);
  configService.loadConfiguration(); 
  assertion...
})
```

Read about Jasmine/Jest spies/stubs.
