### ISSUE TITLE
Access to XMLHttpRequest at '' has been blocked by CORS policy:

### ISSUE THREAD

**Issue by Rajanusa** [ngneat/spectator#183]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The unit test on Angular library gives CORS error

## Expected behavior

The unit test case should pass

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## What is the motivation / use case for changing the behavior?

The following error is coming in the console.
```
zone-evergreen.js:2981 Access to XMLHttpRequest at 'ng:///DynamicTestModule/FormlyFieldsTab.ngfactory.js' from origin 'http://localhost:9876' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
This is not related to Spectator in any way.

**Comment by farhaan008** [comment]
![image](https://user-images.githubusercontent.com/5435421/123441706-c7272c80-d5f1-11eb-9ed4-b086c0728cf4.png)
getting same issue. Any resolution for this??
