### ISSUE TITLE
Could you please document that TypeScript 3+ is required for Spectator v4?

### ISSUE THREAD

**Issue by selangley-wa** [ngneat/spectator#184]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an Angular 6 project that uses Typescript 2.8.1.

Tests using Spectator v4.0.0 fail to compile with internal TypeScript errors.

Tests using Spectator v3.12.0 will compile for this project. 
(@netbasal/spectator@3.12.0)

## Expected behavior

The ReadMe or install page describes that Spectator v4 is for use with Typescript 3+

and that Spectator v3 can be used with TypeScript 2.x.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dirkluijk** [comment]
Our peer dependencies includes Angular 8+, which requires TS 3.4. Besides that, we included TS 2.8+ as peer dependency as well. Adding it to the readme may therfore not be needed?

What version are you using? Why not upgrading?

**Comment by NetanelBasal** [comment]
The library [depends](https://github.com/ngneat/spectator/blob/master/projects/spectator/package.json#L35) on `"typescript": ">= 2.8.0"`. We can't see any reason to add it specifically to the docs, but I will add it. Thanks for your feedback.
