### ISSUE TITLE
[question] Bootstrap entire app for integration-style test

### ISSUE THREAD

**Issue by ersimont** [ngneat/spectator#191]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

Please let me know if you'd like questions asked elsewhere. Looks like there are a number of closed issues where they were welcomed, so on we go...

Looking over the list of features, this library looks great. I prefer writing integration-level specs that initialize and drive large portions of an app, rather than isolated unit tests, and I'd like to discover whether this library will still work for me.

I installed the library and tried a very first attempt:
```ts
describe("AppComponent", () => {
  const createComponent = createComponentFactory({
    component: AppComponent,
    imports: [AppModule],
  });

  let spectator: Spectator<AppComponent>;

  beforeEach(() => {
    spectator = createComponent();
  });

  it("has a title", () => {
    expect(spectator.query("h1")).toHaveText("My App Title");
  });
});
```

With that I immediately met the error, "Type AppComponent is part of the declarations of 2 modules: AppModule and DynamicTestModule!" Is there a way around this?

I assume one fix would be to list out all my app dependencies in the test _except_ the app component, but that would be a non-starter for me. For a small app I'm working on currently, I want to fire up a full `AppComponent` for almost every test.

**Comment by NetanelBasal** [comment]
You can pass `declareComponent: false`.

**Comment by ersimont** [comment]
Fantastic! Sorry for a long winded question that had such a simple answer. I look forward to digging in more.
