### ISSUE TITLE
bitly short link at top of page no longer works

### ISSUE THREAD

**Issue by elio-maggini** [ngneat/spectator#194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The link to https://ng-run.com/edit/VIYdwKFVnEgIc2m6tQYz?test=true no longer works

## Expected behavior

The link should work

## Minimal reproduction of the problem with instructions
Steps to reproduce:
Click on the bit.ly short link found at top of https://github.com/ngneat/spectator page.

## What is the motivation / use case for changing the behavior?

Either the link should work or it should be removed.

## Environment

Any
Browser:
Any
 
<img width="1068" alt="Screen Shot 2019-10-04 at 4 26 56 PM" src="https://user-images.githubusercontent.com/54586689/66237723-d2bb1d00-e6c3-11e9-80a0-d0085456634c.png">

**Comment by dirkluijk** [comment]
Try again. It seems to work for me 😁

**Comment by elio-maggini** [comment]
This does work from my home network. I guess it is possible that my work network blocks the domain.
