### ISSUE TITLE
Component schematics do not respect the path provided with the name

### ISSUE THREAD

**Issue by kanafghan** [ngneat/spectator#195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running `ng g cs shared/components/carousel` produces:

```bash
CREATE src/app/shared/components/carousel/carousel.component.html (23 bytes)                      
CREATE src/app/shared/components/carousel/carousel.component.ts (273 bytes)                       
CREATE src/app/shared/components/carousel/carousel.component.scss (0 bytes)                        
CREATE src/app/shared/components/carousel/shared/components/carousel.component.spec.ts (514 bytes)
UPDATE src/app/shared/shared.module.ts (3589 bytes)                                               
Done in 3.62s.
```

The spec file is moved to `shared/components` within the generated component folder. The HTML, TypeScript and SCSS files are, however, placed in the correct location.

## Expected behavior

Running `ng g cs shared/components/carousel` should produce:

```bash
CREATE src/app/shared/components/carousel/carousel.component.html (23 bytes)                      
CREATE src/app/shared/components/carousel/carousel.component.ts (273 bytes)                       
CREATE src/app/shared/components/carousel/carousel.component.scss (0 bytes)                        
CREATE src/app/shared/components/carousel/carousel.component.spec.ts (514 bytes)
UPDATE src/app/shared/shared.module.ts (3589 bytes)                                               
Done in 3.62s.
```

## Minimal reproduction of the problem with instructions

Just run the component schematics as shown above.

## What is the motivation / use case for changing the behavior?

The component schematics from `@schematics/angular` already work as expected.

## Environment

<pre><code>
Angular version: 8.3.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] N/A
 
For Tooling issues:
- Node version: 10.15.3  
- Platform:  Windows 

Others:

- @ngneat/spectator: 4.3.4
</code></pre>

**Comment by kanafghan** [comment]
The fix for this one is very easy, we should do as done here: https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/component/index.ts#L138

I can provide a PR asap.

**Comment by dirkluijk** [comment]
That would be awesome. 😎
