### ISSUE TITLE
migrate to v4

### ISSUE THREAD

**Issue by DuncanFaulkner** [ngneat/spectator#197]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Migration.md says: "after upgrading to v4" run spectator-migrate

## Expected behavior

expect migration process to run

## Minimal reproduction of the problem with instructions
run "spectator-migrate" on the cmd line within the project

## What is the motivation / use case for changing the behavior?

spectator-migrate: command not found

## Environment

<pre><code>
Angular version: 8.2.9

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.0  
- Platform:  
Ubuntu 18.4

Others:

</code></pre>

**Comment by DuncanFaulkner** [comment]
Managed to run the script calling it

node node_modules/@ngneat/spectator/migrate.js

Not how the documentation describes it, though it's more likely I've not understood something.

**Comment by NetanelBasal** [comment]
You are right. The document isn't correct. It's fixed. Thanks.

**Comment by dirkluijk** [comment]
It should be possible to run `./node_modules/.bin/spectator-migrate` as well.

Not sure, but on my machine it at automatically adds `node_modules` to the current PATH. Maybe it's a zsh feature.
