### ISSUE TITLE
@custom/path can't be found

### ISSUE THREAD

**Issue by Maxstgt** [ngneat/spectator#198]
I'm working inside of an nrwl workspace. We write our own libraries and apps. We also use the default generated paths when we import a library inside of an app like: `@costumLib/data`.
But if I want to write a simple test like 
```
import { 
  createComponentFactory, 
  Spectator 
} from '@ngneat/spectator/jest';

describe('AppComponent', () => {
  const createComponent = createComponentFactory({
    component: AppComponent
  });
  let spectator: Spectator<AppComponent>;

  beforeEach(() => spectator = createComponent());

  it('should create the app', () => {
    const app = spectator.component;
    expect(app).toBeTruthy();
  });
  // more 'it' blocks
});
```
I get an error `Cannot find module '@costumLib/data' from 'app.component.ts'`
So I think there a problem with resolving the paths?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Spectator can't resovle `@custom/paths`

## Expected behavior

That we can use Spectator inside of a nrwl workspace

## Minimal reproduction of the problem with instructions
- Create a nrwl workspace and create two libs with the angular console they provide.
- Install spectator, jest, jest-preset, @types/jest and delete all the karma dependencies/files
- Use one spec file of your choice and do so like the code example above and run the test.

## What is the motivation / use case for changing the behavior?

To make Spectator the best library in the world ;)

## Environment

<pre><code>
Angular version: 8.1.3

 
For Tooling issues:
- Node version: 10.16.1
- Platform:  Ubuntu 18...
Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It's not related to Spectator. Spectator doesn't resolve anything. It's a TS issue, check your TS configuration, please. You can also ask on StackOverflow.

**Comment by Maxstgt** [comment]
Thanks, I will post my solution here if I find one

**Comment by Maxstgt** [comment]
So the problem was, that there were no tsconfig.spec.json in the root directory. ```{
  "extends": "./tsconfig.json",
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```
So this is an problem with nrwl and not with spectator. So I close this issue
