### ISSUE TITLE
Simple tests for injectables are failing with a TypeError

### ISSUE THREAD

**Issue by wescopeland** [ngneat/spectator#210]
## I'm submitting a...

<code>
[x] Support request
</code>

## Current behavior
Getting an error `Cannot read property 'getComponentFromError' of null` when writing basic tests for injectables (HTTP or otherwise).

## Expected behavior
No error should be displayed and the tests should pass.

## Minimal reproduction of the problem with instructions
```
import { SpectatorService, createServiceFactory } from '@ngneat/spectator';
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class UserService {
  constructor() {}
}

describe('Service: UserService', () => {
  let spectator: SpectatorService<UserService>;
  const createService = createServiceFactory(UserService);

  // Error is thrown here. TypeError: Cannot read property 'getComponentFromError' of null
  beforeEach(() => (spectator = createService()));

  it('exists', () => {
    expect(spectator.service).toBeDefined();
  });
});
```

## Environment

<pre>
<code>Angular version: 8.2.11 (latest)
Spectator version: 4.4.2
 
For Tooling issues:
- Node version: 12.6.0
- Platform: macOS 10.15

Others:
This is happening in an Nx 8.6 monorepo.</code>
</pre>

**Comment by dirkluijk** [comment]
It seems not to be related to Spectator (it works [here](https://ng-run.com/edit/qQBj4XZGVxv5oPGmRIC1?test=true)).

I think it has something to do with your test setup or with Nx workspaces. Are you using Jest? Maybe check [this issue](https://github.com/nrwl/nx/issues/1439).

**Comment by wescopeland** [comment]
Understood, thank you for pointing me in the right direction!
