### ISSUE TITLE
Angular build fails when there is Jest installed instead of Jasmine

### ISSUE THREAD

**Issue by ilchenkob** [ngneat/spectator#213]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a project where I've completely removed Jasmine and Karma. I use Jest for unit testing. There is nothing left from Jasmine in that project.
I've added `@ngneat/spectator` package to `devDependencies` and now the project building fails with the following error:

**ERROR in node_modules/@ngneat/spectator/lib/mock.d.ts(1,23): error TS2688: Cannot find type definition file for 'jasmine'.**

## Expected behavior
There should be a way to use `@ngneat/spectator` with Jest without need to install anything from Jasmine.

## Minimal reproduction of the problem with instructions
Add the following packages to `package.json` and try to build even empty app:
```javascript
"dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "^7.2.0",
    "@angular/elements": "^7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "ajv": "^6.9.1",
    "core-js": "^2.5.4",
    "document-register-element": "^1.8.1",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-builders/jest": "^7.4.4",
    "@angular-devkit/build-angular": "~0.13.2",
    "@angular-devkit/build-ng-packagr": "~0.13.2",
    "@angular/cli": "~7.2.4",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@ngneat/spectator": "^4.5.0",
    "@types/jest": "^24.0.19",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jest": "^24.9.0",
    "jest-preset-angular": "^7.1.1",
    "ng-packagr": "^4.2.0",
    "require-dir": "^1.2.0",
    "through2": "3.0.1",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.34.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
```
in the `tsconfig` I have the following:
```javascript
...
"types": [
      "jest",
      "node"
    ],
...
```

## What is the motivation / use case for changing the behavior?
Should be possible to use `@ngneat/spectator` without Jasmine installed.

## Environment

<pre><code>
Angular version: 7.2.0

Browser:
- not related to browser
 
For Tooling issues:
- Node version: 12.4.0
- Platform:  Windows 10 and MacOS 10.14.6

Others:

</code></pre>

**Comment by dirkluijk** [comment]
Maybe this is because you imported stuff from `@ngneat/spectator` that should instead be imported from `@ngneat/spectator/jest`. Can you double check this please?

**Comment by ilchenkob** [comment]
@dirkluijk 
I've double checked it before posting this issue. I had 4 spec files and all of them had imports to `@ngneat/spectator/jest' only

**Comment by NetanelBasal** [comment]
@ilchenkob, can you create a repo that reproduces the issue, please?

**Comment by ilchenkob** [comment]
@NetanelBasal 
You can find test repo at: https://github.com/ilchenkob/jest-test

**Comment by NetanelBasal** [comment]
I don't know how you configure Jest, but I just created a new CLI project and uses Jest [schematics](https://github.com/briebug/jest-schematic), and it works fine.

**Comment by ilchenkob** [comment]
`ng add @briebug/jest-schematic` adds Jest but it leaves `Jasmine` in the project.
So I think it should be stated somewhere in "Jest support" section that `@ngneat/spectator` supports Jest but it's required to have `Jasmine` in the project as well.

**Comment by NetanelBasal** [comment]
It seems that the only thing that you need is `@types/jasmine`. @dirkluijk any thoughts on this?

**Comment by ilchenkob** [comment]
Then maybe `@types/jasmine` should be added to dependencies list. What do you think about it?

**Comment by NetanelBasal** [comment]
I agree. I want to verify it with @dirkluijk.

**Comment by NetanelBasal** [comment]
I have added it to the latest version. Thanks.

**Comment by Dimanoid** [comment]
I had the same setup with jest without jasmine and karma and everything were fine on spectator@4.3.2, today I have updated to latest 4.5.1 and now there are a lot of conflict error between jasmine and jest types:
```
ERROR in ../../node_modules/@types/jasmine/ts3.1/index.d.ts:22:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: beforeAll, beforeEach, afterAll, afterEach, describe, fdescribe, xdescribe, it, fit, xit, expect, DEFAULT_TIMEOUT_INTERVAL, CustomMatcherFactory, CustomEqualityTester

22 type ImplementationCallback = jasmine.ImplementationCallback;
   ~~~~

  ../../node_modules/@types/jest/index.d.ts:33:1
    33 declare var beforeAll: jest.Lifecycle;
       ~~~~~~~
    Conflicts are in this file.
../../node_modules/@types/jasmine/ts3.1/index.d.ts:302:15 - error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.
```
After rolling back to 4.3.2 error are gone.

**Comment by the0rem** [comment]
This has broken my CI at the angular build stage; Just spent the best part of the day tracking it down. Can you please revert this fix?

**Comment by NetanelBasal** [comment]
@Dimanoid @the0rem I reverted this change.

**Comment by the0rem** [comment]
Thanks for the quick response @NetanelBasal :)

**Comment by Dimanoid** [comment]
Just checked 4.5.2, compiling ok. Thanks @NetanelBasal

**Comment by ilchenkob** [comment]
@Dimanoid 
Could you please show your `package.json`? Because I still have the same problem with 4.5.2

**Comment by davidefontana** [comment]
I also have the same problem. 
I tried every solution but i have the same error.

**Comment by davidefontana** [comment]
Ok maybe i find a solution.
Thats because i don't exclude some files in my tsconfig. 
Try add in tsconfig this 
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
For me works

**Comment by bboydflo** [comment]
> Ok maybe i find a solution.
> That's because i don't exclude some files in my tsconfig.
> Try to add in your tsconfig
> `"exclude": [ "node_modules", "**/*.spec.ts" ]`
> For me works

Thanks for this fix. It works for me too. I just wanted to add I am new to angular and didn't know exactly in which of the `tsconfig` to add these settings.

For me it worked when I added them to both `tsconfig.json` and `tsconfig.app.json`. If I only added them to `tsconfig.app.json` after I ran `tsc --noEmit` I was still getting the same issue. putting these settings in both files helped.

**Comment by gagle** [comment]
@bboydflo Excluding spec files will obviously remove tsc errors but this is not the real solution. I want to typecheck also spec files and I have this reference to jasmine type that throws the error.

**Comment by OleWahn** [comment]
Any update on this? The proposed fix

> Ok maybe i find a solution.
> That's because i don't exclude some files in my tsconfig.
> Try to add in your tsconfig
> `"exclude": [ "node_modules", "**/*.spec.ts" ]`
> For me works

does not work for me:

```json
"@ngneat/spectator": "^7.1.0",
"@types/jest": "^24.0.23",
"jest": "^26.6.3",
"jest-preset-angular": "^8.4.0",
```

Also, I agree with @gagle. This seems like a workaround rather than a fix.

**Comment by vaalgrind** [comment]
Any news on this?

**Comment by matheo** [comment]
Bump after almost 4 years :(

@NetanelBasal why not just remove `<reference types="jasmine" />` and let the tsconfig to get the namespace from jest or jasmine?
