### ISSUE TITLE
Upgrade from 3 -> 4: host.patchElementFocus was removed

### ISSUE THREAD

**Issue by fr0** [ngneat/spectator#214]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Old tests that call `host.patchElementFocus` do not work.

## Expected behavior

If this was removed intentionally, it should have been mentioned in the migration guide:  https://github.com/ngneat/spectator/blob/master/MIGRATION.md

**Comment by NetanelBasal** [comment]
Docs updated, thanks.
