### ISSUE TITLE
keyboard and mouse events should bubble

### ISSUE THREAD

**Issue by fr0** [ngneat/spectator#215]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In 3.X, I used: 

```
host.keyboard.pressEscape(window, 'keydown');
```

However, in 4.X, this is an error: `Cannot dispatch keyboard event: [object Window] is not a node`

## Expected behavior

IfI can't dispatch to the window, then I need some way for it to bubble up to the window. I think the keyboard and mouse events should bubble by default.

**Comment by NetanelBasal** [comment]
I'm not sure what's changed. We didn't touch this code.
