### ISSUE TITLE
createRoutingFactory routes with stubs: true (activatedRouteStub.setParam is not a function)

### ISSUE THREAD

**Issue by masaanli** [ngneat/spectator#216]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Getting an error on:
line => `spectator.setRouteParam("status", "nieuw");`
error =>  `TypeError: this.activatedRouteStub.setParam is not a function`

If I'm set `enableStubs: true` and add `RouterModule` to the imports, i'm getting the following error:
```
NullInjectorError: StaticInjectorError(DynamicTestModule)[RouterLinkWithHref -> LocationStrategy]: 
  StaticInjectorError(Platform: core)[RouterLinkWithHref -> LocationStrategy]: 
    NullInjectorError: No provider for LocationStrategy!
```

Code:
```ts
describe("TestPageComponent", () => {
    let spectator: SpectatorRouting<TestPageComponent>;

    const createComponent = createRoutingFactory<TestPageComponent>({
        component:  TestPageComponent,
        imports: [
            NoopAnimationsModule,
        ],
        mocks: [
            SomeService,
            Dialogs
        ],
        stubsEnabled: false,
        routes:  [
            { path: "", redirectTo: "status/new", pathMatch: "full" },
            { path: "status/:status", component: TestPageComponent }
        ]
    });

    beforeEach(inject([NgZone], (ngZone: NgZone) => {
        ngZone.run(() => {
            spectator = createComponent({ detectChanges: false });
        });
    }));

    // Working
    it("should immediately navigate to /test-page/new when router navigates to /test-page", async () => {
        expect(spectator.get(Location).path()).toBe("/status/new");
    });

    // Not working
    it("on /test-page/new", async () => {
        const clientParamsAddFilterSpy = spyOn(spectator.fixture.componentInstance.dataSource.restParams, "addFilter").and.callThrough();

        spectator.setRouteParam("status", "new"); // This line fails..

        expect(clientParamsAddFilterSpy).toHaveBeenCalledWith("Status", "NEW");
    });
});

```

## Expected behavior

I'm trying to change the route param's in the `it` function. and also with `routes` in the SpectatorComponent. 

## What is the motivation / use case for changing the behavior?

I did not find in the docs of Spectator how to achieve it.

## Environment

<pre><code>
Angular version: 8.1.12

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.2.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
@dirkluijk

**Comment by NetanelBasal** [comment]
Please provide a reproduce [here](https://ng-run.com/edit/VIYdwKFVnEgIc2m6tQYz?test=true).
