### ISSUE TITLE
Custom Matchers enhancement

### ISSUE THREAD

**Issue by kekel87** [ngneat/spectator#217]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
```typescript
expect('.zippy').toHaveClass('class a, class b');
expect('some option').toHaveText('Content 1, Content 2, Content 3');
expect('some input').toHaveValue('value 1, value 2, value 3');
```
```typescript
expect('.zippy').toHaveAttribute('id', 'zippy');
expect('.zippy').toHaveAttribute('name', 'zippy');
```
```typescript
expect('img').toHaveProperty('src', 'http://localhost:9876/assset/toto.png');
expect('img').toHaveProperty('alt', 'An image');
```

## Expected behavior
- [ ] Add `array` support for selectors matchers with multiple results
```typescript
expect('.zippy').toHaveClass(['class a', 'class b']);
expect('some option').toHaveText(['Content 1', 'Content 2', 'Content 3']);
expect('some input').toHaveValue(['value 1', 'value 2', 'value 3']);
```
- [ ] Add `contains` variant for Text and Value matchers
```typescript
expect('option').toContainsText('Content 1');
expect('some option').toContainsText(['Content 1', 'Content 2', 'Content 3']);
expect('input').toContainsValue('value 1');
expect('some input').toContainsValue(['value 1', 'value 2', 'value 3']);
```
- [ ] Add `object` support for Attribute and Property
```typescript
expect('.zippy').toHaveAttribute({
  'id':  'zippy',
  'name':  'zippy',
});
expect('checkbox').toHaveProperty({
  'src': 'http://localhost:9876/assset/toto.png',
  'alt':  'An image',
});
```
- [ ] Add `contains` support for Attribute and Property (to avoid to write `http://localhost:9876` for `src` as example)
```typescript
expect('checkbox').toContainsProperty({
  'src': '/assset/toto.png',
  'alt':  'An image',
});
```

## What is the motivation / use case for changing the behavior?
Hello,
Our team is trying to do without its internal utils.
We are considering using your great tools.

After some trying, we just miss some matchers that seems very useful to us.

Thank you.

**Comment by NetanelBasal** [comment]
Can you explain what are the use cases, please?

**Comment by kekel87** [comment]
Yes of course, sorry.

- [ ] Add `array` support for selectors matchers with multiple results
> ```html
> <div class="zippy classe-a classe-b"></div>
> ```
> ```typescript
> expect('.zippy').toHaveClass(['class-a', 'class-b']);
> ```
> Here array is just a more elegant way to compare list of classes (order doesn't mater).
> 
> ```html
> <mat-select>
>   <mat-option>Content 1</mat-option>
>   <mat-option>Content 2</mat-option>
>   <mat-option>Content 3</mat-option>
> </mat-select>
> 
> <form>
>   <input type="text" value="Value 1"/>
>   <input type="text" value="Value 2"/>
>   <input type="text" value="Value 3"/>
> </form>
> ```
> ```typescript
> expect('mat-option').toHaveText(['Content 1', 'Content 2', 'Content 3']);
> expect('input').toHaveValue(['value 1', 'Value 2', 'Value 3']);
> ```
> Here an array is use to compare a list of text/value of selector.

- [ ] Add `contain` variant for Text and Value matchers
> ```html
> <mat-select>
>   <mat-option>Content 1 </mat-option>
>   <mat-option>  Content 2  </mat-option>
>   <mat-option>  Content 3 with other text</mat-option>
> </mat-select>
> 
> <form>
>   <input type="text" value="Value 1"/>
>   <input type="text" value="  Value 2"/>
>   <input type="text" value="Value 3  with other text"/>
> </form>
> ```
> ```typescript
> expect('mat-option').toContainText('Content 1'); // match first only
> expect('mat-option').toContainText(['Content 1', 'Content 2', 'Content 3']);
> expect('input').toContainValue('Value 1'); // match first only
> expect('input').toContainValue(['Value 1', 'Value 2', 'Value 3']);
> ```
> Contain is a variant, like `toContain` of jasmine. He only compare inner text.

- [ ] Add `object` support for Attribute and Property
> ```html
> <input type="text" class="zippy" id="zippy" name="zippy" />
> <input type="checkbox" class="checkbox" id="zippy" name="zippy" />
> ```
> ```typescript
> expect('.zippy').toHaveAttribute({
>   'id':  'zippy',
>   'name':  'zippy',
> });
> expect('.checkbox').toHaveProperty({
>   src: 'http://localhost:9876/assset/toto.png',
>   alt:  'An image',
> });
> ```
> Here is an alias of `element.nativeElement.attributes` `element.nativeElement.properties`, but it only compares the data provided (maybe loop on key and use `nativeElement.getAttribute()`)

- [ ] Add `contain` support for Attribute and Property (to avoid to write `http://localhost:9876` for `src` as example)
> ```html
> <img src="asset/toto.png" />
> ```
> ```typescript
> expect('checkbox').toContainsProperty({
>   src: '/assset/toto.png',
> });
> ```
> When I tested this library, I encountered a problem here, the test failed because src = `http://localhost:9876/assset/toto.png` (karma config), but that does not interest us test this url base.

I hope it's better explained. Thank you.

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by kekel87** [comment]
Okay, I'll try this week, if I have some time.

**Comment by Coly010** [comment]
I have tackled this in PR #235

**Comment by thw0rted** [comment]
I don't understand the difference between `toHaveText` and `toContainText`, and the docs don't say anything about them.

It would be helpful to provide examples of how each one works, especially cases where would one would true but the other would be false, for the same Element.
