### ISSUE TITLE
testing all paths

### ISSUE THREAD

**Issue by DuncanFaulkner** [ngneat/spectator#218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ X ] Support request
[ ] Other... Please describe:
</code></pre>

I currently have a number of services that handle the CRUD stuff and I want to write unit tests for these methods. 

Example:
```
public create(user: IUser): Observable<IUser> {
    return this.httpClient.post<IResponse>(`${usersUrl}`, user).pipe(map((data: IResponse) => 
    data.data),tap(() =>
    this.audit('UserService',`Creating user: ${user.first_name} ${user.last_name}`, 'Created', 
       Levels.Information)),
     catchError(this.handleError<IUser>('createUser'))
    );
}
```
```
in my unit test I have:
it('should create a user', () => {
    spectator.service.create(user).subscribe();
    spectator.expectOne(`${URL}`, HttpMethod.POST);
});
```

This all seems to work and gives me some code coverage, I'm not getting code coverage on line starting with `this.audit...`. I've tried mocking a call to the audit service, but that doesn't pass and I guess it wouldn't as we are not calling the actual create service.

I feel that this may not be testable and I'm OK with that, I just want to check I'm not missing something.
I can test the audit service separately.

## Environment

<pre><code>
Angular version: 8.2.9

Browser:
- [ 77 ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15  
- Platform:  Linux

Others:

**Comment by NetanelBasal** [comment]
Format the code, please.

**Comment by DuncanFaulkner** [comment]
Formatted, sorry meant to do that before posting

**Comment by NetanelBasal** [comment]
You are right. You are mocking the audit service, and therefore the original code doesn't run.

**Comment by DuncanFaulkner** [comment]
Ok thanks, I think I need to remove the call to the `this.audit...` as I'm not sure whether this is good design and try and find another way to write audit logs.
