### ISSUE TITLE
I can't use the syntax: {provide: token, useValue: ...} in mock array

### ISSUE THREAD

**Issue by mailok** [ngneat/spectator#221]
@NetanelBasal hello, what you suggest gives me error

![error](https://user-images.githubusercontent.com/3769277/67877755-8fac6800-fb10-11e9-9c73-e392e0791940.png)

_Originally posted by @mailok in https://github.com/ngneat/spectator/issues/219#issuecomment-547973386_

**Comment by NetanelBasal** [comment]
You need to add it in `providers` not in `mocks`.
