### ISSUE TITLE
spectator.get(Service).observable = of('something') not being passed correctly

### ISSUE THREAD

**Issue by r3plica** [ngneat/spectator#222]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
In my test, if I have a service that looks like this:

***
    import { Injectable } from '@angular/core';
    import { BehaviorSubject, Observable } from 'rxjs';

    import { Category } from '@models';

    @Injectable({
        providedIn: 'root',
    })
    export class SelectorService {
        private currentCategoriesSubject: BehaviorSubject<Category[]>;
        private currentCategorySubject: BehaviorSubject<string>;

        public categories: Observable<Category[]>;
        public category: Observable<string>;

        constructor() {
            this.currentCategoriesSubject = new BehaviorSubject<Category[]>(null);
            this.categories = this.currentCategoriesSubject.asObservable();

            this.currentCategorySubject = new BehaviorSubject<string>(null);
            this.category = this.currentCategorySubject.asObservable();
        }

        public setCategories(categories: Category[]): void {
            if (!categories.length) return;
            this.setCategory(categories[0].id);
            this.currentCategoriesSubject.next(categories);
        }

        public setCategory(categoryId: string): void {
            this.currentCategorySubject.next(categoryId);
        }

        public get currentCategory(): string {
            return this.currentCategorySubject.value;
        }

        public add(category: Category) {
            let categories = this.currentCategoriesSubject.value;
            if (!categories) categories = [];

            categories.push(category);

            this.currentCategoriesSubject.next(categories);
            this.currentCategorySubject.next(category.id);
        }

        public remove(categoryId: string) {
            let categories = this.currentCategoriesSubject.value;
            for (var i = 0; i < categories.length; i++) {
                if (categories[i].id === categoryId) {
                    categories.splice(i, 1);
                }
            }

            this.currentCategoriesSubject.next(categories);

            if (!categories.length) return;

            this.currentCategorySubject.next(categories[0].id);
        }
    }

***
when inejcted into a component, the **ngOnInit** method is not subscribing to the set value if using **spectator.get** method. For example:

***
    ngOnInit() {
        console.log(this.selectorService);

        this.selectorService.category.subscribe(category => {
            console.log('category', category);
        });
    }
***

if I set up the test like this:

***
    describe('SpecificationsSaveComponent', () => {
        const SelectorServiceMock = {
            category: of('cameras'),
        };

        let spectator: Spectator<SpecificationsSaveComponent>;
        const createComponent = createComponentFactory({
            component: SpecificationsSaveComponent,
            imports: [ReactiveFormsModule, HttpClientTestingModule, SharedModule, ToastrModule.forRoot()],
            providers: [
                mockProvider(SelectorService, SelectorServiceMock),
            ],
        });

        beforeEach(() => {
            spectator = createComponent();
        });

        it('should create', () => {
            expect(spectator.component).toBeTruthy();
        });
    });

***

then the console.log(category) will return "cameras" correctly.
But, if I do it like this:

***
    describe('SpecificationsSaveComponent', () => {
        let spectator: Spectator<SpecificationsSaveComponent>;
        const createComponent = createComponentFactory({
            component: SpecificationsSaveComponent,
            imports: [ReactiveFormsModule, HttpClientTestingModule, SharedModule, ToastrModule.forRoot()],
        });

        beforeEach(() => {
            spectator = createComponent();
            spectator.get(SelectorService).category = of('cameras');
        });

        it('should create', () => {
            expect(spectator.component).toBeTruthy();
        });
    });
***

the console.log(category) will return null even though console.log(this.selectorService) shows the correct value for category.

## Environment

<pre><code>
Angular version: 8.2.0

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.13.0 
- Platform:  Windows

</code></pre>

**Comment by benelliott** [comment]
In the second, non-working version, you have already created your component before you override the observable. So the component has already seen and subscribed to the original, unmocked observable. It ignores the reassignment in the next line.

**Comment by r3plica** [comment]
I was unable to find this in the documentation. 

https://github.com/ngneat/spectator

The line that states `const service = spectator.get(QueryService);` talks about the the **createComponent** method but when I tried to implement that, I get an error stating that "get" is not part of Component

**Comment by benelliott** [comment]
It's just a general programming thing rather than a Spectator thing :) Your component has already referenced the `category` observable, so updating it after the fact won't do much good.

You can work around this by setting `detectChanges: false` in the options you pass to `createComponentFactory`, then manually calling `spectator.detectChanges()` after you reassign the observable.

**Comment by Martinspire** [comment]
Using detectChanges also increases the amount of stuff you need to do for the rest of your tests. It would be helpful if ngoninit could be called manually in order to test the startup of the app but also allow you to set it up properly without hassling with when items were declared
