### ISSUE TITLE
How would you test module forRoot and routing config using Spectator?

### ISSUE THREAD

**Issue by remkoboschker** [ngneat/spectator#223]
I am not sure how far I should go in testing modules, but it makes sense to test forRoot / forChild functions and router config. Is this something you do or intend to support?

**Comment by NetanelBasal** [comment]
What do you need to test?

**Comment by remkoboschker** [comment]
I would like to test that the right component is loaded for a particular config. I solved this by using the routingspectator on the app component and then passing the app.module router config to the RouterTestingModule with useStubs to false. Then I check if the right component is rendered below the outlet. I suppose I could do the same for guards. 

I would also like to test if forRoot / forChild calls provide the right tokens.

The nrwl nx workspace schematic generates a test for each module added the checks if all dependenicies can be loaded without errors. I am not sure how useful that is.

**Comment by NetanelBasal** [comment]
I would not bother

**Comment by remkoboschker** [comment]
Alright, thank you. I was wondering what bugs I would catch with this.
