### ISSUE TITLE
Importing spectator after install error

### ISSUE THREAD

**Issue by OgnenEndava** [ngneat/spectator#224]
I just installed spectator ^4.5.2 in my angular project.

After this simple import:
import { Spectator } from '@ngneat/spectator';

I get the following error on ng test:
ERROR in node_modules/@ngneat/spectator/lib/spectator-directive/create-factory.d.ts(9,190): error TS2304: Cannot find name 'unknown'.
node_modules/@ngneat/spectator/lib/spectator-host/create-factory.d.ts(9,175): error TS2304: Cannot find name 'unknown'.
node_modules/@ngneat/spectator/lib/spectator-http/options.d.ts(13,68): error TS2304: Cannot find name 'unknown'.
node_modules/@types/testing-library__dom/query-helpers.d.ts(28,85): error TS2370: A rest parameter must be of an array type.
node_modules/@types/testing-library__dom/query-helpers.d.ts(44,48): error TS2370: A rest parameter must be of an array type.
node_modules/@types/testing-library__dom/query-helpers.d.ts(45,47): error TS2370: A rest parameter must be of an array type.

Can you give me some support regarding this issue ??
Thank you !

**Comment by benelliott** [comment]
What version of TypeScript are you using? It looks like you may need to update.

**Comment by OgnenEndava** [comment]
typescript version 2.9.2

**Comment by OgnenEndava** [comment]
Is it mandatory to use version 3 or higher ?
adding "skipLibCheck": true in tsconfig removes the errors

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/spectator/blob/master/projects/spectator/package.json#L35

```json
peerDependencies: {
 "typescript": ">= 2.8.0"
}
```

**Comment by benelliott** [comment]
@NetanelBasal I think that dependency might need bumping if the type declarations have been generated with v3.0+ as they will not be backwards-compatible with v2.x. The only workaround is to disable type checking for library imports but this isn't ideal.

**Comment by OgnenEndava** [comment]
Any other suggestion apart from skipLibCheck? It is not possible for me to upgrade the typescript version because of other dependencies.

**Comment by benelliott** [comment]
Unfortunately not, the error is due to the introduction of new syntax introduced in TypeScript 3 such as the `unknown` keyword. 

I would have thought that being stuck on TypeScript 2.x would quickly become a problem for an Angular project. Does it not limit you to a particular Angular version? What are the other dependencies that are forcing you not to update?

**Comment by OgnenEndava** [comment]
It is not a personal project so the typescript upgrade is not something we can do in order to use a testing library, kind of sucks because I was looking forward to try it out. 
If I could use skipLibCheck for just this library that would be possible work around.
Like this it is problematic for this project.
Thank you for the support, if you can think of some other suggestion please keep in touch!

**Comment by benelliott** [comment]
You could try using Spectator 2.0.2, which was the last version to be built with TypeScript 2.x. The documentation will be a bit out of sync though.

**Comment by rudym87** [comment]
I think that the peer dependency version of TypeScript should be raised to 3.0 since `@ngneat/spectator` is unusable with TypeScript 2.8.x and 2.9.x.

`@netbasal/spectator` 3.1.2 works fine with TypeScript 2.9.2.
