### ISSUE TITLE
Add support for testing select controls when ngValue is used

### ISSUE THREAD

**Issue by cjcoops** [ngneat/spectator#225]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Arguments for `selectOption` and `toHaveSelectedOptions` must be of type `string | string[]`. Therefore it is difficult to test select controls which use `ngValue` binding on the option, where the value might be a number or an object.

## Expected behavior
Be able to write tests for select controls which use ngValue as follows:
<pre><code>
    spectator.selectOption(select, 2);
    expect(select).toHaveSelectedOptions(2);
</code></pre>
<pre><code>
    spectator.selectOption(select, {id: 1, name: 'Option 1'});
    expect(select).toHaveSelectedOptions({id: 1, name: 'Option 1'});
</code></pre>

## Minimal reproduction of the problem with instructions
See this [Gist](https://gist.github.com/cjcoops/192e5c8fcc2b9b16a66ae4b144e82dcc)
The second test fails to run with the error `Argument of type '2' is not assignable to parameter of type 'string | string[]'`

## What is the motivation / use case for changing the behavior?
Ability to test select controls which use ngValue

## Environment

<pre><code>
Angular version: 8.2.13
Spectator version 4.5.0
</code></pre>

**Comment by NetanelBasal** [comment]
CC @Coly010

**Comment by cjcoops** [comment]
@NetanelBasal I can take a look at this. Do you think the use should be as in my examples above or something like
<pre><code>
spectator.selectOption(select, 2, {ngValue: true});
expect(select).toHaveSelectedOptions(2, {ngValue: true});
</pre></code>

**Comment by NetanelBasal** [comment]
As your example.

**Comment by cjcoops** [comment]
Struggling to run the tests with my changes. Could you point me in the right direction? I did the following:

- Wrote a new test in `test/form-select/form-select.component.spec.ts`
<pre><code>
  it('should set the correct option on standard select with ngValue binding', () => {
    const select = spectator.query('#test-single-ngvalue-select') as HTMLSelectElement;
    spectator.selectOption(select, 1);
    expect(select).toHaveSelectedOptions(1);
  });
</code></pre>
- Made changes in `src/lib/select-option.ts`
<pre><code>
export function selectOption(
  options: string | string[] | number,
  element: HTMLElement | HTMLSelectElement | Document | Window,
  config: { emitEvents: boolean }
): void {
  if (!(element instanceof HTMLSelectElement)) {
    return;
  }

  element.focus();

  if (isString(options)) {
    const option: HTMLOptionElement | null = element.querySelector(`option[value="${options}"]`);
    if (!option) {
      return;
    }

    setOptionSelected(option, element, config);
  } else if (isNumber(options)) {
    const option: HTMLOptionElement | null = element.querySelector(`option[ng-reflect-ng-value="${options}"]`);
    if (!option) {
      return;
    }
    
    setOptionSelected(option, element, config);
  } else {
    if (!element.multiple) {
      return;
    }

    element.querySelectorAll('option').forEach(opt => {
      if (options.includes(opt.value)) {
        setOptionSelected(opt, element, config);
      }
    });
  }
}
</code></pre>

- Ran `npm run build`
- Ran `npm test`

When I look at the built project in `dist` I can see that my changes are in there but the tests seem to be using the old project (before my changes) so are failing.

<pre><code>ERROR in test/form-select/form-select.component.spec.ts:66:36 - error TS2345: Argument of type '1' is not assignable to parameter of type 'string | string[]'.

66     spectator.selectOption(select, 1);
</code></pre>

Sorry, my first time working on an Angular library so probably missing something really simple!

**Comment by NetanelBasal** [comment]
Run `npm run build` first.

**Comment by Coly010** [comment]
Sorry, I know I'm weighing in a little late.

@cjcoops one thing to note about your current solution. `[ngValue]` allows for objects as well as numbers for the `option` value, therefore you may need to accommodate for that. 
To do a comparison of objects, it's easiest to compare the output of running `JSON.stringify()` on both objects.

@NetanelBasal just an fyi for when reviewing the PR. 

Reference:
https://angular.io/api/forms/NgSelectOption

**Comment by NetanelBasal** [comment]
@cjcoops there is no need to run `npm run build`. Modify the source code and run `npm run test`.

**Comment by cjcoops** [comment]
@NetanelBasal @Coly010 Thanks for your help, up and running with this and I have it working for numbers. I have a problem though when `[ngValue]` is used with objects because I am unable to select a particular `option` element. 
For example suppose I had the data:
<pre><code>
const dataFormats = [
    {id: 1, format: 'dd/mm/yyyy'}
    {id: 2, format: 'mm/dd/yyyy'}
    {id: 3, format: 'yyyy/mm/dd'}
]
</code></pre>
and then I do `spectator.selectOption(select, {id: 2, format: 'mm/dd/yyyy'})`, without knowing that the `format` property is the one used between the `option` tags, there is no way of knowing which one to select with `querySelector` as far as I can see.

![image](https://user-images.githubusercontent.com/20629635/68820330-ca012380-063f-11ea-8082-89c7b228693b.png)

Unless you can think of a way would it work to have something like `spectator.selectOption(select, byText('mm/dd/yyyy')`?

**Comment by NetanelBasal** [comment]
Yes, `byText` looks good to me.
