### ISSUE TITLE
Unable to run test using Jest imports

### ISSUE THREAD

**Issue by dgsmith2** [ngneat/spectator#226]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

I'm attempting to open a PR to add a `--jest` flag to have files generated with the import path for Jest (https://github.com/dgsmith2/spectator/commit/674c5ef720c74e86d59a887eb58c24a31db6e0a9).

I'm having a problem when trying to test it with an existing app.  In the app I have the following test which was generated using the new flag I hope to introduce:

```
import { Spectator, createComponentFactory } from '@ngneat/spectator/jest';

import { FooComponent } from './foo.component';

describe('FooComponent', () => {
  let spectator: Spectator<FooComponent>;

  const createComponent = createComponentFactory(FooComponent);

  it('should create', () => {
    spectator = createComponent();

    expect(spectator.component).toBeTruthy();
  });
});
```

When I build and link my version I get: `TS2339 Property 'component' does not exist on type Spectator<FooComponent>`

If I unlink and run it with the current version of spectator I get this error:  `ReferenceError: jasmine is not defined`

I'm sure I'm missing something, I just can't determine what it is.

**Comment by NetanelBasal** [comment]
I think it's something with your local environment. You can submit a PR.

**Comment by Coffee-Tea** [comment]
@dgsmith2 Have you figure out what was the reason and how to avoid that?

**Comment by szymonlisiecki** [comment]
@dgsmith2  any updates on it?
