### ISSUE TITLE
Incorrect type definition for queryHostAll

### ISSUE THREAD

**Issue by undsoft** [ngneat/spectator#230]
This type definition here:
https://github.com/ngneat/spectator/blob/940ec6e4de5644bcf9267bc5283ce21a78ca9ed3/projects/spectator/src/lib/spectator-host/spectator-host.ts#L44
produces double array (Element[][]) as a result.

It should be:
```ts
public queryHostAll<R extends Element>(selector: string | DOMSelector, options?: { root: boolean }): R[];
```
or

```ts
public queryHostAll<R extends Element[]>(selector: string | DOMSelector, options?: { root: boolean }): R;
```

**Comment by NetanelBasal** [comment]
Do you want to open a PR?
