### ISSUE TITLE
SpectatorHttp.expectOne fails if there are concurrent HTTP requests

### ISSUE THREAD

**Issue by Sturgelose** [ngneat/spectator#231]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Trying to test multiple HTTP requests with `SpectatorHttp` and `expectOne` fails with 
`Error: Expected no open requests, found 1: GET request2`.
This seems to be some extra validation done in the `expectOne` function, when it shouldn't validate if there are other requests available to be flushed.

Seems to be specifically this line: https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator-http/spectator-http.ts#L47

## Expected behavior

I would expect a similar behaviour as Angular HttpMock, and allow to verify multiple Http requests done simultaneously. Either this can be given through a flag in the `expectOne` function or to just remove it and make the developer set it in the test itself.

Also, I haven't tested, but seems that this would also happen for any closed httpRequest unless you use `ignoreCancelled` parameter in `verify()`

## Minimal reproduction of the problem with instructions
Will try to provide a stackblitz, when I have time.

```typescript
// api-connector.service.ts
  public addRequests(requests: APIRequest[]) {

    // Setup a pipe for each request
    requests.forEach(request => {
      // Create dictionary entry to store the subject and the metadata
      this._requestSubject$[request] = { id: request, observable$: new Subject()}

      this._http
        .get(request)
        .subscribe(this._requestSubject$[request].result);
    });

  }

  public getResult(queryId: string): Observable<TimeSeries | DataPoint> {
    return this._requestSubject$[queryId].observable$;
  }
```

```typescript
// api-connector.spec.ts
it('should be created', () => {
    const request1 = 'request1';
    const request2 = 'request2';
    spectator.service.addRequests([request1, request2]);
    spectator.service.getResult(request1).subscribe((a) => console.log(a));
    spectator.service.getResult(request2).subscribe((a) => console.log(a));
    spectator.expectOne('request1', HttpMethod.GET).flush({hello: 'world'}); // FAILS
    spectator.expectOne('request2', HttpMethod.GET).flush({foo: 'bar'});

  });
```

## What is the motivation / use case for changing the behavior?

As a develoepr, I'd like to validate that multiple requests have been done concurrently against some specific urls and also would like to return some specific data to each URL.

## Environment

<pre><code>
Angular version: 8.2.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  10.16.3
- Platform:  Mac

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I prefer a flag so that we won't make a breaking change. Do you want to create a PR?

**Comment by Sturgelose** [comment]
@NetanelBasal Hey, sorry, I've been busy this week and couldn't answer before! 
I was willing to do the PR, but I haven't had time, even to answer.

Anyways, I'll see if I can help at least with another PR when I have some time, at least as a payback for implementing this issue so fast :)

Thanks, again!
