### ISSUE TITLE
Cannot Compile Angular if Spectator Installed using only Jest Types

### ISSUE THREAD

**Issue by CMadden8** [ngneat/spectator#234]
I've installed Spectator for an angular app that uses Jest for unit tests. Creating unit tests with Spectator works without any problems - but as soon as I try to compile the app, I get the below list of errors:

----------------------------------------------------------------------------------------------------------
`ERROR in ../node_modules/@ngneat/spectator/jest/lib/matchers-types.d.ts:2:13 - error TS2428: All declarations of
'Matchers' must have identical type parameters.

2   interface Matchers<R> {
              ~~~~~~~~
../node_modules/@ngneat/spectator/lib/mock.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jasmine'.

1 /// <reference types="jasmine" />
                        ~~~~~~~
../node_modules/@types/jest/index.d.ts:729:15 - error TS2428: All declarations of 'Matchers' must have identical
type parameters.

729     interface Matchers<R, T> {`

--------------------------------------------------------------------------------------------------------------

Below is a list of anything related to Jest in the package.json file:

"@types/jest": "^24.0.18",
"jest": "^24.9.0",
"jest-environment-jsdom-fifteen": "^1.0.0",
"jest-preset-angular": "^8.0.0",
"ts-jest": "^24.1.0",

All references to Jasmine and any of its packages have been removed across the entire Angular app. But does Spectator still depend on Jasmine even if it's not used by the app?

All imports of Spectator are using:

from '@ngneat/spectator/jest'

**Comment by CMadden8** [comment]
Just an update on this - I've added "@types/jasmine": "^3.5.0" to package.json, which appears to solve the problem. I've checked ../node_modules/@ngneat/spectator/lib/mock.d.ts and there's no longer a complaint in the editor regarding jasmine. Compiling no longer generates the above errors either, but a new set which I believe are probably related to the project not Spectator.

I'll update if there are any more problems after fixing the new errors. But there should be probably something in Spectator docs specifying jasmine types as a required dependency.

**Comment by NetanelBasal** [comment]
duplicate of #213

**Comment by NetanelBasal** [comment]
Try https://github.com/ngneat/spectator/issues/213#issuecomment-554508333

**Comment by CMadden8** [comment]
@NetanelBasal - cheers, the suggested fix in [https://github.com/ngneat/spectator/issues/213](url) does work. 

I've had to uninstall jasmine types, as they conflict with jest types.

I still think there should be something in the docs about this - it's an easy one to miss.
