### ISSUE TITLE
createDirectiveFactory should have directiveProviders config property

### ISSUE THREAD

**Issue by tamasfoldi** [ngneat/spectator#236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is a possibility to override componentProviders, but there is no option to override directive providers.

## Expected behavior
There should be a property to override directive providers.

## Environment
<pre><code>
Angular version: 9.0.0-rc.3
</code></pre>

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by tamasfoldi** [comment]
Yes I'm going to create one.
