### ISSUE TITLE
Mocking Service witch references to Service 

### ISSUE THREAD

**Issue by lgLindstrom** [ngneat/spectator#239]
I have an angular component that is using a service(service1) that is dependent on another service (service2).

How do I test this using Spectator ?. Only answers I have recived involves writing a new Service1 class not having any references to Service2.  When Service1 are used in most of my components this means a lot of boiler code to write.

```
export class service2 {
    public someFunction() {}

    constructor() {}
}

export class service1 {
    public somOtherFunction() {}
    constructor(s: Service2) {
         this.s.someFunction();
    }
}

@Component({
    selector: 'component',
 })

 export class component {
    constructor(private service:Service1) {
        this.service.someOtherFunction();
    }
 }
```
   
My testbed is looking like this.

```
describe('component', () => { 
    let component: Spectator<component>;
    const createComponent = createComponentFactory();

    beforeEach(() => component = createComponent());

   it('should create', () => {
     expect(component).toBeTruthy();
   });
})
```;

**Comment by benelliott** [comment]
The fact that `Service1` depends on `Service2` is an implementation detail of `Service1` and arguably out of scope of the tests for `Component`.

You can fix it by mocking `Service1` in a way that doesn't depend on `Service2`. If you need to reuse this mock elsewhere you can simply declare it in some shared file of test utilities and import it where needed.

**Comment by lgLindstrom** [comment]
Okay. I assumed there where support fort this use case in Spectator. Manually writing mocks for everything seems like a tedious job.
My background is java and a number of mocking frameworks supported this.

**Comment by benelliott** [comment]
Could you provide a code example of how it would look in Java? I'm curious
