### ISSUE TITLE
Support for spectator.keyboard.pressKey w/ modifier keys

### ISSUE THREAD

**Issue by dedwardstech** [ngneat/spectator#241]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`spectator.keyboard.pressKey('s')` only supports single key presses. There is currently not a way to fake pressing a keyboard key with modifiers like `ctrl + shift + s`

## Expected behavior

I should be able to mock keyboard events like `spectator.keyboard.pressKey('ctrl.shift.s')`

## What is the motivation / use case for changing the behavior?

Providing a more robust experience when mocking keyboard events.

Others:

I have a PR ready to go for adding this feature. If this feature is deemed appropriate. I just have a question around the syntax and what it should be. `ctrl.shift.s` vs `ctrl + shift + s`.
</code></pre>

**Comment by benelliott** [comment]
Sounds good to me, I would vote for the `+` syntax but would wait to hear what @NetanelBasal thinks!

**Comment by NetanelBasal** [comment]
Let's be consistent and use Angular [syntax](https://netbasal.com/diy-keyboard-shortcuts-in-your-angular-application-4704734547a2):

```html
<div (document:keydown.meta.a.g)="doSomething()"></div>
<div (document:keydown.g.c)="doSomething()"></div>
<input (keydown.control.arrowdown)="doSomething()">
<input (keydown.shift.control.z)="doSomething()">
```

**Comment by benelliott** [comment]
I didn't know you could do that! Cool

**Comment by dedwardstech** [comment]
Okay, I'll get the PR up today.
