### ISSUE TITLE
How to test Renderer2 methods called

### ISSUE THREAD

**Issue by blackholegalaxy** [ngneat/spectator#244]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
In one of our component, we rely on Renderer2 to inject some class on body element:
```
public ngOnInit(): void {
  this.renderer.addClass(window.document.body, 'login-body');
}
```

We tried to add Renderer2 in providers:
`provider: [mockProvider(Renderer2)]`

with no success, we cannot assert against calls:

```
const renderer = spectator.get<Renderer2>(Renderer2);

expect(spectator.fixture).toMatchSnapshot();
expect(store.dispatch).toHaveBeenCalled();

--> Matcher error: received value must be a mock or spy function
       Received has value: undefined
```
## Expected behavior - Question
We should be able to spy on Renderer2 methods in any way. Maybe we just didn't find the proper way to achieve it though. Any idea on how to test that using spectator?

## Thoughts

Without spectator, I would create a mock of Renderer2 then inject it on component:
```
renderer = JestUtils.createSpyObj<Renderer2>('renderer', ['addClass', 'removeClass']);
component = fixture.componentInstance;

Object.defineProperties(component, {
  renderer: { get: () => renderer }
});
```
(JestUtils is here just a simple wrapper around jest methods to recreate a similar API than Jasmine and basically just creates proper jest.fn() where needed).

But we don't know how to re-create this behavior with spectator.

## What is the motivation / use case for changing the behavior?
Sometimes we have to test against renderer addClass / removeClass calls. Especially when targetting an element non rendered in test context (eg: body).

## Environment

<pre><code>
Angular version: 8.2.13

Browser:
- [x] Chrome (desktop) version 78
 
For Tooling issues:
- Node version: 10.16.3
- Platform:  Mac

**Comment by NetanelBasal** [comment]
You need to provide a mock value:

```ts
const createComponent = createComponentFactory({
  component: HelloComponent,
  providers: [{ provide: Renderer2, useValue: JestUtils.createSpyObj('Renderer2', ['addClass']) }]
});
```

**Comment by blackholegalaxy** [comment]
I tried that and it still displays 
```
Matcher error: received value must be a mock or spy function
       Received has value: undefined
```

it seems Renderer2 is kind of special mock

**Comment by NetanelBasal** [comment]
Works fine: https://stackblitz.com/edit/angular-testing-spectator-bew49v

**Comment by blackholegalaxy** [comment]
It's created but seems not to be "wired" on the component: 

https://stackblitz.com/edit/angular-testing-spectator-gqmgeb?file=app/hello.component.spec.ts

**Comment by NetanelBasal** [comment]
https://github.com/angular/angular/issues/15341

**Comment by blackholegalaxy** [comment]
Sorry to bother you but I don't get how to use that in the spectator context... Tried the spy method:

https://stackblitz.com/edit/angular-testing-spectator-lkx3lr?file=app/hello.component.spec.ts

I don't know where to hook the spy to ensure it's setup before component is rendered by test.

**Comment by NetanelBasal** [comment]
```ts
import { HelloComponent } from "./hello.component";
import {
  createComponentFactory,
  Spectator,
  createTestComponentFactory
} from "@ngneat/spectator";
import { Renderer2 } from "@angular/core";

describe("HelloComponent", () => {
  let spectator: Spectator<HelloComponent>;

  const createComponent = createComponentFactory({
    component: HelloComponent,
    detectChanges: false,
    providers: [Renderer2]
  });


  it("should display the title", () => {
    spectator = createComponent({
      props: { title: "World" }
    });

    const renderer2 = spectator.get(Renderer2, true);
    spyOn(renderer2, 'addClass').and.callThrough();
    spectator.detectChanges();

    expect(renderer2.addClass).toHaveBeenCalled();
    expect(spectator.query("h1")).toHaveText("Hello World");
  });
});

```

**Comment by blackholegalaxy** [comment]
Thanks you very much. Delaying detectChanges was the missing part. Thanks for your help on that :)
