### ISSUE TITLE
yarn workspaces: Could not find a declaration file for module '@testing-library/dom'

### ISSUE THREAD

**Issue by tao-cumplido** [ngneat/spectator#245]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In a monorepo setup with yarn workspaces I get the following error when trying to run `ng test`
 
```sh
ERROR in ../node_modules/@ngneat/spectator/lib/dom-selectors.d.ts:1:41 - error TS7016: Could not find a declaration file for module '@testing-library/dom'.
```

I tried to manually install `@types/testing-library__dom` as suggested by TypeScript but to no avail. It didn't work in either the angular package or the workspace root.

## Environment

<pre><code>
Angular version: 8.2.14

 
For Tooling issues:
- Node version: 12.13.1
- Platform:  Windows
- yarn: 1.21.0

**Comment by NetanelBasal** [comment]
I'm sorry, but it's not related to the library. You can ask on Stackoverflow.

**Comment by CarlosBalladares** [comment]
@tao-cumplido did you find a solution?
