### ISSUE TITLE
No provider for HttpClient error for mocked service

### ISSUE THREAD

**Issue by schmkr** [ngneat/spectator#248]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

(not sure (yet) if this is a documentation issue/request or support request. Will update accordingly when it is clear).

## Current behavior

~~Our current set up still uses `@netbasal/spectator@3.9.4`. There, we have a test like this:~~

```ts
// update: removed code example, it was incorrect
```

~~where the mocked `LoggerService` has a dependency on the HttpClient and running this test is successful.~~

~~After upgrading to `@ngneat/spectator@4.10.0` and changing the test accordingly (the migration script was very helpful, thanks a lot!) to:~~

```ts
import { SpectatorServiceFactory, createServiceFactory } from '@ngneat/spectator/jest';

import { DbService } from './db.service';
import { LoggerService } from './logger.service';

describe('DbService', () => {
  let spectator: SpectatorServiceFactory<DbService>;

  beforeEach(() => {
      spectator = createServiceFactory({
          service: DbService,
          mocks: [
              LoggerService
          ]
      });
  });

  it('should be instantiated', () => {
      const {service} = spectator();
      expect(service).toBeInstanceOf(DbService);
  });

});
```

The test ~~now~~ fails with an error:

```
  - DbService › should be instantiated

    NullInjectorError: StaticInjectorError(DynamicTestModule)[HttpClient]:
      StaticInjectorError(Platform: core)[HttpClient]:
        NullInjectorError: No provider for HttpClient!
```

## Expected behavior

Test for the `DbService` succeeds.

## Minimal reproduction of the problem with instructions

https://github.com/schmkr/spectator--upgrade-issue/blob/master/src/services/db.service.spec.ts

~~### working example with v 3.9.4~~
~~https://github.com/schmkr/spectator--upgrade-issue/blob/working-with-spectator-3.9.4/src/services/db.service.spec.ts~~

## Environment

<pre><code>
Angular version: 8.2.13

 
For Tooling issues:
- Node version: v13.3.0  
- Platform:  macOS 10.15.1 (19B88)

Others:

</code></pre>

**Comment by schmkr** [comment]
🤦‍♂  Never mind. It seems the test using the old version, never instantiated the service properly.

If I use the similar pattern from v4 in v3:

```ts
describe('DbService', () => {
	let spectator;

	beforeEach(() => {
		spectator = createService({
			service: DbService,
			mocks: [
				LoggerService
			]
		})
	});

	it('should be instantiated', () => {
		const {service} = spectator;
		expect(service).toBeInstanceOf(DbService);
	});
});
```

Tests also fail. So at least, no regression issue.

More a support/documentation issue then: How come the tests fail with missing providers, when those missing providers are actually from the mocked service?

**Comment by NetanelBasal** [comment]
Could you reproduce it, please?

**Comment by schmkr** [comment]
Yes, it is in this repo https://github.com/schmkr/spectator--upgrade-issue/blob/master/src/services/db.service.spec.ts

**Comment by NetanelBasal** [comment]
```ts
describe("DbService", () => {
  let spectator: SpectatorService<DbService>;
  const createService = createServiceFactory({
    service: DbService,
    mocks: [LoggerService]
  });

  beforeEach(() => (spectator = createService()));

  it("should be instantiated", () => {
    const service = spectator.service;
    expect(service).toBeInstanceOf(DbService);
  });
});
```

**Comment by schmkr** [comment]
Thanks @NetanelBasal , that does indeed work. I am now trying to understand the difference. How come calling the factory `createService` in a beforeEach works, but when it is called from within an `it()` block it doesn't?

Because essentially, that is the only real difference, right?
