### ISSUE TITLE
Trigger custom component event

### ISSUE THREAD

**Issue by Wykks** [ngneat/spectator#249]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

I saw this nice article about simulating events in angular tests: https://netbasal.com/simulating-events-in-angular-unit-tests-5482618cd6c6 
It's also talking about spectator at the end, but I actually don't find any info about how to trigger custom component event using spectator.

Are you supposed to do `spectator.debugElement.triggerEventHandler('customOutput', {customData})`, followed by a `detectChanges ` ?
That's seems a little bit off, since spectator provide helpers for native events. (There's `spectator.dispatchFakeEvent`, but it doesn't take custom data).

Am I missing something ?

## Environment

<pre><code>
Angular version: 8.2
Spectator version: 4.6.0
</code></pre>

**Comment by NetanelBasal** [comment]
Invoke the method: 
```ts
it('should emit the $event on click', () => {
  let output;
  spectator.output('click').subscribe(result => (output = result));

  spectator.component.onClick({ type: 'click' });
  expect(output).toEqual({ type: 'click' });
});
```

**Comment by LayZeeDK** [comment]
Are you asking about custom elements with custom events or Angular components with output properties? What are you trying to dispatch and trigger?

**Comment by Wykks** [comment]
Sorry, forgot to answer this....

I'm talking about exactly what's described in the article.

Let say we have : 
```
@Component({
  selector: 'app-stuff',
  template: `
    <app-something (doIt)="letsDoIt()"></app-something>
    <div *ngIf="done">hello world</div>
  `,
})
class StuffComponent {
  done = false;
  letsDoIt() { 
    // I want to test this (but I don't want to call it directly)
    [...]
    this.done = true;
  }
}
```

And the working test :
```
spectator.query(SomethingComponent)!.doIt.emit();
expect(spectator.component.letsDoIt).toHaveBeenCalled();
spectator.detectChanges();
expect(spectator.query(byText('hello world'))).toExist();
```
Or alternatively : 
```
spectator.debugElement.triggerEventHandler('doIt');
expect(spectator.component.letsDoIt).toHaveBeenCalled();
spectator.detectChanges();
expect(spectator.query(byText('hello world'))).toExist();
```

In both case we need to call `spectator.detectChanges();`.

It could be useful to be able to do something like this :

```
spectator.triggerEventHandler('doIt'); // With custom data support just like debugElement.triggerEventHandler
expect(spectator.component.letsDoIt).toHaveBeenCalled();
// spectator.detectChanges(); (automatically called with spectator.triggerEventHandler)
expect(spectator.query(byText('hello world'))).toExist();
```

**Comment by LayZeeDK** [comment]
I thought you meant [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent)s from a web component. That's the output property of an Angular component emitting a component-specific event.

**Comment by LayZeeDK** [comment]
Read [Mocking Components](https://github.com/ngneat/spectator#mocking-components) in the documentation.

**Comment by NetanelBasal** [comment]
@Wykks do you want to create a PR?

**Comment by Wykks** [comment]
@LayZeeDK  I'm not sure to understand about what you're talking about...

I can try do to a PR, yes :)

**Comment by Wykks** [comment]
https://github.com/ngneat/spectator/pull/253
