### ISSUE TITLE
dealing with OnPush

### ISSUE THREAD

**Issue by blackholegalaxy** [ngneat/spectator#250]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Sometimes we need to set the `OnPush` changeDetectionStrategy on some components.

But then changing inputs then doing a `spectator.detectChanges()` doesn't update the component.

In "standard" TestBed testing, we could do something like:
```
fixture = TestBed.overrideComponent(LoginComponent, {
      set: { changeDetection: ChangeDetectionStrategy.Default }
    }).createComponent(LoginComponent);
```

in order, at testing time, to switch back to default strategy.

## Question
In spectator, how can we:
 - Switch back default strategy
 - OR force detectChanges without re-creating component on each test

## What is the motivation / use case for changing the behavior?
Testing easily OnPush components

**Comment by NetanelBasal** [comment]
Add a working example, please.

**Comment by Wykks** [comment]
It works for me. I do have test with `onPush` components, and after a `setInput` they are correctly updated. Do you use `ngOnChanges` in your component ? Because in this case it won't be called. 
In this case, you should use this : https://github.com/ngneat/spectator#testing-with-host

**Comment by Asgaroth** [comment]
If you are calling `detectChanges()` before your `setInput` this is the real issue https://github.com/angular/angular/issues/12313
