### ISSUE TITLE
spectator with both functions  of SpectatorRouting and SpectatorHttp

### ISSUE THREAD

**Issue by abadakhshan** [ngneat/spectator#251]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[*] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
For testing routing features I should use `SpectatorRouting ` and for testing Http features I should use `SpectatorHttp`.

I want to test a component that after route parameter changes, call HTTP request to load some data ans display it .

How can I test this component with @ngneat/spectator ?

## Expected behavior
Can I have `Spectator' with all functions!

**Comment by NetanelBasal** [comment]
Based on your issue, you want to test the component view, and not the actual HTTP call.

In that case, you should mock the service, and make your assertions.
