### ISSUE TITLE
Could globalsInjections work with Jest?

### ISSUE THREAD

**Issue by kiyonlin** [ngneat/spectator#254]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I can't find `defineGlobalsInjections` in `@ngneat/spectator/jest`.

## Expected behavior

Could `defineGlobalsInjections` work with Jest?

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## Environment

<pre><code>
NOT RELATED
</code></pre>

**Comment by NetanelBasal** [comment]
import it from `@ngneat/spectator`

**Comment by kiyonlin** [comment]
I Tried.

`src/test.ts`
```
import { defineGlobalsInjections } from '@ngneat/spectator';
import { NzModule } from '@shared/nz.module';

defineGlobalsInjections({
    imports: [NzModule],
});
```
`tsconfig.spec.json`
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "outDir": "./out-tsc/spec",
    "types": [
      "jest",
      "node"
    ]
  },
  "files": [
    "src/test.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```
`test.component`
```
import { Component } from '@angular/core';
@Component({
    selector: 'app-test',
    template: `
        <nz-card></nz-card>`,
})
export class TestComponent {
}
```
`test.component.spec`
```
import { Spectator, createComponentFactory } from '@ngneat/spectator/jest';

import { TestComponent } from './test.component';
import { NzModule } from '@shared/nz.module';

describe('TestComponent', () => {
    let spec: Spectator<TestComponent>;
    const createComponent = createComponentFactory({
        component: TestComponent,
        // test pass if uncomment the imports line
        // imports: [NzModule],
    });
    it('should create', () => {
        spec = createComponent();
        expect(spec.component).toBeTruthy();
    });
});

```
`error` is 
```
Error: Template parse errors:
'nz-card' is not a known element:
1. If 'nz-card' is an Angular component, then verify that it is part of this module.
2. If 'nz-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        [ERROR ->]<nz-card></nz-card>"): ng:///DynamicTestModule/TestComponent.html@1:8
......

```

**Comment by NetanelBasal** [comment]
The Jest API uses the same underline API, so it should work. Could you create a simple repo that reproduces this, please?

**Comment by kiyonlin** [comment]
After adding `setupFilesAfterEnv: ['<rootDir>/src/test.ts']` to `jest.config.js` file, the `globalsInjections` works.
