### ISSUE TITLE
ReactiveForm valueChanges not triggered

### ISSUE THREAD

**Issue by zagoa** [ngneat/spectator#258]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I test a component which contain in it's ngInit 
```
  listenToSuggestions() {
    this.querySuggestions$ =
      this.searchControl.valueChanges
        .pipe(
          tap(value => console.log(value)),
          filter(value => value && value.length > 1),
          debounceTime(300),
          switchMap(searchInput => {
            return this.getSuggestion(searchInput);
          }),
          takeUntil(this.destroy$)
        );
  }
```
The querySuggestion$ observable is binded through an async pipe. My problem is I try to do an integration test which can trigger my searchControl et look if the getSuggestion method is correctly called.

```
it('should trigger suggestions', fakeAsync(async () => {
    spectator.component.ngOnInit();

    spectator.detectChanges();
    await spectator.fixture.whenStable();
    spectator.detectChanges();

    const spyGetSuggestion = spyOn(spectator.component, 'getSuggestion');

    const input = spectator.query('input') as HTMLInputElement;
    expect(input.placeholder).toEqual('Search');

    // three different approach to trigger my formControl
    input.focus();
    input.value = 'test';
    input.dispatchEvent(new Event('input'));
    spectator.tick(300);

    spectator.typeInElement('test', input);
    spectator.tick(300);
    
    spectator.component.searchControl.setValue('test');
    spectator.tick(300);


    expect(spyGetSuggestion).toHaveBeenCalled();

  }));
```

This code is never called `tap(value => console.log(value))` and my test failed on the haveBeenCalled which return 0.

## Expected behavior
That the reactiveForm react on value modified through valueChanges.

## Environment

<pre><code>
Angular version: 8.2.10
Jest: 24.9.0

For Tooling issues:
- Node version: 10.18.1
- Platform: Linux

**Comment by NetanelBasal** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. If you have any questions relating to how to use the library, we recommend asking them in Stackoverflow.

**Comment by DaSchTour** [comment]
@zagoa I feel you pain. I'm struggling on this since years. I haven't found any solution to properly test form inputs.
