### ISSUE TITLE
ChangeDetection onPush and setInput

### ISSUE THREAD

**Issue by askarby** [ngneat/spectator#260]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When testing a Component, that's "decorated" with `ChangeDetectionStrategy` set to `OnPush`, you have to manually trigger change detection (`spectator.detectComponentChanges()`) after having set input.

## Expected behavior
It would be nice if using `setInput(....)` would take the decorator meta-data into consideration, and execute the `spectator.detectComponentChanges()`-call for you.

## Minimal reproduction of the problem with instructions
Component
```
@Component({
   ...
   changeDetection: ChangeDetectionStrategy.OnPush,
})
class NameComponent {
   @Input() name: string
   ...
}
```

Test
```
...
it('should change name', () => {
   component.spectator.setInput('name', 'Bob');
   component.detectComponentChanges();
});
...
```

## What is the motivation / use case for changing the behaviour?
The behaviour can be induced....  but detecting what's wrong can be quite a puzzler... so, the motivation must be flattening the "learning curve" of Angular testing (with Spectator).

## Environment

<pre><code>
Angular version: 8.2.11

Browser:
n/a
 
For Tooling issues:
- Node version: 10.17.0
- Platform:  Mac

Others:
</code></pre>

**Comment by ArielGueta** [comment]
Where do you see this behaviour? I tried your example, and it works with `detectChanges`.

**Comment by NetanelBasal** [comment]
Please provide a working example.

**Comment by NetanelBasal** [comment]
I'm closing the issue due to inactivity. Feel free to open if you can provide a minimal reproduction.
