### ISSUE TITLE
props evaluated as empty string for @Input properties declared as attributes in component selector

### ISSUE THREAD

**Issue by wilsonparson** [ngneat/spectator#261]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In Angular one way to accomplish the behavior of a required `@Input` property is to include the property's name as an attribute in the component selector:

```typescript
// hello.component.ts

@Component({
  selector: 'hello [title]', // Template won't allow <hello></hello> without [title]
  template: `<h1>Hello, {{title}}!</h1>`
})
export class HelloComponent {
  @Input() title: string;
}
```

The `props` property in the options parameter of `createComponent` appears to set `@Input` properties as empty strings when it encounters inputs that are specified as attributes in the component selector:

```typescript
// hello.component.spec.ts

describe('HelloComponent', () => {
  let spectator: Spectator<HelloComponent>;

  const createComponent = createComponentFactory(HelloComponent);

  it('should display the title', () => {
    spectator = createComponent({
      props: { title: "World" }
    })

    expect(spectator.query('h1')).toHaveText('Hello World');
    // Expected element to have  text 'Hello World', but had 'Hello !'
  });

});
```

Interestingly, if I use a setter and log the values it receives it appears that the `props` property _does_ initially set the value of the `@Input` property correctly, but then it _resets_ it to an empty string:

```typescript
private _title: string;

@Input()
set title(value: string) {
  console.log('setting value of title as', value);
  // 'setting value of title as World'
  // 'setting value of title as '

  this._title = value;
}

get title() { return this._title; }
```

## Expected behavior

`props` option correctly assigns values to `@Input` properties even if their names are included in the component's selector.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-testing-spectator-props-bug

1. Run the app to see the failed test.
2. Try removing `[title]` from the component selector.
3. The test should now pass.

I've reproduced this locally as well on Angular 8.2.9 with a fresh Angular app.

## What is the motivation / use case for changing the behavior?

My team often adds `@Input` property names to component selectors as attributes to achieve a "required input" behavior. We are still able to test these components with Spectator but we have to use `setInput` instead of using the `props` option when creating the component. It would be nice to be able to use the `props` option.

## Environment

<pre><code>
Angular version: 8.2.9

Browser:
- [x] Chrome (desktop) version 79.0.3945.130
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.11.1
- Platform:  Mac
</code></pre>

**Comment by ArielGueta** [comment]
It seems like a bug related to Angular, and not Spectator. I can't see a reason why a selector would influence inputs.

**Comment by NetanelBasal** [comment]
I'm closing the issue due to inactivity. Feel free to open if it's still relevant.
