### ISSUE TITLE
Support for Angular 9

### ISSUE THREAD

**Issue by fr0** [ngneat/spectator#262]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
warning " > @ngneat/spectator@4.11.1" has incorrect peer dependency "@angular/common@^8.0.0".
warning " > @ngneat/spectator@4.11.1" has incorrect peer dependency "@angular/core@^8.0.0".
warning " > @ngneat/spectator@4.11.1" has incorrect peer dependency "@angular/router@^8.0.0".
```

## Expected behavior

No peer dependency warnings when used with Angular 9.

For what it's worth, I've been using spectator with the beta/rc versions of Angular 9 for a while now and haven't encountered any issues other than the warnings.

**Comment by NetanelBasal** [comment]
Sure, can you test it with the stable version and create a PR, please?

**Comment by LayZeeDK** [comment]
We should also switch to TestBed.inject instead of TestBed.get.

**Comment by codeNoobie** [comment]
@NetanelBasal Created https://github.com/ngneat/spectator/pull/267

Please review. I was getting a test failure with `should enable spying on properties` test inside the spyObject test suite. This was apparently happening as ts compilation for es6 was not allowing the getter property to be changed via spyOnProperty. I have fixed it by setting the test tsconfig target to es5. Please suggest if you know a better way.

**Comment by NetanelBasal** [comment]
@codeNoobie thanks. Can you add `spectator.inject` method that'll call `TestBed.inject`, please?

**Comment by codeNoobie** [comment]
Sure. Let me do that.

**Comment by LayZeeDK** [comment]
Yes sorry, `TesbBed.get` is deprecated, not removed yet.

**Comment by codeNoobie** [comment]
Not sure if Angular Team has officially marked it deprecated. But if it, then we should mark Spectator.get as deprecated too.

**Comment by LayZeeDK** [comment]
https://angular.io/api/core/testing/TestBed#get

**Comment by codeNoobie** [comment]
Cool. So I will add similar deprecation message in Spectator.

**Comment by codeNoobie** [comment]
@NetanelBasal Added. Please check and let me know if something else is missing.
