### ISSUE TITLE
v5 suggestions

### ISSUE THREAD

**Issue by LayZeeDK** [ngneat/spectator#268]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

v4
* As-is
## Expected behavior

v5 suggestions

* [ ] Angular 9 support
* [ ] - Deprecate `TestBed.get`
* [ ] Angular Ivy support
* [ ] - Deprecate `entryComponents`?
* [ ] Sinon test doubles support
* [ ] Chai support
* [ ] - Add Chai matchers/plugin
* [ ] - Support Chai's global `expect`?
* [ ] Pipes testing API
* [ ] Make `@angular/router` and `@angular/animations` dependencies optional

## What is the motivation / use case for changing the behavior?

Proposed features for Spectator v5.

### Angular v9
Issue: https://github.com/ngneat/spectator/issues/262
PR: https://github.com/ngneat/spectator/pull/267

### Sinon
Use Sinon test doubles rather than Jasmine/Jest spies.

### Chai
We cannot use Spectator in my current project since we replaced the global Jasmine/Jest `expect` with `chai.expect`.

### Pipes
https://www.reddit.com/r/Angular2/comments/eztwgz/testing_pipes_with_ngneat_spectator/
Related: https://github.com/ngneat/spectator/issues/203

### Optional Angular subpackage dependencies
Running tests using Spectator in an Angular 9 workspace without `@angular/router` yields this error which breaks the whole test run:
```
ERROR in The target entry-point "@ngneat/spectator" has missing dependencies:
 - @angular/router
 - @angular/router/testing
```

Same deal without `@angular/animations`:
```
ERROR in The target entry-point "@ngneat/spectator" has missing dependencies:
 - @angular/animations
 - @angular/animations/browser
```

Is this only an issue in Angular 9 + Ivy (AOT everywhere)?

**Comment by NetanelBasal** [comment]
I reponed the pipe issue if someone wants to contribute. Can you elaborate on the `expect` point?

**Comment by LayZeeDK** [comment]
Regarding Chai's global `expect` instead of Jasmine's, I can't reproduce on Angular 9 except for some types and Karma configurations that need to be set up.

I will investigate further in the Angular 8 codebase where I experienced issues.

**Comment by NetanelBasal** [comment]
I am closing this issue. If you have news regarding `expect`, open a new one. Thanks.

**Comment by LayZeeDK** [comment]
I believe all the suggestions are still valid, including adding support for Sinon test doubles and Chai matchers.

**Comment by NetanelBasal** [comment]
The pipe has its issue. You can open new feature requests separately.
