### ISSUE TITLE
fix documentation

### ISSUE THREAD

**Issue by bboydflo** [ngneat/spectator#269]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

at this link: https://netbasal.gitbooks.io/spectator/content/components/mock-component.html the import seems wrong. 

## Expected behavior

`import { MockComponent } from 'ng-mocks';`

## What is the motivation / use case for changing the behavior?

Fix documentation to be in sync to what is currently in the readme.md

## Environment

<pre><code>
spectator: version 4.1.1
</code></pre>

**Comment by bboydflo** [comment]
Since it's such a small fix I would like to do A PR myself. Can you point me to where I can fix the docs?

**Comment by NetanelBasal** [comment]
Thanks! It's old documentation. We are not maintaining it anymore.
