### ISSUE TITLE
toHaveStyle() matcher doesn't work (throws error) for most of cases

### ISSUE THREAD

**Issue by Coffee-Tea** [ngneat/spectator#270]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We have three elements with different ways of styles applying in component view.
```
  <div class="styled-element" [ngStyle]="{ display: 'flex' }"></div>
  <div class="styled-element-2" style="display: block;"></div>
  <div class="styled-element-3" [style.opacity]="1"></div>
```

Also, we have tests with **toHaveStyle()** matcher
<pre><code>
it('should have style', () => {
    const elem: Element = spectator.query('.styled-element');

    expect(elem.getAttribute('style')).toMatch(/display: flex;/);
    expect(elem).toHaveStyle({ display: 'flex' });
  });

  it('should have style 2', () => {
    const elem2: Element = spectator.query('.styled-element-2');

    expect(elem2.getAttribute('style')).toMatch(/display: block;/);
    expect(elem2).toHaveStyle({ display: 'block' });
  });

  it('should have style 3', () => {
    const elem3: Element = spectator.query('.styled-element-3');

    expect(elem3.getAttribute('style')).toMatch(/opacity: 1;/);
    expect(elem3).toHaveStyle({ opacity: 1 });
  });
</code></pre>

All **toMatch** tests are passed, but all *toHaveStyle* are NOT with the following errors:

![image](https://user-images.githubusercontent.com/13370430/74671271-7a3c7600-51b3-11ea-85f7-295c6f18c352.png)
![image](https://user-images.githubusercontent.com/13370430/74671284-80325700-51b3-11ea-81e4-c1bebad53cb8.png)
![image](https://user-images.githubusercontent.com/13370430/74671296-858fa180-51b3-11ea-9db4-bb8bd9e312ac.png)

## Expected behavior

All *toHaveStyle* calls should be working when elements have specified styles.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## Environment

<pre><code>
Angular version: 7.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   10.15.1
- Platform:   Mac 10.14.6

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Spectator uses the JQuery [css](https://api.jquery.com/css/) method. I will take a look when I have time. If you want to contribute you can take a look here:

https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/matchers.ts#L38

**Comment by Coffee-Tea** [comment]
Hi @NetanelBasal I've tried to link it for my local project to fix and raise PR but faced with issue described here:
https://github.com/ngneat/spectator/issues/226

Any insides?

**Comment by NetanelBasal** [comment]
You don't need to link it. You can add the same spec in our tests suite (something that you should do anyway)
