### ISSUE TITLE
Jest Service Schematics issue

### ISSUE THREAD

**Issue by clementlemarc-certua** [ngneat/spectator#272]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When generating a service using the provided schematics, the _jest_ options is ignored and `SpectatorService` and `createServiceFactory` are imported from `@ngneat/spectator`.

## Expected behavior
`SpectatorService` and `createServiceFactory` are imported from `@ngneat/spectator/jest`.

## Minimal reproduction of the problem with instructions
Configure project schematics in _angular.json_
```json
  "schematics": {
    "@ngneat/spectator:spectator-component": {
      "jest": true,
      "styleext": "scss"
    },
    "@ngneat/spectator:spectator-service": {
      "jest": true
    },
    "@ngneat/spectator:spectator-directive": {
      "jest": true
    }
  }
```
Generate a service
```bash
ng g spectator-service
```
The generated service will have the following import
```js
import { SpectatorService, createServiceFactory } from '@ngneat/spectator';
```

## What is the motivation / use case for changing the behavior?
Use the proper mock function and be consistent with component and directive.

For now I am using _patch-package_ to override my node_modules and it does solve the issue as _SpectatorService_ and _createServiceFactory_ do exists.

```diff
diff --git a/node_modules/@ngneat/spectator/schematics/spectator/files/service/__name@dasherize__.service.spec.ts b/node_modules/@ngneat/spectator/schematics/spectator/files/service/__name@dasherize__.service.spec.ts
index 46347c6..f855c81 100644
--- a/node_modules/@ngneat/spectator/schematics/spectator/files/service/__name@dasherize__.service.spec.ts
+++ b/node_modules/@ngneat/spectator/schematics/spectator/files/service/__name@dasherize__.service.spec.ts
@@ -1,4 +1,4 @@
-import { createServiceFactory, SpectatorService } from '@ngneat/spectator';
+import { createServiceFactory, SpectatorService } from '@ngneat/spectator<% if (jest) { %>/jest<% } %>';
 import { <%= classify(name)%>Service } from './<%= dasherize(name)%>.service';
 
 describe('<%= classify(name)%>Service', () => {

```

## Environment
<pre><code>
Angular version: 9.0.1
</code></pre>

**Comment by clementlemarc-certua** [comment]
I can create a PR if needed :)

**Comment by NetanelBasal** [comment]
Go for it :)
