### ISSUE TITLE
Support for supplying key and keyCode to a mocked keyboard event

### ISSUE THREAD

**Issue by dedwardstech** [ngneat/spectator#278]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Right now, when creating mock keyboard events, you can supply either a key or a keyCode. There is no way to supply both.

## Expected behavior

I would like to be able to supply a key and keyCode to a mock keyboard event. 

## What is the motivation / use case for changing the behavior?

KeyboardEvent.keyCode is deprecated, however there is legacy code/libraries that rely on it. So when you use KeyboardEvent.key but legacy code checks keyCode, you end up with a false negative test.

## Environment

<pre><code>
Angular version: > 8.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dedwardstech** [comment]
I have a PR ready for this if it's deemed an acceptable feature.

**Comment by NetanelBasal** [comment]
Create a PR, please.

**Comment by jlp0328** [comment]
Was this resolved? I'm still getting `event.code` as a numerical value.
