### ISSUE TITLE
toBeVisible-matcher does not work with jest

### ISSUE THREAD

**Issue by askarby** [ngneat/spectator#280]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Visible elements are reported as "not being visible" by the `toBeVisible`-matcher, when spectator is used within jest (using the `@ngneat/spectator/jest`dependency). 

## Expected behavior
Visible elements should be reported as "being visible"

## Minimal reproduction of the problem with instructions
A minimal reproduction repository can be found here: https://github.com/askarby/jest-tobevisible-bug

## What is the motivation / use case for changing the behavior?
You would expect the matcher to work, used in jest or jasmine alike.

## Environment

<pre><code>
Angular version: 9.0.3
</code></pre>

Browser:
<pre><code>
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] jsdom
</code></pre>
 
For Tooling issues:
- Node version: 10.17.0
- Platform:  Mac

## Additional Details
The problem seems to be related to the issue: https://github.com/jsdom/jsdom/issues/135 (regarding jsdom not being able to determine offsetHeight, offsetWidth, etc (which is used from within the `toBeVisible`-matcher).

**Comment by NetanelBasal** [comment]
I'm not sure what you mean. Both Jasmine and Jest are using the same `toBeVisible` matcher.

**Comment by askarby** [comment]
@NetanelBasal 

True.... but the implementation of `toBeVisible` only works (as intended) with jasmine... it fails when used with jest!

**Comment by NetanelBasal** [comment]
Feel free to investigate and create a PR.
