### ISSUE TITLE
Version 5.0.0 has BREAKING CHANGES and there no updated alternative branches

### ISSUE THREAD

**Issue by Coffee-Tea** [ngneat/spectator#283]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Version 5.0.0 has BREAKING CHANGES and requires Angular v.9 but  it's pretty recent version and I believe there are a lot of projects with less Angular version.
It's not a problem to use 4.11.1 version as the latest one before BREAKING CHANGES but **new fixes/updated included in new versions are not available** for most of projects with Angular less than 9.

## Expected behavior

Would be great to have separate branch with versioning 4.12.X, 14.13.X and so on for Angular versions before v9 and available fixes/updates (e.g. add in 5.1.0 etc.) on that branch too.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## What is the motivation / use case for changing the behaviour?

There are a lot of projects with less Angular version than v9 and they can't use the latest fixes/updates which are available only for projects with Angular v.9 b/c are merged to master branch after 5.0.0 version.

## Environment

<pre><code>
Angular version: 7.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  10.16.2
- Platform:  Mac

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Truthfully, I've thought about this a lot, and I agree. I believe that we can downgrade the peer dependency, and add protection in the new `spectator.inject()` method. Do you want to try it, and create a PR?

**Comment by Coffee-Tea** [comment]
@NetanelBasal thanks, I will take a look
