### ISSUE TITLE
ReferenceError: customElements is not defined

### ISSUE THREAD

**Issue by dev054** [ngneat/spectator#288]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm using **@angular@9.0.7**, [**`@ngneat/spectator@5.3.1`**][1] (with **Jest**), [**`Inputmask@5.0.3`**][2] in a project and everything works on application when I run `ng serve` or even `ng build`, but it fails when I try to run a test suite for a `@Pipe` that uses `Inputmask`:

**`@Pipe`**:

    import { Pipe, PipeTransform } from '@angular/core';
    
    import Inputmask from 'inputmask';

    @Pipe({
      name: 'appSomePipe',
    })
    export class SomePipe implements PipeTransform {
      transform(value: string): string {
        return Inputmask.format(value, {
          jitMasking: true,
          mask: '1111-1',
        });
      }
    }

**`@Spec`**:

    import { createPipeFactory, SpectatorPipe } from '@ngneat/spectator/jest';
    
    import { SomePipe } from './some.pipe';
    
    describe('SomePipe', () => {
      let spectator: SpectatorPipe<SomePipe>;
      const createPipe = createPipeFactory(SomePipe);
    
      it('test', () => {
        spectator = createPipe(`{{ '11111' | appSome }}`);
        expect(spectator.element).toHaveText('1111-1');
      });
    });

When I run `ng test`, it shows:

>    ReferenceError: customElements is not defined

      2 | 
    > 3 | import Inputmask from 'inputmask';
    

**PS**: This error just appears for Angular 9 and Spectator 5.x, in Angular 8 and Spectator 4.x all tests were successfully passed.

  [1]: https://github.com/ngneat/spectator
  [2]: https://github.com/RobinHerbots/Inputmask

**PS 2**: I've also posted a question on SO: https://stackoverflow.com/questions/60761140/referenceerror-customelements-is-not-defined/60763102#60763102

## Expected behavior
I'd expect to run the test suite without errors.

## Environment

<pre><code>
Angular version: 9.0.x
</code></pre>

**Comment by benelliott** [comment]
I don't think this issue is related to Spectator. Can you try running a vanilla, non-Spectator unit test? If it's still broken then your issue is with Inputmask or Angular.

**Comment by benelliott** [comment]
You probably need to change your `tsconfig.spec.json` to target a more modern browser environment as per https://stackoverflow.com/questions/41085635/typescript-2-1-custom-elements

**Comment by dev054** [comment]
@benelliott I thought it was an issue with either `Angular` or `Spectator`, because I've updated from 8 and 4 to 9 and 5 respectively, while `inputmask` is at the same version as before. Btw, the target is already set to `es2015`. I also tested change it to `es2016`, but it doesn't work either.

In any way, thanks for the fast response.

**Comment by benelliott** [comment]
Ok no worries. If I were you I would try commenting out the Spectator calls to ensure it isn't Spectator. If you are able to create a reproduction I can try to help you debug it further.

**Comment by dev054** [comment]
I tried to execute the _ng-run_ demo (https://ng-run.com/edit/VIYdwKFVnEgIc2m6tQYz?test=true), but it doesn't compile :/ It keeps saying that I need to Install some deps and so on. Do you have a working url?

**Comment by benelliott** [comment]
If you can't get that working you can just make a simple reproduction in a Github repo.
