### ISSUE TITLE
Testing Angular Material utils

### ISSUE THREAD

**Issue by wjanaszek** [ngneat/spectator#290]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I want to check, that `mat-button` element is disabled, I have to write this:
`expect(createCommentButton).toHaveAttribute('ng-reflect-disabled');`.
Even if I replace this `ng-reflect-disabled` with some global const, it's still not so readable.

## Expected behavior
I think it will be better, to have something like a set of common methods, to test material items, something like this:
`expect(spectator.isDisabled(createCommentButton)).toBeTruthy()`

## What is the motivation / use case for changing the behavior?
Approach with writing in every spec file `.toHaveAttribute('ng-reflect-disabled')` is less readable, than a custom method like `isDisabled`. It's in opposite to DRY.
</code></pre>

**Comment by benelliott** [comment]
Does it not work just to check for the `disabled` attribute?

**Comment by NetanelBasal** [comment]
https://github.com/angular/components/blob/master/src/material/button/button.spec.ts#L134

**Comment by NetanelBasal** [comment]
`expect(spectator.get(element)).toBeDisabled()`

**Comment by wjanaszek** [comment]
Thanks, I didn't see that before!
