### ISSUE TITLE
Unclear documentation providers for Spectator + Jest

### ISSUE THREAD

**Issue by Martinspire** [ngneat/spectator#291]
So I'm trying to set up my project with Jest/Spectator as it seems like a very neat way to develop tests but I'm running into issues with the dependencies for my components and services. And getting them mocked entirely isn't the main issue, changing their behavior to do different things is the main issue.

Say I have a service, that returns something, in my current tests that always seems to be undefined. And when its an observable (like returning an array with the ReplaySubject), it seems to not work. Or when I want to know how many times a call was made (or with what parameters), it doesn't seem to match.

And for child components to change depending on the data I input, or trigger onChange events, it all seems very difficult to find out how its supposed to go. Same with when you add routing to the mix, it all seems to fall flat when you want to try to make things dynamic.

The documentation from Jest and Spectator seems pretty basic and don't really cover the part where you start actually using the thing. I had to look to issues to see whats what and that makes things pretty hard to figure out.

So what are some examples to follow, some best practices to use and things to build on? I'm mainly looking on how to properly mock services so I can change the behavior of my components or services depending on how it communicates with others. The only way I found to make any test work is to completely mock the entire thing but then I'm not really testing the contents of my components well.

I know that Jest/Spectator aren't the Angular defaults, but I've disliked Karma/Jasmine for a long time and wanted to try something different.

So say I have a service like so:
```
import { Injectable } from '@angular/core';
import { ReplaySubject, Observable } from 'rxjs';

/**
 * Some Service to do stuff
 */
@Injectable({
    providedIn: 'root',
})
export class SomeService {
    private myData: string[]; // some data that gets managed here

    private _name$ = new ReplaySubject<string[]>(); // some name that gets updated by different components/services
    nameObservable: Observable<string[]>; // for example when it is set without a function (though I did see there were issues with this)

    constructor() {
        this.nameObservable = this._name$.asObservable(); // for when values get set in the constructor
    }

    // this is a function that gets called from somewhere else
    setName(name: string): void {
        this._name$.next([name]);
    }

    setMyData(): void {
        // this data can come from somewhere else in the application but I want to mock whatever this returns.
        this.myData = ['stuff'];
    }

    getSomeData(stuff: string): string {
        return stuff + 'otherStuff';
    }
}
```

How do I mock this in another test when it is a dependency and modify its output? I get either problems subscribing on results or functions not existing. Even spectator becomes undefined. But rather than just fixing my current issue, I'd like to know what a normal way of working would be.

So, in a single test:
1) How would I mock this dependency for tests that don't involve this dependency?
2) How would I change the output of this dependency to get different data into my tests?
3) How would I check whether functions were called and with what parameters? (spyOn)

**Comment by bboyle** [comment]
This is the sort of pattern I've been using. The key bit relating to this question is the use of mockProvider so you can setup those properties that need to exist when a service is created. I use the mock methods in jest where I can, but if they are being created earlier this does the trick.

In my tests if I need to simulate something, I can just use the subjects in the MOCK variable. Make sure to reset them before each test.

I don't know if this is a great approach, it feels brittle at times. Would love to see other approaches and tips!

```ts
import { SpectatorHost, createHostFactory, mockProvider } from '@ngneat/spectator/jest';
import { TestScheduler } from 'rxjs/testing';
import { BehaviorSubject, of } from 'rxjs';
import { map, tap } from 'rxjs/operators';

import { FolderViewComponent } from './folder-view.component';
import { ArtellaConfigService } from '@core/config/artella-config.service';
import { FolderContentsService } from '@core/file/folder-contents.service';
import { FileActionService } from '@core/file/file-action.service';
import { FileActionTriggerService } from '@core/file/file-action-trigger.service';
import { FileTransferService } from '@core/file/file-transfer.service';
import { UserPrefsService } from '@core/session/user-preferences.service';
import { KeyboardService } from '@core/navigator/keyboard.service';
import { FIXTURE_FOLDER, FIXTURE_FOLDERS } from './folder-view.fixture';


const MOCK = {
  liveContents: of([]),
  fileTransfers: {
    handlepaths$: new BehaviorSubject<string[]>([]),
  },
  folderContents: {
    liveContents: () => MOCK.liveContents,
    renaming$: new BehaviorSubject<string[]>([]),
    showDeleted$: new BehaviorSubject<boolean>(false),
  }
};


describe('FolderViewComponent', () => {
  let spectator: SpectatorHost<FolderViewComponent>;
  const createHost = createHostFactory({
    component: FolderViewComponent,
    mocks: [ArtellaConfigService, FileActionService, FileActionTriggerService, KeyboardService],
    providers: [
      mockProvider(FileTransferService, MOCK.fileTransfers),
      mockProvider(FolderContentsService, MOCK.folderContents),
      mockProvider(UserPrefsService, { get: () => new Promise(resolve => resolve({})) })
    ],
    shallow: true
  });

  beforeEach(() => {
    MOCK.liveContents = of([]);
  });

  it('exists', () => {
    spectator = createHost(`<art-folder-view></art-folder-view>`);
    expect(spectator.component).toBeDefined();
  });

  // other tests
});
```

also shout out for rxjs TestScheduler. It has really helped me out for testing observables.

**Comment by Martinspire** [comment]
@bboyle thanks for sharing. So how would TestScheduler work with Angular/Spectator and observables in providers? Can you share an example test?

**Comment by bboyle** [comment]
I use it like this:

```ts
import { Spectator, createComponentFactory, mockProvider } from '@ngneat/spectator/jest';
import { TestScheduler } from 'rxjs/testing';
import { Subject } from 'rxjs';
import { tap } from 'rxjs/operators';

import { FileTransferSummaryComponent } from './file-transfer-summary.component';
import { FileSizeModule } from '@lib/file-size/file-size.module';
import { FileSizePipe } from '@lib/file-size/file-size.pipe';
import { MatBottomSheetModule } from '@angular/material/bottom-sheet';
import { FileTransferService, IFileTransfer } from '@core/file/file-transfer.service';


const MOCK = {
  fileTransfers: {
    transfers$: new Subject<IFileTransfer[]>()
  }
};


const FIXTURE_TRANSFERS: { [key: string]: IFileTransfer[] } = {
  z: [],
  a: [
    { totalBytes: 1000, transferredBytes: 0, import: false, upload: false, download: false, handlePath: 'foo' }
  ],
  b: [
    { totalBytes: 1000, transferredBytes: 500, import: false, upload: false, download: false, handlePath: 'foo' }
  ],
};


describe('FileTransferSummaryComponent', () => {
  let spectator: Spectator<FileTransferSummaryComponent>;
  const createComponent = createComponentFactory({
    component: FileTransferSummaryComponent,
    imports: [FileSizeModule, MatBottomSheetModule],
    mocks: [FileSizePipe],
    providers: [
      mockProvider(FileTransferService, MOCK.fileTransfers),
    ],
    shallow: true
  });

  beforeEach(() => {
    MOCK.fileTransfers.transfers$ = new Subject<IFileTransfer[]>();
    spectator = createComponent();
  });

  it('updates when transfer observable changes', () => {
    const testScheduler: TestScheduler = new TestScheduler((actual, expected) => {
      expect(actual).toEqual(expected);
    });

    testScheduler.run(({ expectObservable, hot }) => {
      hot('a-b', FIXTURE_TRANSFERS)
        .pipe(
          tap(transfers => MOCK.fileTransfers.transfers$.next(transfers))
        )
        .subscribe();

      const expectedValues = {
        z: { totalBytes: 0, transferredBytes: 0 },
        a: { totalBytes: 1000, transferredBytes: 0 },
        b: { totalBytes: 1000, transferredBytes: 500 },
      } as const;

      expectObservable(spectator.component.summary$).toBe('a-b 1999ms z', expectedValues);
    });
  });
});
```
