### ISSUE TITLE
spectator depends on schematics-utilities which brings Angular 7 dependencies in project

### ISSUE THREAD

**Issue by L2jLiga** [ngneat/spectator#292]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

When install spectator it brings schematics-utilities which brings dependencies:
rxjs: `^6.4.0`
`@angular-devkit/core` and `@angular-devkit/schematics `: `^7.3.6`

And Angular 7 itself depending on rxjs 6.3.3

## Minimal reproduction of the problem with instructions
ng new demo-proj
cd demo-proj
npm i -D @ngneat/spectator

## Environment

<pre><code>
Angular version: 8-9

Browser: n/a
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Windows

Others:
</code></pre>

**Comment by L2jLiga** [comment]
I found that `schematics-utilities` depends on Angular v8 since `2.x`, is it possible to upgrade `schematics-utils` for 4.x and publish new version to be consist?

**Comment by L2jLiga** [comment]
Have it done in https://github.com/L2jLiga/spectator/tree/v4.11.2


[feat__update_schematics-utilities.zip](https://github.com/ngneat/spectator/files/4433264/feat__update_schematics-utilities.zip)

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR if that's not a breaking change

**Comment by L2jLiga** [comment]
There's no any breaking changes. I'll create PR in few minutes :)
