### ISSUE TITLE
Option to pretty format component HTML

### ISSUE THREAD

**Issue by JacobSiegle** [ngneat/spectator#293]
Please close if you think this is out of scope but a big pain is logging HTML in a readable format when trying to debug tests. Allow the possibility for a string parser to hook into spectator to log out pretty HTML.

Here is a manual hooked up prettier format example.

```
    const prettier = require('prettier/standalone');
    const prettierHTML = require('prettier/parser-html');
    
    describe('', () => {
        let spectator: Spectator<LoginComponent>;
        const createComponent = createComponentFactory({
            component: LoginComponent,
            imports: [SharedTestingModule.forRoot()]
        });
    
        beforeEach(() => {
            spectator = createComponent();
        });

        it('should redirect on log success', () => {
    
        });
    
        fit('should show error message on log fail', () => {
            const pretty = prettier.format(spectator.element.outerHTML, { parser: 'html', plugins [prettierHTML] });
            console.log(pretty);
        });
    });
```

Something like `spectator.prettyLog();` could be called to log out the HTML contents of the component.

**Comment by benelliott** [comment]
Could you expand a bit on why you would want to output HTML in a unit test? I'm not sure I understand the use case.

**Comment by JacobSiegle** [comment]
Debugging. For example lets say i'm using a 3rd party sidebar and testing my component which wraps it. I want to ensure my component properly configures the 3rd party sidebar which has it's own HTML I am not completely familiar with. To see how this HTML is composed some options are manually looking up the code on git, dig into the generated NPM files for the source, manually open the test runner and debug it, or load up my app. It's far easier and faster to print out the entire HTML state and just see the generated output to figure out what elements I want to query for this test but the HTML structure is not formatted. 

Sometimes you second guess what is actually going on, like "Why am I not pulling this element". Well lets see how the DOM looks and if it's what I actually expect. Sometimes people compute state in angular HTML files which you want to check how those are resolving and the easiest way to to just log those in HTML with {{model | json}}.

**Comment by NetanelBasal** [comment]
It's not within the scope of the library. You can use this library: https://github.com/kreuzerk/pretty-html-log

**Comment by JacobSiegle** [comment]
Thanks for your consideration! Really enjoy the lib thus far.
