### ISSUE TITLE
Run RouterTestingModule outside zone

### ISSUE THREAD

**Issue by CrozifletteSavoyarde** [ngneat/spectator#298]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hello guys! I'm trying to test my component with a routerLink, and I've found this super doc.
[https://github.com/ngneat/spectator#integration-testing-with-routertestingmodule](https://github.com/ngneat/spectator#integration-testing-with-routertestingmodule)
But I have an issue with this line.
`// test the current route by asserting the location
    expect(spectator.get(Location).path()).toBe('/');`
The issue:
`TS2339: Property 'path' does not exist on type 'SpyObject '.`
So instead of "path()", I try to use "pathname", not sure if this is the same thing.
So what "Location" is used?
After, using pathname, I have this error that I don't understand:
`NullInjectorError: R3InjectorError(CompilerModule)[Location -> Location]:
          NullInjectorError: No provider for Location!
        error properties: Object({ originalStack: 'Error: NullInjectorError: No provider for Location!
`
Is this example supposed to work? Did I miss something with the location?
And also, the doc uses "spectator.get()", isn't it supposed to be deprecated? 
## Expected behavior

No TS issue when using the example.
No error :(
No deprecated mark

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## What is the motivation / use case for changing the behavior?

Documentation is not enough, I'm not able to reproduce the example with my component.
Thanks!

## Environment

<pre><code>
Angular version: 9.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by CrozifletteSavoyarde** [comment]
I try to make a workaround, using Router instead of Location.
I don't know why Router is ok but not Location.

My new test 
```
it("should navigate away using router link", (done) => {
      // arrange
      const spectator = createComponentRouter();
      const router: Router = spectator.inject(Router);
      
     // assert (act is after as this is a subscribe)
      router.events.pipe(filter(e => e instanceof NavigationStart)).subscribe(e => {
        const navigation = router.getCurrentNavigation();
        expect(navigation.initialUrl.toString()).not.toEqual(NEW_PATH);
        expect(navigation.extractedUrl.toString()).toEqual(NEW_PATH);
        done();
      });

      // act
      spectator.click(spectator.query(SELECTOR));
    });
```

So now it seems to work, but I have a warning.
`WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'
`
I don't know if it's me or a spectator bug. I have it only in this test when creating the spectator with createComponentRouter()

**Comment by ArielGueta** [comment]
https://github.com/angular/angular/issues/25837

**Comment by CrozifletteSavoyarde** [comment]
Thanks, for the link

Unfortunately, it happens during the spectator factory creation, when I don't use router yet. I use something very similar to the example.
```
const createComponent = createRoutingFactory({
    component: MyComponent,
    declarations: [OtherComponent],
    stubsEnabled: false,
    routes: [
      {
        path: '',
        component: MyComponent
      },
      {
        path: 'foo',
        component: OtherComponent
      }
    ]
  });
```
And my router link is in the html
` <mat-card [routerLink]="['/new_path']"></mat-card>`

So I can't spy, can't use fixture, nor the other solutions and I don't understand how to handle that.
In fact, I don't even understand why it happens as I don't use router at this step.

**Comment by CrozifletteSavoyarde** [comment]
I switched to a classic createComponentFactory, and I don't have the warning anymore, and the test is ok.
I seriously don't understand what's happening

**Comment by NetanelBasal** [comment]
We can wrap this [line](https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator-routing/create-factory.ts#L68) inside ngZone. You're welcome to submit a PR.

**Comment by CrozifletteSavoyarde** [comment]
Hello Netanel, I'm trying to do it.
What should I do to refresh the lib in my consuming app, after the update?
I'm unsure if my patch is not working, ou just not taken in account.

**Comment by NetanelBasal** [comment]
Read about `npm link`

**Comment by PierreDuc** [comment]
The original issue here is that @CrozifletteSavoyarde uses the native browser [`Location`](https://developer.mozilla.org/en-US/docs/Web/API/Location) object, instead of specifically importing [`Location`](https://angular.io/api/common/Location) from angular:

```
import { Location } from '@angular/common';
```

Nevertheless, I reached this issue after getting the following warning my console:

```
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'
```

which appears with using the `createRoutingFactory` method
