### ISSUE TITLE
Support passing template in factory

### ISSUE THREAD

**Issue by dev054** [ngneat/spectator#299]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I noticed that [**`SpectatorDirectiveOptions`**](https://github.com/ngneat/spectator/blob/fd7ce101440ae139a76684b9bf5854d61ef2caf9/projects/spectator/src/lib/spectator-directive/options.ts#L11) supports (or at least is what the interface tell us) a "fixed" template, so I tried to use it:

```ts
describe('MyDirective', () => {
  let spectator: SpectatorDirective<MyDirective>;
  const createDirective = createDirectiveFactory({
    directive: MyDirective,
    template: '<input myDirective>',
  });

  test('should do something', () => {
    // Expected 1 arguments, but got 0.ts(2554)
    // spectator-directive.d.ts(22, 70): An argument for 'typeOrOptions' was not provided.
    spectator = createDirective();
  });
});
```

... however it gives the error I have commented out. Since it isn't allowed to have a "fixed" template as `createDirective` always expect a template, I wonder why exists this option. 

Note that the same happens with [**`SpectatorHostOptions`**](https://github.com/ngneat/spectator/blob/216f1c88adf503b053e3ad98d57004900b83a209/projects/spectator/src/lib/spectator-host/options.ts#L12) and with  [**`SpectatorPipeOptions`**](https://github.com/ngneat/spectator/blob/f4a42a7c5e60d7fb110e5d80dcff768cc2cc73e6/projects/spectator/src/lib/spectator-pipe/options.ts#L11):

```ts

describe('MyPipe', () => {
  const createPipe = createPipeFactory({
    pipe: MyPipe,
    template: '{{ input | myPipe }}',
  });

  test('should do something', () => {
    const { element } = createPipe({
      hostProps: {
        input: 'text',
      },
    });
    expect(element).toHaveExactText('text');
  });
```

... the test fails because it doesn't recognizes the template (the `input` is always empty. No matter the `input` I pass).

<hr>

 It's not clear in docs how to use, or even if it's possible to use this feature.

## Expected behavior
I'd expect to know if it's possible to use it.

## Environment

<pre><code>
Angular CLI: 9.1.3
Node: 13.7.0
OS: darwin x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.3
@angular-devkit/build-angular      0.901.3
@angular-devkit/build-ng-packagr   0.901.3
@angular-devkit/build-optimizer    0.901.3
@angular-devkit/build-webpack      0.901.3
@angular-devkit/core               9.1.3
@angular-devkit/schematics         9.1.3
@ngtools/webpack                   9.1.3
@schematics/angular                9.1.3
@schematics/update                 0.901.3
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by NetanelBasal** [comment]
It's legacy code, and I'll remove it. Thanks.

```ts
beforeEach(() => (spectator = createPipe(`{{ [1, 2, 3] | sum }}`)));
```

**Comment by dev054** [comment]
> It's legacy code, and I'll remove it. Thanks. You can do:
> 
> ```ts
> beforeEach(() => (spectator = createPipe(`{{ [1, 2, 3] | sum }}`)));
> ```

Hey @NetanelBasal thanks for the response. Oh, so it should be removed from the 3 interfaces?

<hr>

Btw, your suggestion is a little bit different to what I was trying to accomplish. I was trying to have a fixed template and manipulate the `props` in each `test`... but as now you said that it's deprecated... it seems that the only way possible is by creating a component.

<hr>

**PS**: Shouldn't this issue remain open to track this for future removal?

**Comment by NetanelBasal** [comment]
After re-examining the code, I think we can add this as a feature. Currently, we ignore the template passed in the factory. Do you want to create a PR?
