### ISSUE TITLE
Migrate the docs to docusaurus

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/spectator#301]
Migrate our long README to [docusaurus](https://v2.docusaurus.io/docs/introduction/).

You can take the code from [Akita](https://github.com/datorama/akita/tree/master/docs) or [Transloco](https://github.com/ngneat/transloco/tree/master/docs), and modify it.

**Comment by Steven-Harris** [comment]
I got you fam

**Comment by Steven-Harris** [comment]
I got this started, I will try to pick back up on it next week

**Comment by NetanelBasal** [comment]
Awesome, thanks!
