### ISSUE TITLE
How to use overrideModule ?

### ISSUE THREAD

**Issue by maxime1992** [ngneat/spectator#302]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I need to mock `MatIconModule` and can't

## Expected behavior

I'd like to be able to do the following: 

```
TestBed.configureTestingModule({
  // ...
})
.overrideModule(MatIconModule, {
  // ...
})
```

But with spectator.

## What is the motivation / use case for changing the behavior?

Have all the native capabilities of TestBed and being able to override a module.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR and add support.
