### ISSUE TITLE
Issue with mocking provider

### ISSUE THREAD

**Issue by nicmeriano** [ngneat/spectator#308]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm trying to test a page component which makes a call to a global service which returns an observable. I'm able to properly mock the call for methods that are called outside `ngOnInit`, however when I subscribe to the returned observable within the page component's lifecycle method, I get `TypeError: Cannot read property 'subscribe' of null`.

Here's a stripped down example:

MyService.ts
```
@Injectable({
    providedIn: 'root',
})
export class MyService {
    private _data$ = BehaviorSubject<initialState>;
    data$: Observable<Data>;

    constructor(private http: HttpClient) {
        this._data$ = new BehaviorSubject(initialState);
        this.data$ = this._data$.asObservable();
        this.getData();
    }

    public method(id: string): Observable<any> {
        return this.data$.pipe(
            map((data) => data.find((obj) => 
                obj.id === id)),
            take(1)
        );
    }

    private getData() {
        this.http.get<data>(url).pipe(
            tap(data => {
                this._data$.next(data);
            }
        ).subscribe()
    }

    ...
}
```

PageComponent.ts
```
export class PageComponent implements OnInit {
    success = false;

    constructor(
        private service: MyService,
        private route: ActivatedRoute,
        private router: Router,
    ) {}


    ngOnInit(): void {
        const { type, id } = this.route.snapshot.queryParams;
        
        this.service.method(id).subscribe((obj) => {
            if (!obj) {
                const queryParams = { id: null };
                return this.router.navigate([], { queryParams, queryParamsHandling: 'merge' });
            }
            this.success = true;
        });
    }

    ...
}
```

PageComponent.spec.ts
```
describe('PageComponent', () => {
    let spectator: SpectatorRouting<PageComponent>;
    let component: PageComponent;
    let mockIntegrationStore: SpyObject<MyService>;

    const createComponent = createRoutingFactory({
        component: PageComponent,
        mocks: [MyService]
    });

    beforeEach(() => {
        spectator = createComponent({
            queryParams: { type: 'test', id: '123' },
        });
    });

    it('should ...', () => {
        const component = spectator.component;
        const mockService = spectator.get<MyService>(MyService);
        mockService.method.and.returnValue(of('mock return value'));
        expect(...)
    });
}
```

This will throw the `TypeError` mentioned above, however if I call `this.service.method(id).subscribe(...)` outside the `ngOnInit` then I get the expected mocked value.

I hope my example is sufficiently clear. Any ideas?

## Expected behavior

Calling `this.service.method(id).subscribe(...)` within my `ngOnInit` method should return the mocked response as it does when called outside the lifecycle method.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## Environment

<pre><code>
Angular version: 9.1.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 13.8.0
- Platform:  Mac

</code></pre>

**Comment by NetanelBasal** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. If you have any questions relating to how to use the library, we recommend asking them either in Stackoverflow or in the dedicated Gitter channel.


From a quick look, it seems that you need to use `detectChanges: false`, and mock the method before you run `ngOnInit`.
