### ISSUE TITLE
Design the new docs site homepage

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/spectator#312]
We'd love for someone to design (and code) our new homepage.

- Clone the project, and `cd` to `docs`. Run `npm i` and `npm start` to run the docs.
- Here's a link to the [Home](https://github.com/ngneat/spectator/blob/master/docs/src/pages/index.js#L73) page file.

**Comment by donmckenna** [comment]
I'll take this.

**Comment by NetanelBasal** [comment]
@donmckenna any progress here?

**Comment by donmckenna** [comment]
My apologies. Life delays. I will get to this within the week.

**Comment by joshiraez** [comment]
I can work on this as well if you are too busy.
