### ISSUE TITLE
Provider value passed in component provider does not overwrite component factory value

### ISSUE THREAD

**Issue by Tinadim** [ngneat/spectator#315]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The providers passed to the `createComponent` don't seem to be overriding the providers passed to `createComponentFactory`. See the reproduction steps below for details.

## Expected behavior
There is a comment in the documentation that states that:
```
spectator = createComponent({
    // Override the component's providers
    providers: [],
});
```
And so I would expect the providers in the array above to overwrite the ones passed to `createComponentFactory`

## Minimal reproduction of the problem with instructions
This is my component:

```
import { Component, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
})
export class AppComponent {
    platform: string;

    constructor(@Inject(PLATFORM_ID) private platformId: object) {
        this.platform = isPlatformBrowser(this.platformId) ? 'Browser' : 'Server';
    }
}
```
and this is my test:
```
import { Spectator, createComponentFactory } from '@ngneat/spectator/jest';
import { PLATFORM_ID } from '@angular/core';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
    let spectator: Spectator<AppComponent>;
    const createComponent = createComponentFactory(AppComponent);

    it('Should indicate we are in the browser context', () => {
        spectator = createComponent({
            providers: [{ provide: PLATFORM_ID, useValue: 'browser' }],
        });
        expect(spectator.component.platform).toBe('Browser');
    });

    it('Should indicate we are in the server context', () => {
        spectator = createComponent({
            providers: [{ provide: PLATFORM_ID, useValue: 'server' }],
        });
       // this test fails. Platform is still browser.
        expect(spectator.component.platform).toBe('Server');
    });
});
```

## What is the motivation / use case for changing the behavior?
Broken tests

## Environment

<pre><code>
Angular version: 9.1.7

 
For Tooling issues:
- Node version: v12.14.0
- Platform:  Mac

Others:
- Jest: v26.0.1
</code></pre>

**Comment by NetanelBasal** [comment]
Based on [this](https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator/create-factory.ts#L103) code it should work.

**Comment by Tinadim** [comment]
I believe you, and probably I'm doing something wrong, but I can't figure out where the problem is. Can you please help pointing out what I can try?

**Comment by NetanelBasal** [comment]
Reproduce it on stackblitz.

**Comment by Tinadim** [comment]
@NetanelBasal there you go https://stackblitz.com/edit/repro-steps?file=src/app/app.component.spec.ts

**Comment by NetanelBasal** [comment]
You must add it on creation:

```ts
  const createComponent = createComponentFactory({
    component: AppComponent,
    providers: [{ provide: PLATFORM_ID, useValue: "browser" }]
  });
```

**Comment by Tinadim** [comment]
@NetanelBasal indeed it works, thanks for the help. Can this be added to the documentation? I imagine more people eventually will have the same question.

**Comment by NetanelBasal** [comment]
Feel free to submit a PR.
