### ISSUE TITLE
Make createSpyObject public

### ISSUE THREAD

**Issue by kremerd** [ngneat/spectator#316]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`createSpyObject` is _public api_ for [Jasmine](https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/mock.ts#L69), but only _internal_ for [Jest](https://github.com/ngneat/spectator/blob/master/projects/spectator/jest/src/lib/mock.ts#L6).

## Expected behavior
It should be public api for both environments.

## Minimal reproduction of the problem with instructions
Not applicable.

## What is the motivation / use case for changing the behavior?
For homogeneity it's desireable to manually mock objects in the same way that spectator mocks objects automatically. In fact that's already possible with public api by using `mockProvider(type, properties).useFactory()`. However that's rather unintuitive to write out all the time ;).

## Environment
Not relevant.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by kremerd** [comment]
Done ;).
