### ISSUE TITLE
Routing does not support ActivatedRoute's url property

### ISSUE THREAD

**Issue by sandbergja** [ngneat/spectator#323]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to test a component that checks the value of path, within the ActivatedRoute's url property (this one: https://angular.io/api/router/UrlSegment#path).  Specifically, I'm looking at the route's parent's url path.  Whenever I try to test this code, however, I run into the error:

<pre><code>
TypeError: this.route.parent.url is undefined in
http://localhost:9876/_karma_webpack_/main.js (line 4690)
    error properties: Object({ ngDebugContext: DebugContext_({ view:
Object({ def: Object({ factory: Function, nodeFlags: 33800193,
rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [
Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex:
0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 245760,
directChildFlags: 245760, childMatchedQueries: 0, matchedQueries:
Object({  }), matchedQueryIds: 0, references: Object({  }),
ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0,
outputs: [  ], element: Object({ ns: '', name: 'ng-component', attrs:
[  ], template: null, componentProvider: Object({ nodeIndex: 1,
parent: <circular reference: Object>, renderParent: <circular
reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1,
flags: 245760, childFlags: 0, directChildFlags: 0,
childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0,
references: Object, ngContentIndex: -1, childCount: 0, bindings:
Array, bindingFlags: 0, outputs:  ...
    ./src/app/staff/admin/basic-admin-page.component.ts/BasicAdminPageComponent.prototype.ngOnInit@http://localhost:9876/_karma_webpack_/main.js:4690:9
    checkAndUpdateDirectiveInline@http://localhost:9876/_karma_webpack_/vendor.js:66667:19
    checkAndUpdateNodeInline@http://localhost:9876/_karma_webpack_/vendor.js:75065:20
    checkAndUpdateNode@http://localhost:9876/_karma_webpack_/vendor.js:75027:16
    debugCheckAndUpdateNode@http://localhost:9876/_karma_webpack_/vendor.js:75661:38
    debugCheckDirectivesFn@http://localhost:9876/_karma_webpack_/vendor.js:75621:36
    View_BasicAdminPageComponent_Host_0/<@ng:///DynamicTestModule/BasicAdminPageComponent_Host.ngfactory.js:10:8
    debugUpdateDirectives@http://localhost:9876/_karma_webpack_/vendor.js:75613:21
    checkAndUpdateView@http://localhost:9876/_karma_webpack_/vendor.js:75009:14
    callWithDebugContext@http://localhost:9876/_karma_webpack_/vendor.js:75879:25
    debugCheckAndUpdateView@http://localhost:9876/_karma_webpack_/vendor.js:75581:12
    ./node_modules/@angular/core/fesm5/core.js/</ViewRef_.prototype.detectChanges@http://localhost:9876/_karma_webpack_/vendor.js:66256:22
    ./node_modules/@angular/core/fesm5/testing.js/</ComponentFixture.prototype._tick@http://localhost:9876/_karma_webpack_/vendor.js:76461:32
    ./node_modules/@angular/core/fesm5/testing.js/</ComponentFixture.prototype.detectChanges/<@http://localhost:9876/_karma_webpack_/vendor.js:76475:49
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3524:30
    ./node_modules/zone.js/dist/proxy.js/</ProxyZoneSpec</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:167009:43
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3523:36
    onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:71826:33
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3523:36
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.run@http://localhost:9876/_karma_webpack_/polyfills.js:3281:47
    ./node_modules/@angular/core/fesm5/core.js/</NgZone.prototype.run@http://localhost:9876/_karma_webpack_/vendor.js:71740:28
    ./node_modules/@angular/core/fesm5/testing.js/</ComponentFixture.prototype.detectChanges@http://localhost:9876/_karma_webpack_/vendor.js:76475:25
    ./node_modules/@ngneat/spectator/fesm5/ngneat-spectator.js/DomSpectator.prototype.detectChanges@http://localhost:9876/_karma_webpack_/vendor.js:109541:22
    createRoutingFactory/<@http://localhost:9876/_karma_webpack_/vendor.js:111307:23
    ./src/app/staff/admin/basic-admin-page.component.spec.ts/</<@http://localhost:9876/_karma_webpack_/main.js:4622:49
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3524:30
    ./node_modules/zone.js/dist/proxy.js/</ProxyZoneSpec</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:167009:43
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3523:36
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.run@http://localhost:9876/_karma_webpack_/polyfills.js:3281:47
    runInTestZone@http://localhost:9876/_karma_webpack_/vendor.js:166564:38
    wrapTestInZone/<@http://localhost:9876/_karma_webpack_/vendor.js:166579:24
    <Jasmine>
    runInTestZone/</testZoneSpec</<@http://localhost:9876/_karma_webpack_/vendor.js:165683:51
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3524:30
    ./node_modules/zone.js/dist/proxy.js/</ProxyZoneSpec</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:167009:43
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3523:36
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.run@http://localhost:9876/_karma_webpack_/polyfills.js:3281:47
    runInTestZone/</testZoneSpec<@http://localhost:9876/_karma_webpack_/vendor.js:165683:33
    ./node_modules/zone.js/dist/async-test.js/</</</AsyncTestZoneSpec</AsyncTestZoneSpec.prototype._finishCallbackIfDone/</<@http://localhost:9876/_karma_webpack_/vendor.js:165517:39
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:9876/_karma_webpack_/polyfills.js:3559:35
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.runTask@http://localhost:9876/_karma_webpack_/polyfills.js:3326:51
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneTask</ZoneTask.invokeTask@http://localhost:9876/_karma_webpack_/polyfills.js:3641:38
    ZoneTask/this.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3630:52
    timer@http://localhost:9876/_karma_webpack_/polyfills.js:6169:33
    TypeError: spectator is undefined in
http://localhost:9876/_karma_webpack_/main.js (line 4624)
    ./src/app/staff/admin/basic-admin-page.component.spec.ts/</<@http://localhost:9876/_karma_webpack_/main.js:4624:9
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3524:30
    ./node_modules/zone.js/dist/proxy.js/</ProxyZoneSpec</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:167009:43
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3523:36
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.run@http://localhost:9876/_karma_webpack_/polyfills.js:3281:47
    runInTestZone@http://localhost:9876/_karma_webpack_/vendor.js:166564:38
    wrapTestInZone/<@http://localhost:9876/_karma_webpack_/vendor.js:166579:24
    <Jasmine>
    runInTestZone/</testZoneSpec</<@http://localhost:9876/_karma_webpack_/vendor.js:165683:51
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3524:30
    ./node_modules/zone.js/dist/proxy.js/</ProxyZoneSpec</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:167009:43
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3523:36
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.run@http://localhost:9876/_karma_webpack_/polyfills.js:3281:47
    runInTestZone/</testZoneSpec<@http://localhost:9876/_karma_webpack_/vendor.js:165683:33
    ./node_modules/zone.js/dist/async-test.js/</</</AsyncTestZoneSpec</AsyncTestZoneSpec.prototype._finishCallbackIfDone/</<@http://localhost:9876/_karma_webpack_/vendor.js:165517:39
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:9876/_karma_webpack_/polyfills.js:3559:35
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</Zone</Zone.prototype.runTask@http://localhost:9876/_karma_webpack_/polyfills.js:3326:51
    ./node_modules/zone.js/dist/zone.js/</</Zone$1</ZoneTask</ZoneTask.invokeTask@http://localhost:9876/_karma_webpack_/polyfills.js:3641:38
    ZoneTask/this.invoke@http://localhost:9876/_karma_webpack_/polyfills.js:3630:52
    timer@http://localhost:9876/_karma_webpack_/polyfills.js:6169:33

</code></pre>

## Expected behavior
Desired behavior is that I could set the path with something like this:

      const createComponent = createRoutingFactory({
        component: ProductDetailsComponent,
        parent: { path: '/special-sale' } 
      });

But I'd be very happy with any solution that allows me to run my tests without getting the undefined error. :-)

## Minimal reproduction of the problem with instructions

https://github.com/sandbergja/spectator_url_issue

## What is the motivation / use case for changing the behavior?

We have a bunch of auto-generated interfaces that all use the same component, with various helpful data passed in through the route data and the parent's path.

## Environment

<pre><code>
Angular version: 9.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 76.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 83.0.478.54
 
For Tooling issues:
- Node version: 14.4
- Platform:  Linux, windows

</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
