### ISSUE TITLE
peer dependency warning when using Angular 10

### ISSUE THREAD

**Issue by crfrolik** [ngneat/spectator#325]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
warning " > @ngneat/spectator@5.11.0" has incorrect peer dependency "tslib@^1.10.0".
```

## Expected behavior

I believe Angular 10 upgrade to tslib@2, so the peer dependency should be updated appropriately.

## Environment

<pre><code>
Angular version: 10.0.2

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR. I think we can remove the peer dependency.

**Comment by crfrolik** [comment]
I looked in the code and couldn't find the peer dependency an any `package.json`.
Could it be possible that `ng-packagr` is adding this? In which case, the solution is likely to update to Angular 10 and ng-packagr 10. I don't know what implications such an upgrade has for spectator (major version bump to 6.0?) but I'll be happy to submit a PR for that if you think it is appropriate.

**Comment by NetanelBasal** [comment]
The best option would be to compile Spectator without --importHelpers flag, thus directly generating the helper functions and removing the tslib peer dependency.

**Comment by adam-beck** [comment]
It looks to me like it's coming from `@angular-devkit/build-angular`

**Comment by crfrolik** [comment]
I wanted to help with this but I am swamped with other work right now so I won't be able to. My apologies.
