### ISSUE TITLE
feat:(routing): ActivatedRouteStub support for firstChild/children

### ISSUE THREAD

**Issue by cgatian** [ngneat/spectator#328]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`firstChild` is a property of `ActivatedRoute` but not `ActivatedRouteStub`

## Expected behavior
Ability to stub out activated route children.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## What is the motivation / use case for changing the behavior?
I have a routed component that inspects to see if it's `firstChild` was given a specific parameter.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
