### ISSUE TITLE
Is it possible to test HTTP services that use other dependencies besides HttpClient with createHttpFactory?

### ISSUE THREAD

**Issue by jkop95** [ngneat/spectator#329]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Documentation describes that when testing HTTP services, I can use `createHttpFactory`, so I can get access to such features as `expectOne` for comparing request URL with given URL etc. The example given in docs shows a simple `TodosDataService` which has only one dependency in its constructor - `HttpClient`.

What if my HTTP service has more dependencies than just HttpClient (such as a basic, custom authentication service)? Can I still somehow use createHttpFactory and take advantage of `expectOne` or do I have to stick to createServiceFactory (which, if I understand correctly, is meant for services in general - not just HTTP, and doesn't support HTTP-specific functions such as expectOne)? Is there a way to test HTTP services that have other injections (than `HttpClient`) with `createHttpFactory`?

## Expected behavior
I can use createHttpFactory for testing more advanced HTTP services than the `TodosDataService` in docs, i.e. services with more dependencies.

## What is the motivation / use case for changing the behavior?
I want to write some tests for HTTP service in my project, but it uses our custom auth service for one of its functions. After reading the docs, I'm not sure whether I can use `createHttpFactory` if my service has more than `HttpClient` in the constructor.

**Comment by NetanelBasal** [comment]
You can pass it in the `providers` [option](https://github.com/ngneat/spectator/blob/e13c9554778bdb179dfc7235aedb4b3b90302850/projects/spectator/src/lib/http.ts#L11).

**Comment by jkop95** [comment]
Thank you very much! Basing on docs, I wasn't aware that HTTP service should be passed as `dataService` to `createHttpFactory`. I guess we may consider this issue closed. :)

**Comment by RobertasM** [comment]
Hi, 

I see createHTTPFactory is deprecated and we should use createHttpFactory, which don't have **providers** option. Where we should pass other services besides HttpClient in new createHttpFactory ?

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/spectator/blob/e13c9554778bdb179dfc7235aedb4b3b90302850/projects/spectator/src/lib/spectator-http/create-factory.ts#L44
