### ISSUE TITLE
Capture component stylesheet in snapshot

### ISSUE THREAD

**Issue by zakhenry** [ngneat/spectator#330]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

I've checked multiple above as I'm not quite sure what this is!

## Current behavior
There appears to be no way to do snapshot testing in a way that also captures the component stylesheet

## Expected behavior

A simple ability to do something like 

```ts
expect(spectator.fixture.stylesheet).toMatchSnapshot()
```

## What is the motivation / use case for changing the behavior?

In our application we have fairly complicated dynamic svg components, and are currently doing jest snapshots as integration tests, however if we inspect the snapshot directly as an svg, it looks completely wrong as the stylesheet from the component is not captured. 

Instead we would like to persist a snapshot that is the full DOM of the host component as a self-contained html file, to allow for easier review of any diff that might have been caused by changes to either the ts, the html or the css

**Comment by NetanelBasal** [comment]
I'm not sure how it's related to Spectator. We're using Angular `TestBed` under the hood.

**Comment by zakhenry** [comment]
You're right that this is definitely not a specator bug, but I really tried to see if there was a way to do this and it seems that if there is a way, it is not trivial, and given spectator takes away the excessive boilerplate of vanilla angular, it feels like a good fit.

Feel free to close if you think I should just take this up with Angular directly
