### ISSUE TITLE
defineGlobalsInjections not working for TranslocoTestingModule

### ISSUE THREAD

**Issue by tommueller** [ngneat/spectator#332]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Using the `defineGlobalsInjection` does not work with Transloco. Using this as my test.ts:
```typescript
import 'zone.js/dist/zone-testing'

import { getTestBed } from '@angular/core/testing'
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing'
import { defineGlobalsInjections } from '@ngneat/spectator'
import { getTranslocoTestingModule } from 'src/transloco-testing.module'

// This file is required by karma.conf.js and loads recursively all the .spec and framework files

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);

defineGlobalsInjections({
  imports: [getTranslocoTestingModule()]
});
```
still let's my tests fail with `could not find translate of undefined`. Putting the import into the component-test directly works however.

```typescript
  const createComponent = createComponentFactory({
    component: SelectComponent,
    imports: [
      FormsModule,
      getTranslocoTestingModule()
    ]
  });
```

## Expected behavior
I would assume that the global import should work.

## What is the motivation / use case for changing the behavior?
The convenience of not having to import the module for all my components :)

## Environment

<pre><code>
Angular version: 9.1.0

**Comment by tommueller** [comment]
Ok, just after posting this I found the solution: `defineGlobalsInjections` has to be on top of the test.ts file.
Maybe you could put a hint for that into the docs. I will provide a PR ;)

**Comment by JeremieLapert** [comment]
I have the same question about Jest
