### ISSUE TITLE
@ngneat/spectator makes google cloud functions predeploy script fail

### ISSUE THREAD

**Issue by metalllus** [ngneat/spectator#339]
[x] Bug report

After installing @ngneat/spectator package with --save-dev, the predeploy script upon google cloud function deployment fails. I am using Angular 10.0.2 with Jest, Jasmine/Karma was completely removed from the project.

Running command: npm --prefix "functions" run build

> functions@ build C:\Users\metal\Dropbox\Programming\Sekacik\sekacik\functions
> tsc

../node_modules/@types/testing-library__dom/events.d.ts:86:38 - error TS2304: Cannot find name 'Document'.

86 export type FireFunction = (element: Document | Element | Window | Node, event: Event) => boolean;

../node_modules/@types/testing-library__dom/events.d.ts:86:59 - error TS2304: Cannot find name 'Window'.

86 export type FireFunction = (element: Document | Element | Window | Node, event: Event) => boolean;

I get lots of errors like this when the script fails. this is just a sample.
If I uninstall the package, everything works fine again.
Temporarily removing the node_modules\@types\testing-library__dom\ folder added by @ngneat/spectator fixes the issue as well.

**Comment by wiegell** [comment]
My problem was caused by yarn workspaces - added @types\testing-library__dom\ to nohoist in package.json, and problem solved

**Comment by metalllus** [comment]
> My problem was caused by yarn workspaces - added @types\testing-library__dom\ to nohoist in package.json, and problem solved

I do not use yarn in my project so this is not my case unfortunately I guess...
