### ISSUE TITLE
Cannot redefine property: defaultPrevented

### ISSUE THREAD

**Issue by jpzwarte** [ngneat/spectator#340]
With the latest spectator, spectator needs to add `configurable: true` on line https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/internals/event-objects.ts#L94 otherwise you will get errors with the latest Chrome.

See also https://github.com/angular/components/issues/19440

**Comment by NetanelBasal** [comment]
Do you want to open a PR?

**Comment by jpzwarte** [comment]
@NetanelBasal Thanks! Any chance you could release a new version? (5.13.2?)

**Comment by NetanelBasal** [comment]
Sure
