### ISSUE TITLE
Typescript 4 breaking change

### ISSUE THREAD

**Issue by gmfun** [ngneat/spectator#345]
## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Does not work with latest angular
</code></pre>

## Current behavior

Angular application built with v10.1 and typescript 4 is throwing error for tests

## Expected behavior

It should not throw error

## Error
`ERROR in node_modules/@ngneat/spectator/lib/spectator-routing/activated-route-stub.d.ts:26:9 - error TS2611: 'snapshot' is defined as a property in class 'ActivatedRoute', but is overridden here in 'ActivatedRouteStub' as an accessor.`

This is due to typescript 4 breaking change https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#properties-overriding-accessors-and-vice-versa-is-an-error

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by EnnoLohmann** [comment]
Hi i have made an PR for this issue. 
https://github.com/ngneat/spectator/pull/346
I am open for feedback so would be nice if you could review it  😄

**Comment by maddan** [comment]
Started seeing the above issue after we migrated to Angular 11.2.18 and "typescript": "4.1.5",
Our Spectator unit test started failing. Any suggestions what we need to do? @NetanelBasal
