### ISSUE TITLE
ngOnChanges not called when setting properties

### ISSUE THREAD

**Issue by dedwardstech** [ngneat/spectator#348]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When setting properties via `createComponentFactory(TestComponent)({ props: {} })`, ngOnChanges is not called.

## Expected behavior

In the Angular LifeCycle, `ngOnChanges` is called when properties are set initially and it's called before `ngOnInit()`. This is a known problem unit testing components that aren't inside a host component, because directly setting properties on a component bypasses change detection.

## What is the motivation / use case for changing the behavior?

I think that inside [setProps()](https://github.com/ngneat/spectator/blob/f8059560f71d614c1d25311c0bf90dd4fc59325f/projects/spectator/src/lib/internals/query.ts#L31) a `SimpleChanges` object can be built and the `ngOnChanges` function can be fired. This would help avoid confusion and google searches on why `ngOnChanges` isn't firing initially when directly testing a component.

**Comment by NetanelBasal** [comment]
You can create a PR.

**Comment by ntvsx193** [comment]
Hi!
My team recently started using this utility. I decided to fix this problem.
In fact, the only solution is to write through the host component and this imposes a small overhead.

**Comment by ntvsx193** [comment]
@NetanelBasal any news about review PR?
