### ISSUE TITLE
Wrong url to github on top bar in documentation

### ISSUE THREAD

**Issue by artur1989** [ngneat/spectator#351]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Link to github have wrong url. 

Currently is https://github.com/ngneat/specatator/

## Expected behavior

Expected be https://github.com/ngneat/spectator/

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE:
1. Click link to github in right top corner in navigation bar
</code></pre>

**Comment by geromegrignon** [comment]
@NetanelBasal it was fixed with #347 but not deployed.

**Comment by NetanelBasal** [comment]
Thanks, deploying now.
