### ISSUE TITLE
Expose dummy event creators (dispatchKeyboardEvent)

### ISSUE THREAD

**Issue by twittwer** [ngneat/spectator#353]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`dispatchKeyboardEvent` enables tests regarding keyboard events in components/directives.
It uses `createKeyboardEvent` to mock the event.

## Expected behavior & motivation

To achieve the same ease in service tests handling keyboard events (e.g. Angular CDK FocusKeyManager) it would be nice to export the internal `createKeyboardEvent` helper. Maybe it would make sense to export the other event helpers (mouse, touch) as well.

***

In case the idea is accepted I would like to provide a PR

**Comment by NetanelBasal** [comment]
Go for it.
