### ISSUE TITLE
Guidance on .query() vs .queryHost()

### ISSUE THREAD

**Issue by johncrim** [ngneat/spectator#359]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I generally find spectator super useful, but one feature that has tripped me up more than a few times is that sometimes `.query()` works for obtaining a component or HTMLElement, and sometimes `.queryHost()` works. I haven't exactly figured out what the differences are, and the docs haven't helped me.

What I end up doing is try `.query()`, check+fail if it doesn't return anything (personally I think query should throw if there is no result), and if it doesn't work try `.queryHost()`.

## Expected behavior
Either combine the APIs into one (preferred), or spell out in the docs what the differences are so it's easy to decide which to use.

## Minimal reproduction of the problem with instructions
Sorry, I wasn't able to use the starting point on ng-run to create a repro.

Here's a modified example from yesterday:
```ts
describe('Thing I'm testing', () => {

  const createHost = createHostFactory({
    component: AppComponent
  });

  it('does what I expect', () => {

    const spectator = createHost(
      `<app-component>
        <div id="child" tabindex="0"></div>
       </app-component>
       <div id="outside" tabindex="0"></div>`);

    // HERE: .query works
    const childElt = spectator.query('#child') as HTMLElement;
    assert(!!childElt);

    childElt.focus(); // spectator.focus() doesn't properly set doc.activeElement; this does (another bug)
    expect(doc.activeElement).toBe(childElt);

    // HERE: .query doesn't work; queryHost does
    (spectator.queryHost('#outside') as HTMLElement).focus();
  });

});
```

## What is the motivation / use case for changing the behavior?
Developer productivity when writing tests.

## Environment

<pre><code>
Angular version: 10.1.2
Spectator: 5.13.3
Jest: 26.4.2
</code></pre>

**Comment by NetanelBasal** [comment]
`query` => query the tested component. In your example, it's the `AppComponent`.
`queryHost` => query the `host` the hosts your tested component.

**Comment by johncrim** [comment]
OK - thank you @NetanelBasal, I suppose that makes sense. 

So, what is the difference between `query(selector, { root: true })` and `queryHost()`?

**Comment by NetanelBasal** [comment]
`root` is an alias for `document.querySelector`. It's for cases when you need to query an element that, for example, was appended to the body. ( like modals and tooltips )

**Comment by johncrim** [comment]
Thank you. That explains why there's 3 distinct scopes.

While there's probably room for improving the docs with these answers (I did look, but possibly not in the right place), my misunderstanding has been corrected. Closing.
