### ISSUE TITLE
About toHaveClass

### ISSUE THREAD

**Issue by dev054** [ngneat/spectator#361]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[?] Bug report  
[ ] Performance issue
[?] Feature request
[ ] Documentation issue or request
[ ] Support request
[?] Other... Please describe:

I don't know if it's the expected behavior or a bug.
</code></pre>

## Current behavior
I have this template:

```html
<div
  class="primary"
  [class.test]="someCondition"
  [class.awesome]="anotherCondition"
>A text</div>
```

and this spec:
```ts
expect(spectator.query(byText('A text'))).toHaveClass([
  'primary',
  'awesome',
  'test',
]);
```

...the problem is that the custom matcher `toHaveClass` expects the array to be ordered as in the same way it's rendered by Angular so to make the tests green I have to look at its rendering order to replicate in spec and I don't know if it's the expected behavior.

## Expected behavior
If it's the expected behavior, I'd suggest to create an `options` parameter to make it configurable as people may want only check the classes without caring about its order.

## Environment

<pre><code>
Angular version: 10

**Comment by NetanelBasal** [comment]
You're welcome to create a PR.

**Comment by ntvsx193** [comment]
The jasmine has support native `toHaveClass(expected: string, expectationFailOutput?: any): boolean;` from version v.3.0.0.
@dev054 it's have breaking changes with this naming.
May be name for `toHaveClassSerial` ... or any some other name.
