### ISSUE TITLE
FR: Add byRole

### ISSUE THREAD

**Issue by rafaelss95** [ngneat/spectator#362]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Add [**byRole**](https://testing-library.com/docs/dom-testing-library/api-queries#byrole) based on the `@testing-library/dom` to make it easier to grab some elements.

## Environment

<pre><code>
Angular version: 10.x

**Comment by NetanelBasal** [comment]
You're welcome to create a PR.

**Comment by stones** [comment]
I have created a PR https://github.com/ngneat/spectator/pull/365

**Comment by rafaelss95** [comment]
Thanks for the addition, I'm gonna close as it already landed in master :)
