### ISSUE TITLE
Not using spectator by default

### ISSUE THREAD

**Issue by grosch** [ngneat/spectator#366]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I generate a service, spectator is not used.  I did the CLI setting the README page shows.  Am I misunderstanding what that's supposed to do?

## Expected behavior

Use spectator :)

## Minimal reproduction of the problem with instructions

```bash
% ng config cli
{
  "defaultCollection": "@ngneat/spectator"
}
% ng g s test
CREATE src/app/test.service.spec.ts (347 bytes)
CREATE src/app/test.service.ts (133 bytes)
% cat src/app/test.service.spec.ts 
```
```typescript
import { TestBed } from '@angular/core/testing';

import { TestService } from './test.service';

describe('TestService', () => {
  let service: TestService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(TestService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
```

## Environment

<pre><code>
Angular version: 10.2.3

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v15.1.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by krzyhan** [comment]
As a workaround you can create the service with cli, adding suffix "s" 
i.e. `ng g ss serviceName`

**Comment by grosch** [comment]
@krzyhan Yup, that's what I'm currently doing.  I just normally do all those types of things inside of PhpStorm, so I was hoping the defaults worked.

**Comment by grosch** [comment]
Any thoughts on why this isn't working?
