### ISSUE TITLE
setInput to undefined on write-only variables not setting value

### ISSUE THREAD

**Issue by pascal-puetz** [ngneat/spectator#367]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When a component's `@Input` is defined as write-only (i.e. only `set` is implemented) and inside a test you want to set it to undefined via `setInput('prop', undefined)`, the setter is not called.

This worked in v6.0.0 and fails on v6.1.0

## Expected behavior
The setter should be called.

## Minimal reproduction of the problem with instructions
Component to test:

```
@Component({template: ''})
export class TestComponent {
   @Input() set prop(val:string | undefined) {
     this.someOtherVal = val;
   }

   public someOtherVal?:string;
}
```
Spec:
```
it('should reset someOtherVal to undefined, () => {
   spectator.setInput('prop', 'Something');
   expect(spectator.component.someOtherVal).toEqual('Something'); // This works
   spectator.setInput('prop', undefined); 
   expect(spectator.component.someOtherVal).toBeUndefined(); // This fails -> someOtherVal is still 'Something'
});
```

## What is the motivation / use case for changing the behavior?
We use write-only values in our application for listening to scroll changes. Whenever the element to listen on changes, we discard the old subscription and start listening on the new element. The element might be removed as well, so having an element and then removing it later is very possible. We want to test that in this case the old subscriptions are still correctly discarded.
The element does not matter, only the observables for scroll position - hence we don't want to make it accessable through a getter.

## Environment

<pre><code>
Angular version: 11.0.0

Browser:
- [X] Chrome (desktop) version 86.0.4240.198
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.6.0
- Platform:  Mac

Others:
</code></pre>

**Comment by NetanelBasal** [comment]
@ntvsx193 please check this.

**Comment by ntvsx193** [comment]
Yes, It's bug, confirmed.
I open PR with fix

**Comment by ntvsx193** [comment]
#368

**Comment by ntvsx193** [comment]
@NetanelBasal close issue, pls
