### ISSUE TITLE
calling createComponent does not reset any jest.fn mock provided in the createComponentFactory specification

### ISSUE THREAD

**Issue by remkoboschker** [ngneat/spectator#372]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I specificy a createComponentFactory with a provider override using mockProvider that contains a method overridden by `jest.fn(() => "something")`, then when I call createComponent in two tests. The jest.fn mock is not reset when calling the second createComponent.

## Expected behavior
I would expect the jest.fn mock to reset. But I suppose the instance set in the createComponetFactory is not reset or recreated.

## What is the motivation / use case for changing the behavior?
It is easy to trip on this and forget to reset the mock, because it looks like your creating a fresh component (including mocks) when calling createComponent.

Should the mocks be recreated? Or is this up to the user to remember?

## Environment

 "@ngneat/spectator": "^6.0.0",
 "@nrwl/jest": "10.3.1",
 "jest": "26.2.2",
 "jest-preset-angular": "8.3.1",

**Comment by NetanelBasal** [comment]
Duplicate of #255?

**Comment by remkoboschker** [comment]
I suppose it is a duplicate. Sorry, about that.
