### ISSUE TITLE
Support request: Excessive boilerplate

### ISSUE THREAD

**Issue by wiegell** [ngneat/spectator#374]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

I have spectator working, but i feel like i'm not using it as intended. I'm recreating the parent module for every .spec file, which seems excessive. E.g.:
**positions.component.spec.ts**
```
import { provideMockStore } from '@ngrx/store/testing';
// ... other imports ...

describe('PositionsComponent', () => {
  let spectator: Spectator<PositionsComponent>;
  const createComponent = createComponentFactory({
    component: PositionsComponent,
    declarations: [
      SettingsDashboardComponent,
      MeasurementPeriodsComponent,
      TableViewComponent,
      WorkFunctionsComponent,
      EditDiagComponent,
      PositionsComponent,
    ],
    imports: [
      HttpClientTestingModule,
      AppModule,
      NoopAnimationsModule,
      CommonModule,
      SharedModule,
      MaterialModule,
      SettingsRoutingModule,
      StoreModule.forRoot(settingsReducer),
      FormsModule,
      ReactiveFormsModule,
    ],
    providers: [
      { provide: APP_BASE_HREF, useValue: '/' },
      provideMockStore({
        initialState: {},
        selectors: [{ selector: selectSettings, value: mockState }],
      }),
    ],
  });

  beforeEach(() => (spectator = createComponent()));
// ... tests ...
}
```
Which is (almost) identical to my parent module:
**settings.module.ts**
```
@NgModule({
  declarations: [
    SettingsDashboardComponent,
    MeasurementPeriodsComponent,
    TableViewComponent,
    WorkFunctionsComponent,
    EditDiagComponent,
    PositionsComponent,
    EditPositionComponent,
  ],
  imports: [
    CommonModule,
    SharedModule,
    MaterialModule,
    SettingsRoutingModule,
    StoreModule.forFeature(settingsStoreKey, settingsReducer),
    EffectsModule.forFeature([SettingsEffects]),
    FormsModule,
    ReactiveFormsModule,
    NgxMaskModule.forChild(),
  ],
  providers: [SettingsService],
  entryComponents: [EditDiagComponent],
})
export class SettingsModule {
  constructor(private store: Store) {
    this.store.dispatch(loadSettings());
  }
}
```

What i would like to do is basically to copy the original SettingsModule, but override some of the injections (e.g. store). Is this possible? I'm somewhat new to testing, and couldn't figure it out from the documentation.
I read somewhere, that it's possible to do, if using "SCAM" (single component angular module), though i don't exactly see why that would make a difference?

Hope someone can enlighten me :)

## Environment

<pre><code>
"@angular/core": "^10.1.2",
"@ngneat/spectator": "^6.0.0",

 
For Tooling issues:
- Node version: 10.22  
- Platform: macOS 
</code></pre>

**Comment by criskrzysiu** [comment]
Hmm, maybe try out https://www.npmjs.com/package/ng-mocks#how-to-create-a-mock-module? or create a factory function?  Just a thought.

**Comment by bogusweb** [comment]
@wiegell u can create global injections, https://github.com/ngneat/spectator#global-injections

**Comment by wiegell** [comment]
I've been able to simplify to some degree by making a "componentTestModule" and importing that, but e.g. MaterialsModule will not work in this way. Global injections is not fitting IMO, if i need to leave something out of certain tests?
