### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by grosch** [ngneat/spectator#377]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

When I build my project I'm getting compiler errors from the controls in this package.  For example, this is the first one that appears:

> Error: node_modules/@ngneat/reactive-forms/lib/formControl.d.ts:20:9 - error TS2416: Property 'asyncValidator' in type 'FormControl<T, E>' is not assignable to the same property in base type 'FormControl'.
  Type 'AsyncValidatorFn<T, any> | null' is not assignable to type 'AsyncValidatorFn | null'.
    Type 'AsyncValidatorFn<T, any>' is not assignable to type 'AsyncValidatorFn'.
      Types of parameters 'control' and 'control' are incompatible.
        Type 'AbstractControl' is missing the following properties from type 'AbstractControl<T, any>': touch$, dirty$, disabled$, enabled$, status$
>
> 20     get asyncValidator(): AsyncValidatorFn<T> | null;
           ~~~~~~~~~~~~~~

## Minimal reproduction of the problem with instructions

I've attached a bare-bones project showing the issue.
[example.zip](https://github.com/ngneat/spectator/files/5674852/example.zip)

<!-- Describe the motivation or the concrete use case. -->

## Environment

<pre><code>
Angular version: 11.0.0
Browser:  N/A
For Tooling issues:
- Node version: v15.3.0  <!-- run `node --version` -->
- Platform: Mac
</code></pre>

**Comment by bogusweb** [comment]
but u have problem with `@ngneat/reactive-forms` :)
