### ISSUE TITLE
Run only specific tests and skip the rest

### ISSUE THREAD

**Issue by AhmedAlatawi** [ngneat/spectator#378]
Hi,
Looks like when I add `f` to a `describe`, like shown below, all other tests in the app still run! Is there a way to only run specific tests, and skip the rest? Thanks!
<pre><code>
import { createComponentFactory, Spectator } from '@ngneat/spectator/jest';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';

fdescribe('AppComponent', () => {
  const createComponent = createComponentFactory({
    component: AppComponent,
    imports: [ RouterTestingModule ]
  });

  let spectator: Spectator<AppComponent>;

  beforeEach(() => spectator = createComponent({detectChanges: false}));

  test('should create the root app', () => {
    const app = spectator.component;
    expect(app).toBeTruthy();
  });

})
</code></pre>

**Comment by NetanelBasal** [comment]
It doesn't relate to Spectator. You can check jest docs. https://jestjs.io/docs/en/cli
