### ISSUE TITLE
DOM Query by Custom Attribute

### ISSUE THREAD

**Issue by aaronscribner** [ngneat/spectator#380]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
We have data-qa attributes on our elements that we already use for Cypress tests and we would like to figure out how to use Spectator to DOM query based on a custom data attribute.

## Expected behavior
Would like a simplified way to select by custom attributes on the element.

## What is the motivation / use case for changing the behavior?
HTML
<input data-qa="password></input>

TS
const input = spectator.query(byAttribute('data-qa', 'password')

## Environment

<pre><code>
Angular version: 11

**Comment by stones** [comment]
Under the hood, spectator uses the [DOM testing library](https://testing-library.com/docs/dom-testing-library/intro/) under the hood for queries. 

Out of the box it provides `[ByTestId](https://testing-library.com/docs/dom-testing-library/api-queries/#bytestid)` which uses `data-testid="identifier"`, and you can configure what the test attribute is called using `configure({testIdAttribute: 'data-my-test-attribute'})`
