### ISSUE TITLE
Error Testing Components with templateUrl / styleUrls because they where never compiled

### ISSUE THREAD

**Issue by bjesuiter** [ngneat/spectator#395]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Our whole codebase has angular components like this: 
```
@Component({
  selector: 'lib-nutzungsbedingungen',
  templateUrl: './nutzungsbedingungen.component.html',
  styleUrls: ['./nutzungsbedingungen.component.scss'],
})
```

When i try to create the component with spectator, it fails with the following message: 
```
This test module uses the component NutzungsbedingungenComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.
```

## Expected behavior

Spectator notices the problem and compiles the neccessary files. Or at least offers a config for me to instruct it to do so.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

I try to come up with a sample repository on stackblitz, however, it will take some time, 
as I have to setup the correct angular version in combination with a similar testing setup to mine 
and with Spectator correctly set up. 

But I think, my explanation outlines my problem very well. 
I can't imagine that nobody had this problem before me, 
so I wonder why this is not mentioned in the docs at all?

## What is the motivation / use case for changing the behavior?

Our whole codebase uses templateURLs instead of inline templates, so I can't easily convert that. 
Also, most of our templates are too big to fit into inline templates. 
I know, I could refactor that, but that needs time I don't have right now. 

Also, I can't work around that, since I don't know how to compile the component manually via `TestBed.compileComponents()` in context of spectator createComponent() (created by createComponentFactory()).

## Environment

<pre><code>
Angular version: 8.2.3 
Note: I can't check on the newest angular version, since we are currently bound to version 8.2 by the surrounding environment our angular app runs in. 

Browser (not involved) :
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX 
- [ ] Chrome (iOS) version XX 
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.20.1  
- Platform:  Windows 10.0.17763 Build 17763 

Others:

- Jest 24.9.0
- Spectator Version: 6.1.3
</code></pre>

**Comment by bjesuiter** [comment]
## Update 2020-02-11

I made a test repo for this problem: 
https://github.com/bjesuiter/ngneat-spectator-issue-395-sample-repo

An here the running Stackblitz (not so useful for running tests)
http://stackblitz.com/github/bjesuiter/ngneat-spectator-issue-395-sample-repo

Findings: 
- The test seems to work flawlessly

Next Steps: 
- Comparing this demo setup with my actual setup to find differences.

**Comment by ecstaticrainbow** [comment]
Did you workout what was wrong with your setup and the demo setup? I'm having the same issue

**Comment by bjesuiter** [comment]
Yes, I found the issue. 
Spectator does not mock components automatically. 
So you need to install a mocking library, the main example for that is ng-mock. 

It is also available in the docs, albeit a little hidden: 
https://ngneat.github.io/spectator/docs/mocking-components/

Simply add a mock for all components (or at least all custom components) which are used in the template of the component, you want to test and then it should work

**Comment by ecstaticrainbow** [comment]
Ah brilliant thank you!
