### ISSUE TITLE
Invalid Link to FAQs

### ISSUE THREAD

**Issue by Runster** [ngneat/spectator#401]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The link to the FAQs in the footer of the page is invalid. It directs to an empty Page (404): https://ngneat.github.io/spectator/docs/faq

Should be happen in every browser and for everyone ..

**Comment by NetanelBasal** [comment]
Removed. Thanks.
