### ISSUE TITLE
Add VSCode snippet for jest

### ISSUE THREAD

**Issue by ebichan38** [ngneat/spectator#404]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

VSCode snnippets are compatible only with Jasmine (import from '@ngneat/spectator')

## Expected behavior

Adding snippets like `spec-comp-jest`, which will import from '@ngneat/spectator/jest'

## What is the motivation / use case for changing the behavior?

It's helpful for jest users to avoid import mistake

Others:

If this idea is acceptable I'll open PR. Thank you for great product!
</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by ebichan38** [comment]
I have submitted a PR. https://github.com/ngneat/spectator/pull/407 .
I'm sorry for that I have mistakenly submitterd https://github.com/ngneat/spectator/pull/406. Please igonre it.
