### ISSUE TITLE
TriggerEventHandler should provide an option to query from 'root'

### ISSUE THREAD

**Issue by anandtiwary** [ngneat/spectator#414]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Some components create popover elements which are part of the Dom root. These dom elements are not descendants of the spectator host element. The spectator api provides an option to query them using the `{root: true}` option. This works well.

With my use case, I am trying to trigger an event handler using `triggerEventHandler` method on a child component which is being displayed inside the  popover. This of course doesn't work. I think we would need a similar `{root: true}` option to support this use case. If there is an alternative could you please point me towards the same?

## Expected behavior

We should be able to `triggerEventHandler` method with the root option.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

1. Create a host component that has a Popover component inside (or any thing that attaches the content to the root dom). 
2. Add any other component to this popover's content. 
3. From the host component, trigger the popover to show its content in an overlay
4. Now Trigger an event handler using `triggerEventHandler` on the **child component**. This should trigger corresponding handler in the host component

## What is the motivation / use case for changing the behavior?

Missing behavior

## Environment

<pre><code>
Angular version: 11.X

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   v15.3.0
- Platform:   MAc

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
