### ISSUE TITLE
Add example of pipe in template to documentation

### ISSUE THREAD

**Issue by leoleoff** [ngneat/spectator#435]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
This took me a long time to debug, I had a custom pipe on my template `duration | visualTime`, and I was trying query a component with Spectator.
It fails without giving an error, and the solution was to add `declarations: [VisualTimePipe]` to the `createComponentFactory`.

## What is the motivation / use case for changing the behavior?
Since pipes are a common thing to create and use, I think new users would appreciate having an example of this in the documentation, that can be easily found with a ctrl+f.

**Comment by NetanelBasal** [comment]
I can't see how it's different from directives, for example. Feel free to open a PR.
