### ISSUE TITLE
Changing a host prop after creation

### ISSUE THREAD

**Issue by Foxandxss** [ngneat/spectator#438]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Imagine I create a Directive like:

```
spectator = createDirective(
  '<div foo="bar">Baz</div>',
  {
    hostProps: {
      foo: 'Something',
    },
  }
);
```

I test it, all good, but what if I want to update `foo` to see how it changes its behavior?

I can't do:

```
spectator.hostComponent.foo = '...';
```

Because `foo` doesn't exist in `hostComponent`.

I can certainly do: 

```
const hostComponent = spectator.hostComponent as any;
hostComponent.foo = '...';
```

## Expected behavior

Is there a proper way to do this without casting? Or am I doing this all wrong?

**Comment by NetanelBasal** [comment]
You can pass the type here: https://github.com/ngneat/spectator/blob/65022848934a640f85cdfc7a6518650cea7bd677/projects/spectator/src/lib/spectator-directive/create-factory.ts#L48
