### ISSUE TITLE
HttpClient issue with Angular 12 and jest

### ISSUE THREAD

**Issue by gentleman-turk** [ngneat/spectator#441]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  (Searched for similar issue, I could not find one)
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Since updating to angular v12, I can't seem to get any tests to work when using httpclient within @ngneat/spectator/jest.

I'm getting the error:
<pre><code>
 Can't resolve all parameters for FakeService: (?).
</code></pre>

## Expected behavior
Expected my unit tests would run as they did when using angular v11.

## Minimal reproduction of the problem with instructions
<pre><code>
import { createHttpFactory, SpectatorHttp } from "@ngneat/spectator/jest";
import { HttpClient } from "@angular/common/http";
import { Injectable } from "@angular/core";
@Injectable({
    providedIn: "root"
})
export class FakeService {
    constructor(private http: HttpClient) { }
}

describe("genericRetryStrategy", () => {
    let spectator: SpectatorHttp<FakeService>;
    const createHttp = createHttpFactory(FakeService);

    beforeEach(() => {
        spectator = createHttp();
    });

    it("should create service", (() => {
        expect(spectator.service).toBeTruthy();
    }));
});
</code></pre>

## What is the motivation / use case for changing the behavior?
backwards compatibility.

## Environment

<pre><code>
Angular CLI: 12.0.2
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  v12.22.1
- Platform:  Windows 10

Others:

</code></pre>

**Comment by aintnomoreloyalty** [comment]
Got the same issue:
```Error: Can't resolve all parameters for AuthService: (?, ?, ?, ?)```
Everything was working before updating to Angular 12

**Comment by arunpk11** [comment]
Is this resolved?

**Comment by NetanelBasal** [comment]
Can you try v8? I upgraded to v12, and the specs pass.

**Comment by gentleman-turk** [comment]
Sorry, I should have closed this earlier. Once we updated to Angular 12.1.0 the issues went away. I saw this issue from 12.0.0-12.0.5.

**Comment by gentleman-turk** [comment]
Closing since 12.1.0 works.
