### ISSUE TITLE
Upgrade to v12

### ISSUE THREAD

**Issue by grosch** [ngneat/spectator#442]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

When trying to create a service I get an error.

## Minimal reproduction of the problem with instructions

% ng g ss Locale
"SpectatorSchematicsAngularService" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SpectatorSchematicsAngularService" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Schematic input does not validate against the Schema: {"name":"Locale","project":"BoltOn","flat":true,"spec":false,"skipTests":true,"isDataService":false,"jest":false}
Errors:

  Data path "" must NOT have additional properties(spec).

## Environment

<pre><code>
Angular version: 12.0.2

For Tooling issues:
- Node version: 12.19.0
- Platform:   Windows

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
We need to upgrade to v12.

**Comment by DaSchTour** [comment]
I have probably already fixed this issue in my PR https://github.com/ngneat/spectator/pull/437 but I can't get it to work locally to test it

**Comment by NetanelBasal** [comment]
You need to build it and use npm link

**Comment by NetanelBasal** [comment]
We can also add the new configuration to make specs faster:

https://github.com/angular/angular/pull/42566

**Comment by grosch** [comment]
Any ETA on when you might have time to implement this?

**Comment by NetanelBasal** [comment]
@grosch, No. You're welcome to submit a PR if you want to help :)

**Comment by DaSchTour** [comment]
@grosch it is blocked because build is not working: https://github.com/ngneat/spectator/pull/437#issuecomment-845714182
