### ISSUE TITLE
The return type of `spectator.query` is not compatible with the expected type for the `selector` parameter of `spectator.typeInElement`.

### ISSUE THREAD

**Issue by animamundi** [ngneat/spectator#447]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The return type of `spectator.query` is not compatible with the expected type for the `selector` parameter of `spectator.typeInElement`. The following error is thrown by Typescript:
```
Argument of type 'Element | null' is not assignable to parameter of type 'SpectatorElement | undefined'.
  Type 'null' is not assignable to type 'SpectatorElement | undefined'.ts(2345)
```

## Expected behavior
I'd expect to be able to pass the element returned from `spectator.query` directly into `spectator.typeInElement`. Since it's an optional parameter, it shouldn't matter if I pass in `null`.

## Minimal reproduction of the problem with instructions
```typescript
const nameInput = spectator.query('input');
spectator.typeInElement("Hello World", nameInput);
```

## What is the motivation / use case for changing the behavior?
As it stands now, I will need to explicitly cast my element before passing it into the query function, which can result in a loss of type safety.

## Environment

<pre><code>
Angular version: 12.0.0
Typescript version: 4.2.4
Browser: N/A
For Tooling issues: N/A
Others:
It only applies with `strictNullChecks` turned on for Typescript, which is the case by default in new Angular projects these days.
</code></pre>

**Comment by NetanelBasal** [comment]
The issue is with the `null` type. You can use not null assertion:

`spectator.typeInElement("Hello World", nameInput!)`

**Comment by animamundi** [comment]
I'm not fond of the suggestion since any reader of the code not familiar with it will be asking why we have to use the not null assertion here. I think `typeInElement` should be able to receive null if it can already receive `undefined`. Especially since these two functions are probably going to be used together, should their types not be compatible?

**Comment by NetanelBasal** [comment]
There is an `undefined` because you don't have to pass an element. The default is the element itself.

**Comment by animamundi** [comment]
I can see that we don't see this the same way so I will close. Thanks for your time.
