### ISSUE TITLE
Not called angular hooks when disabled detectChanges and setInput called

### ISSUE THREAD

**Issue by ntvsx193** [ngneat/spectator#461]
`ngOnInit`, `ngAfterViewInit` and other hooks not called when use `createComponentFactory` + `detectChanges = false` + `setInput`

## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`ngOnInit`, `ngAfterViewInit` and other hooks not called

## Expected behavior
`ngOnInit`, `ngAfterViewInit` and other hooks called

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-testing-senb4a?file=app%2Fapp.component.spec.ts

## Environment

<pre><code>
Angular version: 11.2.9

Browser:
- [x] Chrome (desktop) version 92.0.4515.107
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.17.4
- Platform:  Mac
</code></pre>

**Comment by NetanelBasal** [comment]
You need to call detectChanges()

**Comment by ntvsx193** [comment]
Why are u close problem?
`setInput` is calling detectChanges, but insatance of caller DC is `debugElement` on element, not root.

dom-spectator.ts:
```
public setInput(input: any, value?: any): void {
  setProps(this.instance, input, value, false);
  this.debugElement.injector.get(ChangeDetectorRef).detectChanges();
}

public detectChanges(): void {
  this.fixture.detectChanges();
}

```

Unfortunately, you use root in `createHostFactory`, in `setHostInput` spectator-host/spectator-host.ts:
```
public setHostInput(input: any, value?: any): void {
  setProps(this.hostComponent, input, value, false);
  this.detectChanges();
}
```

Why use different instances of DC?

**Comment by NetanelBasal** [comment]
It's an Angular design. When you call detectChanges it will call ngOnInit. This is not a Spectator issue. That's why I closed it.
