### ISSUE TITLE
triggerEventHandler and void

### ISSUE THREAD

**Issue by grosch** [ngneat/spectator#467]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`triggerEventHandler` requires three arguments, which seems to imply that it doesn't work with void event emitters?

## Expected behavior

I though I should be able to do `spectator.triggerEventHandler(MyComponent, 'myEventEmitter')`

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

```ts
@Component({
    selector: 'app-child',
    template: ''
})
class ChildComponent {
    @Output() linkChanged = new EventEmitter<void>()
}

@Component({
    selector: 'x',
    template: '<app-child (linkChanged)="changed()"></app-child>'
})
class FooComponent {
    changed(): void {}
}

describe('FooComponent', () => {
    it('should emit', () => {
        const createComponent = createComponentFactory(FooComponent)
        const spectator = createComponent()
        spectator.triggerEventHandler(ChildComponent, 'linkChanged')
    })
})
```

## Environment

<pre><code>
Angular version: 12.0.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/spectator/blob/ac40000dfa6665468e24e22607351e90c3805501/projects/spectator/jest/test/button/button.component.spec.ts#L35
