### ISSUE TITLE
Component with async onInit not properly waiting for changes

### ISSUE THREAD

**Issue by celluj34** [ngneat/spectator#469]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

A component with `ngOnInit` that returns a promise functions as if it is not being `await`ed when `spectator.detectChanges()` is called with `detectChanges: false`.

## Expected behavior

Any component with an `async` `ngOnInit` is successfully handled by the `spectator.detectChanges()` method.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).
Steps:
* Create component that implements OnInit
* Create ngOnInit method which returns a promise
  * set some data in the method (like `this.loading = false`)
* Create test to check the above field
* Test will fail because "true" does not equal "false"

The issue can be worked around either by calling `spectator.component.ngOnInit` or `await`ing a promise with a short timeout (e.g. 200ms).

## What is the motivation / use case for changing the behavior?

Angular supports async ngOnInit, so tests should too.

## Environment

<pre><code>
Angular version: 12.1.4

Browser:
- [X] Chrome (desktop) version 92
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.3.0 
- Platform: Win 10 x64  

Others:

</code></pre>

**Comment by benelliott** [comment]
This is the first time I've heard that you can return a `Promise` from a lifecycle hook and I can't find documentation of it online, would you mind pointing to some Angular docs where it's described?

In the interface definition [here](https://github.com/angular/angular/blob/master/packages/core/src/interface/lifecycle_hooks.ts#L64) it seems that it only supports `void`.
