### ISSUE TITLE
spectator.blur(..) broken in jest tests since v8.0.3

### ISSUE THREAD

**Issue by mvindahl** [ngneat/spectator#477]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`spectator.blur(..)` does not work in jest tests when using spectator 8.0.3.

We believe this to be due to the recent fix for https://github.com/ngneat/spectator/issues/373.
Specifically, we believe the regression to be caused by the following change which alters the behavior when running jest: https://github.com/johncrim/spectator/commit/9ff8bd4cce562e8c726d378a4f07ea1ea9c0f5ab#diff-fdb99b18d9100abb482776b5c9d72409c00c0d64e919c825e993de6f643865a0R16 

## Expected behavior

It should work like it did in 8.0.2, and like it continues to do for jasmine tests.

## Minimal reproduction of the problem with instructions
The regression is easily reproduced by copying the events component spec into the spectator/jest/test folder, "jestifying" the spectator import, and executing jest tests:

Using MacOS bash:
```bash
cp -r projects/spectator/test/events projects/spectator/jest/test
sed -i '' s#'@ngneat/spectator'#'@ngneat/spectator/jest'# projects/spectator/jest/test/events/events.component.spec.ts
yarn test:jest
```

The output will now show the blur method to not work:
```
Summary of all failing tests
 FAIL  projects/spectator/jest/test/events/events.component.spec.ts (12.443 s)
  ● EventsComponent › should handle blur

    Expected element to have  text 'blur', but had ''

      17 |   it('should handle blur', () => {
      18 |     spectator.blur('input');
    > 19 |     expect(spectator.query('h1')).toHaveText('blur');
         |                                   ^
[...]
Test Suites: 1 failed, 1 skipped, 28 passed, 29 of 30 total
```
On a side note, it would probably be a good idea to keep this jest specific test as part of the fix since focus and blur can no longer be assumed to be handled in the same way across jasmine and jest.

## Environment

Checked out the most recent master from ngneat/spectator. The issue is specific to jest tests so browsers are not relevant.

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.16.1  
- Platform: Mac 

Others:

</code></pre>

**Comment by johncrim** [comment]
Perhaps this info should be in the docs:

> In Jest tests, only legitimate focusable elements can be `focus()`ed, and only an element with focus can be `blur()`ed. For example, elements that aren't normally focusable (eg a `<div>`) must have tabindex="0" or similar to make the element focusable.
> 
> In Karma/browser tests `Spectator.focus()` and `Spectator.blur()` can be called on any element, and not all browser side effects from focusing and blurring occur (eg `document.activeElement` may not be updated, depending on the browser). This inconsistency occurs because some browsers don't properly focus/blur when the component is not visible; `Spectator.focus()` and `Spectator.blur()` detect when the browser did not send the expected events, and fake events are dispatched.

**Comment by mvindahl** [comment]
Hello @johncrim , thanks for your feedback. I had initially reached the conclusion that blur behaviour had been broken -- seeing some of our existing tests that would previously pass but would now fail. On closer reflection, and having investigated the details, my understanding now aligns with yours: JSDom does a better job of mimicking the browser than did the spectator focus/blur patch.

Your comment on the 373 issue explains it well; I had somehow managed to overlook that, for which I apologise.

As for the docs, I agree that we should not describe the subtle differences in painstaking detail in the docs; this would just leave people confused. How do you like my PR suggestion which adds a somewhat broadly phrased one liner to the docs?

**Comment by johncrim** [comment]
@mvindahl: I think your comment is good - it at least gives the reader something to try if they're encountering a problem with `blur()`, without bogging them down with possibly unnecessary details. How about adding a link to this issue if the reader needs more info on `.focus()` and `.blur()`  methods?

**Comment by NetanelBasal** [comment]
We should also mention the environment.

**Comment by mvindahl** [comment]
@NetanelBasal , which level of detail would you prefer?

1) Current suggestion, arguably too broad
> Note that if the element does not have focus, blur() may be ignored.

2) Explicit mention that this only applies to jest tests:
> Note that if using the jest framework, blur() only works if the element is focused.

3) .. and a link to John's fine description for the curious reader:
> Note that if using the jest framework, blur() only works if the element is focused. [Details]( https://github.com/ngneat/spectator/issues/373#issuecomment-896285805).

4) Even more details?

**Comment by NetanelBasal** [comment]
Option 3, thanks.

**Comment by mvindahl** [comment]
👍

I have updated the PR accordingly.
