### ISSUE TITLE
8.0.4 broke element blur in jsDom

### ISSUE THREAD

**Issue by RGunning** [ngneat/spectator#482]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Calling blur on a element when in a jsDom environment triggers the angular cdkFocusMonitor

Prior to 8.0.4 calling `spectator.blur` on a input element with a cdkFocusMonitor listening to the parent element would trigger the subscribe. Current behaviour is that the subscribe is no longer called.

```ts
   ngAfterViewInit() {
        this.focusMonitor
            .monitor(this.elementRef, true)
            .pipe(takeUntil(this.ngUnsubscribe$))
            .subscribe((focusOrigin) => {
                if (!focusOrigin) {
                    Promise.resolve().then(() => {
                        this.onTouched();
                        this.cdRef.markForCheck();
                    });
                }
            });
    }
``` 

## Expected behavior

The blur bubbles in a jsDom environment and trigger the focus monitor subscription.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

## What is the motivation / use case for changing the behavior?

8.0.4 breaks my unit tests, so i can't update to latest spectator.

## Environment

<pre><code>
Angular version: 11.2.14

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.17.3  
- Platform: Mac/Linux 

Others:

</code></pre>

Bug introduced by https://github.com/ngneat/spectator/pull/473/files if in a jsDom environment `patchElementFocus` no longer does anything when it used to call `element.focus = () => dispatchFakeEvent(element, 'focus'); element.blur = () => dispatchFakeEvent(element, 'blur');` 

Re-adding `element.blur = () => dispatchFakeEvent(element, 'blur');` is enough to restore old behaviour.

**Comment by NetanelBasal** [comment]
@johncrim

**Comment by RGunning** [comment]
duplicate of https://github.com/ngneat/spectator/issues/477

same fix as there, need to call focus before blur now
