### ISSUE TITLE
Cannot find type definition file for 'jasmine'

### ISSUE THREAD

**Issue by matheo** [ngneat/spectator#508]
### Is this a regression?

No

### Description

We just upgraded
from Angular 11 + Jest 26 + Spectator 7
to Angular 12 + Jest 27 + Spectator 8
and after managing to put all the dependencies in place, we're getting this:
![image](https://user-images.githubusercontent.com/260185/140632530-a7154f5d-6eba-45ac-9fb1-28f6f4dcc506.png)

I've tried to install `@types/jasmine` but it conflicts with `@types/jest`
is it possible to move that "workaround" to somewhere else in the package config?
Thanks in advance

### Do you want to create a pull request?

No

**Comment by matheo** [comment]
Unfortunately `jest/lib/mock.d.ts` imports `SpyObject` from the base package, and there's the `jasmine` ref

**Comment by bboyle** [comment]
FYI, I've encountered this when trying to run storybook with angular (and I use jest for testing, not jasmine). It hasn't come up compiling the angular app, but when running storybook it runs into a jest/jasmine conflict. I've been working around it by manually deleting comment from mocks.ts, and manually removing the `@types/jasmine` folder from node_modules. Don't know how to fix (I'd make a PR if I can) but a fix would be awesome. (This niggle aside, the spectator library is great!)

**Comment by matheo** [comment]
@bboyle so far I've been able to avoid this error importing from `@ngneat/spectator/jest` in my spec files.
The only import I need from `@ngneat/spectator` is to `defineGlobalsInjections` in the jest setup file.

**Comment by bboyle** [comment]
@matheo good tip. I have definitely caught myself importing from `@ngneat/spectator` in the past.

I've got it all sorted except for `createKeyboardEvent` …

```ts
import { createKeyboardEvent } from '@ngneat/spectator';
```

vscode tells me it's not exported from `@ngneat/spectator/jest`?

**Comment by matheo** [comment]
@NetanelBasal should I reopen and rename the issue to have `createKeyboardEvent` for `jest`?

**Comment by zagoa** [comment]
> FYI, I've encountered this when trying to run storybook with angular (and I use jest for testing, not jasmine). It hasn't come up compiling the angular app, but when running storybook it runs into a jest/jasmine conflict. I've been working around it by manually deleting comment from mocks.ts, and manually removing the `@types/jasmine` folder from node_modules. Don't know how to fix (I'd make a PR if I can) but a fix would be awesome. (This niggle aside, the spectator library is great!)

I had the same problem. To resolve it please look at your `.storybook/tsconfig.json` and in the exclude section be sure it point to the right `test.ts`. In my case it was pointing to the `../src/test.ts` whereas the right path is `../projects/my-project/src/test.ts`. After doing the compiler will understand that there will be no more related link to spectator lib.
