### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by wSedlacek** [ngneat/spectator#513]
### Description

When running this project with [jest-preset-angular](https://github.com/thymikee/jest-preset-angular) on Angular 13 creating a routing component fails due to it trying to call an Angular `.mjs` import in a `umd` file

### Steps to reproduce:
1. Clone [jest-preset-angular](https://github.com/thymikee/jest-preset-angular)
2. Install example-app-v13
3. Install `@ngneat/spectator`
4. Configure `app.component.spec.ts` like so
```ts
import { Spectator, createRoutingFactory } from '@ngneat/spectator/jest';

import { AppComponent } from './app.component';

describe('AppComponent', () => {
  let spectator: Spectator<AppComponent>;
  const createComponent = createRoutingFactory({
    component: AppComponent,
    stubsEnabled: false,
    routes: [],
  });

  beforeEach(() => (spectator = createComponent()));

  it('should create the app', () => {
    const app = spectator.fixture.componentInstance;

    expect(app).toBeInstanceOf(AppComponent);
  });
});
```
5. Run test

### Expected results
Test to pass

### Actual results
Test fail with the following error
```
$ jest --no-cache
ngcc-jest-processor: running ngcc
 FAIL  src/app/app.component.spec.ts
  AppComponent
    ✕ should create the app (6 ms)

  ● AppComponent › should create the app

    TypeError: Class constructor ActivatedRoute cannot be invoked without 'new'

      11 |   });
      12 |
    > 13 |   beforeEach(() => (spectator = createComponent()));
         |                                 ^
      14 |
      15 |   it('should create the app', () => {
      16 |     const app = spectator.fixture.componentInstance;

      at new ActivatedRouteStub (node_modules/projects/spectator/src/lib/spectator-routing/activated-route-stub.ts:30:5)
      at src/app/app.component.spec.ts:13:33

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.842 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I traced this back and it's actually trying to run the `examples/example-app-v13/node_modules/@ngneat/spectator/bundles/ngneat-spectator.umd.js` file which errors on this line
```js
  var ActivatedRouteStub = /** @class */ (function (_super) {
        __extends(ActivatedRouteStub, _super);
        function ActivatedRouteStub(options) {
            var _this = _super.call(this) || this;
            ...
```

### Other details

Running the same test with the `example-app-v12` does not produce such an error.
The same `ngneat-spectator.umd.js` file is run, it just runs without errors on v12 for some reason.

At run time I logged out the value for `ActivatedRoute` and I got the following results.
v12 - `[Function: ActivatedRoute]`
v13 - `[class ActivatedRoute]`

### Possible solution

I believe this problem can be resolved by disturbing `.mjs` files and possibly dropping the umd format.
From my understanding umd isn't generated by the latest versions of ng-packagr anymore.
https://github.com/ng-packagr/ng-packagr/releases/tag/v13.0.0

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
The library isn't compatible with Angular v13.
