### ISSUE TITLE
Spy / call services' methods before component is created?

### ISSUE THREAD

**Issue by sharshuv-quotient** [ngneat/spectator#533]
### Description

Hey, I have a scenario in which I want to make some preparation before the component is created. For example, mock methods in services that are called upon component creation. 
Currently I don't think there is a way to do it in spectator. (Correct me if I'm wrong)

### Proposed solution

Add a property to SpectatorOverrides and to BaseSpectatorOptions: 
```
beforeCreation: (beforeCreationOptions?: { <something-that-will-enable-injecting-services> }) => void;
```
So the consumer can inject services, call methods, or mock them, before the component is being created. 

### Alternatives considered

Currently the only alternative I could find is not using spectator.

### Do you want to create a pull request?

I'm willing to try to implement it myself, if the idea sounds good to the moderators.

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/spectator#mocking-providers

**Comment by jnizet** [comment]
I have the same issue and I don't see how this chapter of the documentation solves it. 

Basically, if a dependency is called directly from the constructor, and not from ngOnInit, then there is a chicken an egg problem: you need the spectator to access the mocked service and tell it what to do, but creating the spectator also creates the component and thus calls its constructor.

So, as far as I understand, either ngOnInit must be used to access the mocked dependency instead of the constructor, or a mock must be created and passed as a provider.

**Comment by NetanelBasal** [comment]
> Basically, if a dependency is called directly from the constructor,

This is an anti-pattern.

**Comment by jnizet** [comment]
Well, a lot of people disagree with that, including in the Angular team (see https://discord.com/channels/748677963142135818/748806247926726736/836316474725498891). Especially with strict null checks, where initializing stuff in the constructor makes it much cleaner.

**Comment by jnizet** [comment]
For the record, one relatively simple way to do it is

```ts
  beforeEach(() => {
    someService = createSpyObject(SomeService);
    someService.foo.and.returnValue(something);

    spectator = createComponent({
      providers: [
        {
          provide: SomeService,
          useValue: someService
        }
      ]
    });
  });
```

**Comment by NetanelBasal** [comment]
Correct

**Comment by NetanelBasal** [comment]
@jnizet will you benefit from the suggested solution?

**Comment by jnizet** [comment]
You probably wanted to as @sharshuv-quotient. 

I find it simple enough. But I'd say this is a common enough problem to deserve a note in the documentation, in the same vein as the section about [mocking ngOnInit dependencies](https://github.com/ngneat/spectator#mocking-oninit-dependencies).

I can make a PR if you agree.
