### ISSUE TITLE
byRole selector does not work when running tests with @angular-builders

### ISSUE THREAD

**Issue by andreashouben** [ngneat/spectator#538]
### Is this a regression?

No

### Description

In my customers project we use [@angular-builders](https://github.com/just-jeb/angular-builders/tree/master/packages/jest) to run our angular tests with spectator.

For some reason querying HtmlElements with byRole always returns null.

If I run the tests with jest, the byRole selector works.

For a very simple component that simply renders a button I wrote the following test:

```javascript

describe('ButtonComponent', () => {
  let spectator: Spectator<ButtonComponent>
  const createComponent = createComponentFactory({
    component: ButtonComponent
  })

  beforeEach(async ()=>{
    spectator = createComponent()
  })

  it('should find the button', () =>{
    console.log(spectator.query(byRole('button')))
  })
});

```

If I run this with angular-builders I get the following console.log output:

```
 PASS  src/app/button/button.component.spec.ts
  ● Console

    console.log
      null

      at src/app/button/button.component.spec.ts:16:13
```

If I run it with jest the same test produces:
```
 PASS  src/app/button/button.component.spec.ts
  ● Console

    console.log
      <ref *3> HTMLButtonElement {
        __ngContext__: <ref *1> LComponentView(22) [
          HTMLDivElement {
            __ngContext__: [LRootView],
            __ng_debug__: [DebugElement]
          },
...
```

I linked my repository below, where you can see this behavior. The main branch runs with jest, the "angular-builders" branch with angular-builders.

### Please provide a link to a minimal reproduction of the bug

https://github.com/andreashouben/spectator-by-role

### Please provide the exception or error you saw

```true
See description above.
```

### Please provide the environment you discovered this bug in

```true
Mac OS, node version 16.13.1
Windows, node version 16.13.1
```

### Do you want to create a pull request?

No

**Comment by benelliott** [comment]
Under the hood, Spectator's `byRole` query is powered by `@testing-library/dom`.  If you take a look at https://github.com/testing-library/dom-testing-library/blob/30bd61453645d29fc9419854ac18e739d0066c2f/src/queries/role.js#L173 you can see that by default the query filters out any results that are inacessible in the viewport.

When you disable this filtering by passing the options `{hidden: true}` in your unit test, the test passes. So it must be that the `@angular-builders` runner is running the component tests in an inaccessible container while the Jest runner is not.

**Comment by andreashouben** [comment]
Thanks for the analysis. This is a great help! I will file an issue with `@angular-builders`
