### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by jadengis** [ngneat/spectator#551]
### Description

Currently standalone components, directives and pipes cannot be tested because they are automatically added to the `declarations` portion when configuring TestBed internally. Angular throws an error when trying to declare a standalone component. 

### Proposed solution

Add the component/directive/pipe-under-test to the imports section of `TestBed.configureTestingModule` if the component is standalone.

### Alternatives considered

There isn't really a way to work around this.

### Do you want to create a pull request?

Yes

**Comment by anikets43** [comment]
Angular 14 supports template binding to protected component members. But the same is not supported by `props`

<img width="463" alt="image" src="https://user-images.githubusercontent.com/7136799/172152037-02566d0a-537a-41db-aa52-2735f3c11b25.png">

```
Type '{ opened: true; }' is not assignable to type 'Partial<ThemeComponent>'.
  Object literal may only specify known properties, and 'opened' does not exist in type 'Partial<ThemeComponent>'.ts(2322)
create-factory.d.ts(14, 5): The expected type comes from property 'props' which is declared here on type 'CorrSpectatorOverrides<ThemeComponent>'
```

**Comment by jadengis** [comment]
I might take a stab at this.

**Comment by jadengis** [comment]
I opened a PR for this change here: https://github.com/ngneat/spectator/pull/553
