### ISSUE TITLE
Jest service mocks have wrong types

### ISSUE THREAD

**Issue by DaSchTour** [ngneat/spectator#614]
### Discussed in https://github.com/ngneat/spectator/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **DaSchTour** June  1, 2023</sup>
I have some code that uses mocks and jest functions like `mockReturnValue`. For example like this

```ts
const fooService = spectator.inject(FooService);
fooService.someMethod.mockReturnValue({foo: 'bar'});
```

This worked fine but now suddenly I get typescript errors `TS2339: Property 'mockReturnValue' does not exist on type '((key: string | null, location?: string | undefined) => Observable ) & CompatibleSpy'.`.

It looks like typescript doesn't use the jest typings but the jasmine version.

I'm not sure if that is an issue with my configuration, with a wrong version of jest or maybe caused by TypeScript 5. Did anybody else expect similar issues?</div>

This issue is also present in https://github.com/ngneat/spectator/blob/master/projects/spectator/jest/test/auth.service.spec.ts

So probably there is something wrong with the jest SpyObject typings.

Interesting is, that when opening the file in VSCode or IntelliJ there are errors shown, but the test run correctly without issues.

**Comment by chimurai** [comment]
@DaSchTour @elmarbeckmann Could you verify the fix in PR https://github.com/ngneat/spectator/pull/615?

**Comment by DaSchTour** [comment]
@chimurai when looking on the specs in spectator repo it looks fine. When trying to verify it with `npm link` I get a lot of new very strange errors. But the typings for mocks are correct.

**Comment by chimurai** [comment]
Could you try to manually patch `node_modules/@ngneat/spectator/jest/lib/mock.d.ts`? (instead of using `npm link`)

And apply the change from https://github.com/ngneat/spectator/pull/615/files

**Comment by DaSchTour** [comment]
@chimurai sorry for the late response. I now checked with patching the file and all test work fine. Thanks a lot
