### ISSUE TITLE
Angular 16 | Transform Input Values

### ISSUE THREAD

**Issue by LukasMachetanz** [ngneat/spectator#619]
As described in [article](https://netbasal.com/say-goodbye-to-setters-and-getters-angulars-transform-option-for-input-values-88fd9442dcad) a new helpful feature has been introduced in Angular v16.1.0 to provide an alternative and easy way to transform input values.

It seems that the corresponding transformation function is not executed having a setup using `spectator`. I would expect that the function is executed though.

**Comment by NetanelBasal** [comment]
and without Spectator it works?

**Comment by LukasMachetanz** [comment]
To be honest, I did not try it yet. But I will do it and come back to you. 

But in general, wouldn’t you expect that it should work?

**Comment by LukasMachetanz** [comment]
It does not work with the native Angular testing setup either. To be more precise, it does not work creating the component under test directly. The transformation function is only executed having a host component in place.

Using spectator it does work using `createHostFactory` instead of `createComponentFactory` as well. Therefore, this issue can be considered as resolved.

To be honest, I did not expect this behaviour, but apparently that's how it currently works. In the end it's at least a lesson learned.
