### ISSUE TITLE
Support Angular 17

### ISSUE THREAD

**Issue by vecernik** [ngneat/spectator#631]
### Is this a regression?

Yes

### Description

Please add a support for styleUrl (singular) in components.

### Please provide the exception or error you saw

```true
Component 'TopSearchHeaderComponent' is not resolved:
 - styleUrl: ./top-search-header.component.scss
Did you run and wait for 'resolveComponentResources()'?

  let s: Spectator<TopSearchHeaderComponent>

  const createComponent = createComponentFactory({
    component: TopSearchHeaderComponent,
    imports: [ MatIconTestingModule ],
  })
```

### Please provide the environment you discovered this bug in

```true
Nx workspace @nx/jest 17.1.1, Spectator 15.0.1, jest 29.7.0, jest-preset-angular 13.1.3
```

### Do you want to create a pull request?

Yes

**Comment by netanel-utila** [comment]
You are welcome to create a PR that upgrades to v17

**Comment by timonmasberg** [comment]
I still have this issue with the latest version
