### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Playthrough')

### ISSUE THREAD

**Issue by dexster** [ngneat/spectator#644]
### Is this a regression?

Yes

### Description

This error occurs when running a test on 17.0.1. When downgrading to 17.0.0 the tests run correctly 

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of undefined (reading 'Playthrough')

import { Spectator, createComponentFactory } from '@ngneat/spectator/jest';
         | ^
      29 |
      30 | describe('LoginComponent', () => {
      31 |   let spectator: Spectator<LoginComponent>;

      at Object.<anonymous> (../../node_modules/@ngneat/spectator/fesm2022/ngneat-spectator.mjs:1453:44)
      at Object.<anonymous> (../../node_modules/@ngneat/spectator/fesm2022/ngneat-spectator-jest.mjs:1:549)
      at Object.<anonymous> (src/app/components/login/login.component.spec.ts:28:1)
```

### Please provide the environment you discovered this bug in

```true
Nx monorepo with Angular 16
```

### Anything else?

It's this line when setting defaultOptions:
    `deferBlockBehavior: DeferBlockBehavior.Playthrough,`

My assumption is `DeferBlockBehavior` is an ng17 feature which is why it is undefined in my ng16 project?

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
We require Angular v17 https://github.com/ngneat/spectator/blob/master/projects/spectator/package.json#L31
