### ISSUE TITLE
setInput doesn't respect the alias names

### ISSUE THREAD

**Issue by profanis** [ngneat/spectator#648]
### Is this a regression?

Yes

### Description

An alias name of the input is not a valid option in the `setInput` function. This causes the test to fail

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  template: ``,
  styles: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  @Input({alias: 'isVisibleAlias'})
  isVisible: boolean = false;

  @Input('isEnabledAlias')
  isEnabled: boolean = false;
}
```

```ts
describe('AppComponent', () => {
  let spectator: Spectator<AppComponent>;
  const createComponent = createComponentFactory(AppComponent);

  it('respect the alias input names', () => {
    spectator = createComponent({
        props: {
          isVisible: true,
          isEnabled: true,
         // isVisibleAlias: true <-- compilation error
         // isEnabledAlias: true <-- compilation error
       }
    });

    const component = spectator.component;
    expect(component.isVisible).toBeTruthy(); // this test fails
    expect(component.isEnabled).toBeTruthy(); // this test fails
  });
});
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-vn8kfk?file=src%2Ftest.spec.ts

### Please provide the exception or error you saw

```true
The `setInput` should also accept the alias names
```

### Do you want to create a pull request?

Yes

**Comment by profanis** [comment]
How about if we provide a more loose function overload?

https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator/spectator.ts#L44
```ts
  public setInput(input: string, inputValue: unknown): void;
```

I think something similar exists also in Angular repo
https://github.com/angular/angular/blob/da906fdafcbb302fa280a162d1c1f04369be2efa/packages/core/src/linker/component_factory.ts#L34

**Comment by profanis** [comment]
> How about if we provide a more loose function overload?
> 
> https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator/spectator.ts#L44
> 
> ```ts
>   public setInput(input: string, inputValue: unknown): void;
> ```
> 
> I think something similar exists also in Angular repo https://github.com/angular/angular/blob/da906fdafcbb302fa280a162d1c1f04369be2efa/packages/core/src/linker/component_factory.ts#L34

@kfrancois @NetanelBasal what do you think?

**Comment by kfrancois** [comment]
Hi @profanis! Thank you for logging this issue.

I think what you propose is the best possible option at the moment. Unfortunately, inputs aliases are defined as `string`:
```ts
interface InputOptions<ReadT, WriteT> {
    alias?: string;
    transform?: (v: WriteT) => ReadT;
```

If this were a generic type, we would at least be able to infer the correct field name and use it for `setInput` (at least for signal inputs, traditional inputs we wouldn't be able to do anything), but for now it feels safer to lose type info here and go with `input: string, inputValue: unknown`.

**Comment by NetanelBasal** [comment]
I trust you to reach a solution and open a PR

**Comment by NetanelBasal** [comment]
Can we close it?

**Comment by profanis** [comment]
Sorry for the delay. 
This is the relevant PR https://github.com/ngneat/spectator/pull/652
