### ISSUE TITLE
NPM version

### ISSUE THREAD

**Issue by juzeppe9000** [ngneat/spectator#681]
Why is it still version 19.0.0 in NPM, while GitHub version is 19.1.0 and has the fix to support the latest angular version? We had to rewrite the app to outputs or don't use the spectator in tests.

**Comment by milo526** [comment]
@NetanelBasal do you have any insight on when we can expect 19.1.0 to land on NPM?
It has been tagged well over 2 months ago; but it seems like it did not get pushed to NPM.

**Comment by NetanelBasal** [comment]
published v19.1.1
