### ISSUE TITLE
Question: Querying nodes dynamically attached to the body

### ISSUE THREAD

**Issue by IlCallo** [ngneat/spectator#87]
Thank you for the great library! (cit. :P)

I'm testing some components using Angular Material.
Some of those components (dialogs, autocomplete, menu, etc) are implemented using an overlay system which is attached to the body, not inside the component declaring them.

With normal Angular testing API I use something like this (using testid)
`fixture.nativeElement.parentNode.querySelectorAll('[data-testid="testId"]')`.

I find your API much more elegant, so I tryed
`spectator.queryAll(byTestId('testId'))`
hoping it would search in the whole DOM, but was disappointed noticing it still gets limited to the component scope.

Would it be possible to change the search root to the html tag or body tag?

If not by default, at least with some kind of parameter on `query/queryAll` and all other query methods.

Or somehow creating a `Spectator` instance based on a provided `HTMLElement`, in order to allow wrapping of body tag and use the same API in all tests.

**Comment by NetanelBasal** [comment]
You can use one of the global helper methods:
https://github.com/NetanelBasal/spectator/blob/master/projects/spectator/src/lib/internals.ts#L109
https://github.com/NetanelBasal/spectator/blob/2f70012dfd82d9d26facc794fc780fc102df4166/projects/spectator/src/lib/globals.ts

**Comment by IlCallo** [comment]
Surely `query` and `queryAll` are a nice shortcut, ty, even if I couldn't find their reference in the documentation.

Still, they accept a string selector, so I cannot use `byTestId` (or others DOM selectors) with them, which is a pity.
It would be pretty cool to be able to do `query(byTestId('testId'))` to keep consistency with Spectator methods.

Just suggesting...

**Comment by NetanelBasal** [comment]
Yes, this is a helpful suggestion. I'll consider it. Thanks.

**Comment by MartinNuc** [comment]
we use data-test selectors as well just like `.query('[data-testid="testId"')`. So your `byTestId` method could just return such selector.

**Comment by dirkluijk** [comment]
Just wondering, why would you need to query by test id? Never used it before.
Aren't components removed from the DOM after each test?

**Comment by MartinNuc** [comment]
@dirkluijk it's a way how to write your page objects with using specific selector - instead of targeting by class (which might have CSS properties and could change in future) you use special attribute which gives the element special name which is used in test/page object.

**Comment by IlCallo** [comment]
As he said. I actually discovered this pattern  with this library and it's really useful, because I can write tests which do not break when I change the underlying structure and/or class names

**Comment by dirkluijk** [comment]
Since `4.0.0` the we support global queries: `spectator.query('.some-selector', { root: true })`. Please see the updated README for more details about this new feature.

Feel free to open a new ticket if you have ideas or questions.
