### ISSUE TITLE
ngOnDestroy is not called for createService

### ISSUE THREAD

**Issue by MartinNuc** [ngneat/spectator#92]
This is up to discussion and quite possibly Angular issue but maybe we could handle this in the spectator or maybe someone could point me to a correct solution.

[createService](https://github.com/NetanelBasal/spectator/blob/master/projects/spectator/src/lib/service.ts#L27) recreates everytime a new TestingModule using `beforeEach`. Problem is that `ngOnDestroy` for previous module is not called for services - therefore introducing possible memory leaks.

In our case we use it to unsubscribe from observables. In tests these observables are replaced with a subject which is used to control tests. Example:

```
const routerEventsSubject = new Subject();
...
      mockProvider(Router, {
        events: routerEventsSubject
      }),
```

Problem is that this subject is subscribed everytime a new testing module is created but never unsubscribed.

I tried following (probably done by Angular on its own):

```
afterEach(() => {
  TestBed.resetTestingModule();
});
```

but it didnt help. What helped was manually calling unsubscribe:

```
  afterEach(() => {
    spectator.service.ngOnDestroy();
  });
```

But this works only for tested service, not for all providers.

What do you think should be correct approach?

**Comment by NetanelBasal** [comment]
`ngOnDestroy` is only called for non-singletons services.

**Comment by NetanelBasal** [comment]
Maybe we can add it the afterEach block as a default inside the library.

**Comment by MartinNuc** [comment]
I concur. I will make a PR tomorrow if you agree.

**Comment by NetanelBasal** [comment]
I can't see how it can be an issue, so I'm OK with that.
